import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {mkdtemp,readFile,rm} from 'node:fs/promises';import net from 'node:net';import os from 'node:os';import path from 'node:path';import {chromium,webkit} from 'playwright';
const root=process.cwd(),work=await mkdtemp(path.join(os.tmpdir(),'direct-enterprise-')),socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));const url='http://127.0.0.1:'+port;
const seed=spawnSync(process.env.PYTHON||'python3',['scripts/enterprise_ui_fixture.py',path.join(work,'test.db'),path.join(work,'records.json')],{cwd:root,encoding:'utf8'});assert.equal(seed.status,0,seed.stderr);const fixtures=JSON.parse(await readFile(path.join(work,'records.json'),'utf8'));
const child=spawn(process.env.PYTHON||'python3',['server.py'],{cwd:root,env:{...process.env,DIARISTAS_DB_PATH:path.join(work,'test.db'),DIARISTAS_PORT:String(port)},stdio:['ignore','ignore','pipe']});let serverErrors='';child.stderr.on('data',d=>serverErrors+=d.toString());
const api=async(method,route,body)=>{const r=await fetch(url+route,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();assert.ok(r.ok,route+':'+JSON.stringify(d));return d;};

try{
 for(let i=0;i<80;i++){try{await api('GET','/api/lojas');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 const workspace=JSON.parse(await readFile('static/enterprise-schema.json','utf8'));
 for(const [engine,name]of [[chromium,'Chromium'],[webkit,'WebKit']]){const browser=await engine.launch();try{for(const width of [1280,390,320]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url+'/#empresa');await page.locator('#enterprise-area-cards a').last().waitFor();assert.equal(await page.locator('#enterprise-area-cards a').count(),9);assert.equal(await page.locator('#enterprise-record-section').isVisible(),false);assert.equal(await page.locator('#enterprise-local-section').isVisible(),false);
 const areas=await page.evaluate(()=>DirectEnterprise.workspace.areas);
 for(const [area,spec]of Object.entries(areas)){
 await page.locator('#enterprise-area-cards a[href="#empresa?area='+area+'"]').click();await page.waitForFunction(label=>document.getElementById('enterprise-page-title').textContent===label,spec.label);await page.waitForFunction(()=>document.getElementById('enterprise-count').textContent.includes('registro'));
 assert.equal(await page.locator('#enterprise-kinds button').count(),spec.kinds.length);assert.equal(await page.locator('#enterprise-period-section').isVisible(),area==='assistente');assert.equal(await page.locator('#enterprise-local-section').isVisible(),area==='assistente');assert.equal(await page.locator('#enterprise-bank-section').isVisible(),false);assert.equal(await page.locator('#enterprise-cash-section').isVisible(),false);
 await page.locator('#enterprise-new').click();assert.ok(await page.locator('#enterprise-form').isVisible());await page.locator('#enterprise-cancel').click();
 await page.locator('#enterprise-tabs a').click();await page.locator('#enterprise-overview').waitFor();
 }
 // Search and situation really query the server; clear restores the category. Rapid navigation cannot restore old rows.
 await page.locator('#enterprise-area-cards a[href="#empresa?area=cadastros"]').click();await page.waitForFunction(()=>document.getElementById('enterprise-count').textContent.includes('registro'));
 await page.locator('#enterprise-search').fill('NÃO EXISTE QA');await page.waitForFunction(()=>document.getElementById('enterprise-count').textContent.startsWith('0 registro'));assert.match(await page.locator('#enterprise-records').innerText(),/Limpar filtros/);
 await page.locator('#enterprise-clear').click();await page.locator('[data-enterprise-tipo=cliente]').first().waitFor();await page.locator('#enterprise-status').selectOption('arquivado');await page.waitForFunction(()=>document.getElementById('enterprise-count').textContent.startsWith('0 registro'));await page.locator('#enterprise-clear').click();await page.locator('[data-enterprise-tipo=cliente]').first().waitFor();
 await page.locator('#enterprise-search').fill('NÃO EXISTE');await page.getByLabel('Mudar área da empresa').selectOption('materiais');await page.locator('[data-enterprise-tipo=material]').first().waitFor();assert.equal(await page.locator('#enterprise-search').inputValue(),'');
 // All required controls, including a reference with a search box, have independent accessible labels.
 await page.getByLabel('Mudar área da empresa').selectOption('operacao');await page.locator('[data-enterprise-tipo=tarefa]').first().waitFor();await page.locator('#enterprise-new').click();assert.equal(await page.getByLabel('Responsável *',{exact:true}).count(),1);assert.equal(await page.getByLabel('Pedido',{exact:true}).count(),1);await page.locator('#enterprise-fields [name=titulo]').fill('Rascunho QA');await page.locator('#enterprise-cancel').click();
 // Overview filters don't silently hide unrelated category records. Validate bad periods before requesting.
 await page.locator('#enterprise-tabs a').click();await page.locator('#enterprise-start').fill('2026-10-10');await page.locator('#enterprise-end').fill('2026-10-09');await page.locator('#enterprise-filter').click();assert.match(await page.locator('#enterprise-feedback').innerText(),/período válido/);
 await page.locator('#enterprise-start').fill('2026-10-01');await page.locator('#enterprise-filter').click();await page.locator('#enterprise-area-cards a[href="#empresa?area=comercial"]').click();await page.locator('[data-enterprise-tipo=oportunidade]').first().waitFor();
 if(!await page.locator('#enterprise-sidebar').evaluate(e=>e.open))await page.locator('#enterprise-sidebar summary').click();await page.locator('#enterprise-sidebar a[data-enterprise-area=financeiro]').click();await page.locator('[data-enterprise-tipo=despesa]').first().waitFor();await page.getByRole('link',{name:'Simular caixa',exact:true}).click();await page.locator('#enterprise-cash-section').waitFor();assert.equal(await page.locator('#enterprise-record-section').isVisible(),false);await page.locator('#enterprise-cash-opening').fill('100');await page.locator('#enterprise-cash-extra').fill('25');await page.locator('#enterprise-cash-calculate').click();assert.match(await page.locator('#enterprise-cash-result').innerText(),/75,00/);
 await page.getByRole('link',{name:'Contas e extratos',exact:true}).click();await page.locator('#enterprise-bank-section').waitFor();assert.equal(await page.locator('#enterprise-cash-section').isVisible(),false);
 // Optional models don't start by opening a normal page; invalid actions produce useful feedback without downloads.
 await page.getByLabel('Mudar área da empresa').selectOption('assistente');await page.locator('#enterprise-local-section summary').click();await page.getByRole('button',{name:'Sugerir interpretação pelo processador (mais lento)',exact:true}).click();assert.match(await page.locator('#enterprise-local-status').innerText(),/Escreva/);await page.getByRole('button',{name:'Transcrever áudio em português',exact:true}).click();assert.match(await page.locator('#enterprise-local-status').innerText(),/Escolha um áudio/);await page.getByRole('button',{name:'Parar e liberar memória',exact:true}).click();await page.locator('#enterprise-local-input').fill('Conferir presença');await page.getByRole('button',{name:'Levar texto para a Leitura IA',exact:true}).click();await page.waitForFunction(()=>document.getElementById('reading-text').value==='Conferir presença');
 for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),name+' '+width+' overflow');}
 assert.deepEqual(errors,[]);console.log(name+' '+width+': nine dedicated areas, contextual tools, working filters, sidebar, labelled forms, cash, optional model validation, text handoff and themes passed.');await page.close();
 }
 // Role navigation respects entity read/write permissions, including direct old links.
 for(const role of ['operacao','financeiro','consulta']){const page=await browser.newPage();await page.addInitScript(r=>window.directRemote={role:r,request:async(url,options)=>{const response=await fetch(url,options),data=await response.json();if(!response.ok)throw Error(data.erro);return data;}},role);await page.goto(url+'/#empresa');await page.locator('#enterprise-area-cards a').last().waitFor();
 for(const [kind,spec]of Object.entries(workspace.entities)){await page.goto(url+'/#empresa?tipo='+kind);await page.waitForFunction(()=>window.DirectEnterprise);if(spec.read.includes(role)){await page.waitForFunction(label=>document.getElementById('enterprise-kind-title').textContent===label,spec.label);assert.equal(await page.locator('#enterprise-new').isVisible(),spec.write.includes(role));}else{await page.locator('#enterprise-feedback').waitFor();assert.match(await page.locator('#enterprise-feedback').innerText(),/perfil não pode/);assert.notEqual(await page.locator('#enterprise-kind-title').innerText(),spec.label);}}
 if(role==='consulta'){assert.equal(await page.locator('[data-enterprise-area=financeiro]').isVisible(),false);assert.equal(await page.locator('[data-enterprise-area=comercial]').isVisible(),false);}
 await page.close();console.log(name+' '+role+': direct links and write controls respect all 35 entity permissions.');}
 }finally{await browser.close();}}
 // Pagination and the exported CSV include the visible category fields, bounded to the selected page.
 for(let i=0;i<29;i++)await api('POST','/api/empresa/registro',{tipo:'cliente',titulo:'Cliente QA '+i,status:'ativo',dados:{segmento:'eventos'},chave:crypto.randomUUID()});
 const browser=await chromium.launch();try{const page=await browser.newPage({acceptDownloads:true});await page.goto(url+'/#empresa?tipo=cliente');await page.waitForFunction(()=>document.getElementById('enterprise-count').textContent.startsWith('30 registro'));assert.equal(await page.locator('[data-enterprise-tipo=cliente]').count(),25);await page.locator('#enterprise-next').click();await page.waitForFunction(()=>document.getElementById('enterprise-count').textContent.includes('Página 2'));assert.equal(await page.locator('[data-enterprise-tipo=cliente]').count(),5);const downloaded=page.waitForEvent('download');await page.locator('#enterprise-export').click();const file=await downloaded,csv=await readFile(await file.path(),'utf8');assert.match(csv,/Segmento/);assert.match(csv,/Eventos/);assert.equal(csv.trim().split('\r\n').length,6);await page.locator('#enterprise-prev').click();await page.waitForFunction(()=>document.getElementById('enterprise-count').textContent.includes('Página 1'));await page.reload();await page.locator('[data-enterprise-tipo=cliente]').first().waitFor();console.log('Pagination, full category fields in CSV and reload passed.');}finally{await browser.close();}
} catch(e){console.error(serverErrors.slice(-1000));throw e;}finally{child.kill();await new Promise(r=>child.once('exit',r));await rm(work,{recursive:true,force:true});}
