import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {mkdtemp,readFile,rm} from 'node:fs/promises';import net from 'node:net';import os from 'node:os';import path from 'node:path';import {chromium,webkit} from 'playwright';
const root=process.cwd(),work=await mkdtemp(path.join(os.tmpdir(),'direct-enterprise-flow-')),socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));const url='http://127.0.0.1:'+port;
const seed=spawnSync(process.env.PYTHON||'python3',['scripts/enterprise_ui_fixture.py',path.join(work,'test.db'),path.join(work,'records.json')],{cwd:root,encoding:'utf8'});assert.equal(seed.status,0,seed.stderr);const f=JSON.parse(await readFile(path.join(work,'records.json'),'utf8'));
const child=spawn(process.env.PYTHON||'python3',['server.py'],{cwd:root,env:{...process.env,DIARISTAS_DB_PATH:path.join(work,'test.db'),DIARISTAS_PORT:String(port)},stdio:['ignore','ignore','pipe']});let stderr='';child.stderr.on('data',d=>stderr+=d);
const api=async(method,route,body)=>{const r=await fetch(url+route,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),d=await r.json();assert.ok(r.ok,route+':'+JSON.stringify(d));return d;};
try{for(let i=0;i<80;i++){try{await api('GET','/api/lojas');break;}catch{await new Promise(r=>setTimeout(r,100));}}
for(const [engine,name]of [[chromium,'Chromium'],[webkit,'WebKit']]){const browser=await engine.launch();try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.copies=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async t=>window.copies.push(t)}});});
await page.goto(url+'/#empresa?tipo=tarefa');await page.waitForFunction(()=>window.DirectEnterprise);
const save=async()=>{await page.locator('#enterprise-form button[type=submit]').click();await page.locator('#enterprise-review').waitFor();const response=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/empresa/registro'));await page.locator('#enterprise-confirm').click();const r=await response;assert.equal(r.status(),200,await r.text());const data=await r.json();await page.locator('#enterprise-dialog').waitFor({state:'hidden'});return data;};
// Private compressed photo has an actual byte download and a metadata/sha link.
await page.evaluate(r=>DirectEnterprise.detail(r),f.tarefa);await page.getByLabel('Foto ou comprovante para '+f.tarefa.titulo).setInputFiles({name:'evidencia.png',mimeType:'image/png',buffer:Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=40;c.getContext('2d').fillRect(0,0,40,40);return c.toDataURL().split(',')[1];}),'base64')});await page.getByRole('button',{name:'Revisar foto',exact:true}).click();await page.getByRole('button',{name:'Confirmar envio da foto'}).click();await page.locator('#enterprise-dialog').waitFor({state:'hidden'});const photos=await api('GET','/api/empresa/anexos?registro_id='+f.tarefa.id);assert.ok(photos.length);const photo=await fetch(url+'/api/empresa/foto?id='+photos[0].id);assert.equal(photo.headers.get('content-type'),'image/jpeg');assert.equal((await photo.arrayBuffer()).byteLength,photos[0].bytes);
// Payment beneficiary/amounts are picked from native pending daily rows.
const worker=f.pagamento_revisao.dados.diarista_id,today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const daily=await api('POST','/api/diaristas/'+worker+'/diarias',{data:today,local:'Super Lagoa',setor:'Eventos',valor:'45.00',valor_recebido:'80.00',vencimento_pagamento:today,vencimento_recebimento:today});
await page.evaluate(()=>location.hash='#empresa?tipo=pagamento_revisao');await page.waitForFunction(()=>document.getElementById('enterprise-kind-title').textContent===DirectEnterprise.model.schema.entities.pagamento_revisao.label);await page.locator('#enterprise-new').click();await page.locator('#enterprise-fields [name=titulo]').fill('Pagamento QA '+name);await page.locator('#enterprise-fields [name=diarista_id]').selectOption(String(worker));await page.locator('#enterprise-fields [name=diaria_ids] option[value="'+daily.id+'"]').waitFor({state:'attached'});await page.locator('#enterprise-fields [name=diaria_ids]').selectOption(String(daily.id));await page.locator('#enterprise-fields [name=responsavel]').fill('Financeiro QA');const review=await save();await page.evaluate(r=>DirectEnterprise.openForm(r),review);await page.locator('#enterprise-fields [name=status]').selectOption('aprovado');const approved=await save();await page.locator('[data-enterprise-id="'+approved.id+'"]').getByRole('button',{name:'Registrar pagamento'}).click().catch(async e=>{console.error('PAYMENT',await page.locator('#enterprise-feedback').innerText(),await api('GET','/api/empresa/lista?tipo=pagamento_revisao'),await page.locator('#enterprise-records').innerText());throw e;});await page.getByLabel('Forma do pagamento realizado').fill('Pix QA');await page.getByRole('button',{name:'Confirmar pagamento realizado'}).click();await page.locator('#enterprise-dialog').waitFor({state:'hidden'});const paid=(await api('GET','/api/diaristas/'+worker+'/diarias')).find(r=>r.id===daily.id);assert.equal(paid.valor_centavos,4500);assert.ok(paid.data_pagamento&&paid.pagamento_lote_id);
// Approved external report returns only the human-reviewed client content.
const contract=await page.evaluate(()=>DirectEnterprise.model.schema),data=Object.fromEntries(contract.entities.relatorio.fields.filter(k=>f.relatorio.dados[k.name]!==undefined).map(k=>[k.name,f.relatorio.dados[k.name]]));const current=await api('GET','/api/empresa/registro?id='+f.relatorio.id);const report=current.status==='aprovado'?current:await api('POST','/api/empresa/registro',{id:current.id,versao:current.versao,tipo:'relatorio',titulo:current.titulo,status:'aprovado',dados:{...data,aprovado_por:'Supervisão QA'},chave:current.chave});await page.evaluate(()=>location.hash='#empresa?tipo=relatorio');await page.waitForFunction(()=>document.getElementById('enterprise-kind-title').textContent===DirectEnterprise.model.schema.entities.relatorio.label);await page.locator('[data-enterprise-id="'+report.id+'"]').getByRole('button',{name:'Copiar link do relatório'}).click();await page.waitForFunction(()=>window.copies.length>0);const external=await browser.newPage();await external.goto(await page.evaluate(()=>copies.at(-1)));await external.locator('#report-results').waitFor();assert.equal(await external.locator('#report-results').innerText(),report.dados.resultado);assert.doesNotMatch(await external.locator('body').innerText(),/52998224725|valor_centavos|custo_unitario/);await external.close();
// Campaign report, reserves, history, cash, analytical sources and native quote conversion.
const navigate=async kind=>{await page.evaluate(k=>location.hash='#empresa?tipo='+k,kind);await page.waitForFunction(k=>document.getElementById('enterprise-kind-title').textContent===DirectEnterprise.model.schema.entities[k].label,kind);await page.locator('[data-enterprise-tipo="'+kind+'"]').first().waitFor();};
await navigate('campanha');await page.getByRole('button',{name:'Resultados da campanha'}).click();await page.getByRole('button',{name:'Preparar relatório para o cliente'}).click();await page.locator('#enterprise-form').waitFor();assert.ok((await page.locator('#enterprise-fields [name=titulo]').inputValue()).startsWith('Resultado:'));await page.locator('#enterprise-cancel').click();
await navigate('cliente');await page.getByRole('button',{name:'Histórico de relacionamento'}).click();await page.locator('#enterprise-details').waitFor();assert.match(await page.locator('#enterprise-dialog-title').innerText(),/Histórico/);await page.locator('#enterprise-close').click();
await page.evaluate(id=>DirectEnterprise.reserves(id),f.vinculo.pedido_id);await page.locator('#enterprise-details').waitFor();assert.match(await page.locator('#enterprise-details').innerText(),/horários/);await page.locator('#enterprise-close').click();
await navigate('material');await page.getByRole('button',{name:'Consultar saldo'}).click();await page.waitForFunction(()=>document.getElementById('enterprise-feedback').textContent.includes('disponíveis'));
await navigate('aviso');await page.getByRole('button',{name:'Confirmar minha leitura'}).click();await page.waitForFunction(()=>document.getElementById('enterprise-feedback').textContent.includes('leitura foi registrada'));
await page.goto(url+'/#empresa?area=financeiro&view=caixa');await page.locator('#enterprise-cash-section').waitFor();for(const [key,value]of Object.entries({opening:'100,00',receipts:'50,00',payments:'30,00',extra:'20,00',delayed:'10,00'}))await page.locator('#enterprise-cash-'+key).fill(value);await page.locator('#enterprise-cash-calculate').click();assert.match(await page.locator('#enterprise-cash-result').innerText(),/90,00/);
await page.evaluate(()=>location.hash='#empresa?tipo=frase');await page.locator('#enterprise-question').waitFor();await page.locator('#enterprise-question').fill('Quais vagas estão abertas?');await page.locator('#enterprise-ask').click();await page.waitForFunction(()=>document.getElementById('enterprise-answer').textContent.includes('Fonte:'));
await navigate('proposta');let quote=await api('GET','/api/empresa/registro?id='+f.proposta.id);if(quote.status==='rascunho'){await page.evaluate(r=>DirectEnterprise.openForm(r),quote);await page.locator('#enterprise-fields [name=status]').selectOption('enviada');quote=await save();}if(quote.status==='enviada'){await page.evaluate(r=>DirectEnterprise.openForm(r),quote);assert.ok(await page.locator('#enterprise-fields [name=titulo]').isDisabled());await page.locator('#enterprise-fields [name=status]').selectOption('aprovada');quote=await save();}if(quote.status==='aprovada'){const count=(await api('GET','/api/pedidos')).length;await page.locator('[data-enterprise-id="'+quote.id+'"]').getByRole('button',{name:'Gerar pedido',exact:true}).click();await page.getByRole('button',{name:'Confirmar e gerar pedido'}).click();await page.locator('#enterprise-dialog').waitFor({state:'hidden'});assert.equal((await api('GET','/api/pedidos')).length,count+1);}
// The client request stays pending for human approval for each guided service.
const store=(await api('GET','/api/lojas'))[0],link=await api('POST','/api/lojas/'+store.id+'/link',{acao:'consultar'});const portal=await browser.newPage({viewport:{width:390,height:844}});portal.on('pageerror',e=>errors.push(e.message));await portal.goto(url+'/loja.html#convite='+link.token);await portal.locator('#store-portal-app').waitFor();for(const type of ['reposicao','degustacao','evento']){await portal.locator('#store-service-type').selectOption(type);if(type==='degustacao')await portal.locator('#store-service-product').fill('Produto QA');if(type==='evento')await portal.locator('#store-service-event').fill('Entrada QA');await portal.locator('#store-request-start').fill(today);await portal.locator('#store-request-sector').selectOption({index:1});portal.once('dialog',d=>d.accept());const sent=portal.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('/api/loja-portal/submit'));await portal.locator('#store-request-submit').click();const sentResponse=await sent;assert.equal(sentResponse.status(),200,await sentResponse.text());await portal.waitForFunction(()=>document.getElementById('store-portal-feedback').textContent.includes('enviada'));}
const requests=await api('GET','/api/solicitacoes-lojas');assert.ok(requests.some(r=>r.dados.observacoes.includes('Produto QA')));assert.ok(requests.some(r=>r.dados.observacoes.includes('Entrada QA')));assert.ok(requests.every(r=>r.estado==='pendente'));assert.ok(await portal.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));assert.deepEqual(errors,[]);console.log(name+': compressed private photo bytes, payment review→native batch, public approved report, and all 3 guided portal service types passed.');await portal.close();await page.close();}finally{await browser.close();}}}
catch(e){console.error(stderr.slice(-1500));throw e;}finally{child.kill();await new Promise(r=>child.once('exit',r));await rm(work,{recursive:true,force:true});}
