import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {mkdtemp,readFile,rm} from 'node:fs/promises';import net from 'node:net';import os from 'node:os';import path from 'node:path';import {chromium,webkit} from 'playwright';
const root=process.cwd(),work=await mkdtemp(path.join(os.tmpdir(),'direct-enterprise-')),socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));const url='http://127.0.0.1:'+port;
const seed=spawnSync(process.env.PYTHON||'python3',['scripts/enterprise_ui_fixture.py',path.join(work,'test.db'),path.join(work,'records.json')],{cwd:root,encoding:'utf8'});assert.equal(seed.status,0,seed.stderr);const fixtures=JSON.parse(await readFile(path.join(work,'records.json'),'utf8'));
const child=spawn(process.env.PYTHON||'python3',['server.py'],{cwd:root,env:{...process.env,DIARISTAS_DB_PATH:path.join(work,'test.db'),DIARISTAS_PORT:String(port)},stdio:['ignore','ignore','pipe']});let serverErrors='';child.stderr.on('data',d=>serverErrors+=d.toString());
const api=async(method,route,body)=>{const r=await fetch(url+route,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();assert.ok(r.ok,route+':'+JSON.stringify(d));return d;};
const engines=process.env.DIRECT_ENTERPRISE_WEBKIT?[[webkit,'WebKit']]:(process.env.DIRECT_ENTERPRISE_SMOKE||process.env.DIRECT_ENTERPRISE_MOBILE)?[[chromium,'Chromium']]:[[chromium,'Chromium'],[webkit,'WebKit']];
try{
 for(let i=0;i<80;i++){try{await api('GET','/api/lojas');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 for(const [engine,name]of engines){const browser=await engine.launch();try{for(const width of process.env.DIRECT_ENTERPRISE_SMOKE?[1280]:process.env.DIRECT_ENTERPRISE_MOBILE?[390]:[1280,390,320]){
  const context=await browser.newContext({viewport:{width,height:900},isMobile:width<500,hasTouch:width<500}),page=await context.newPage(),errors=[];page.setDefaultTimeout(30000);page.on('pageerror',e=>{errors.push(e.message);console.error('BROWSER',e.message);});await page.addInitScript(()=>{window.copies=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async t=>window.copies.push(t)}});});
  await page.goto(url+'/#empresa');await page.waitForFunction(()=>window.DirectEnterprise&&document.querySelector('#enterprise-count').textContent.includes('registro'));const contract=await page.evaluate(()=>DirectEnterprise.model.schema);
  for(const [kind,spec]of Object.entries(contract.entities)){console.log('FORM',name,width,kind);
    await page.evaluate(k=>location.hash='#empresa?tipo='+k,kind);await page.waitForFunction(k=>document.getElementById('enterprise-kind-title').textContent===DirectEnterprise.model.schema.entities[k].label,kind);await page.waitForTimeout(50);
    const r=await api('GET','/api/empresa/registro?id='+fixtures[kind].id);
    await page.evaluate(r=>DirectEnterprise.detail(r),r);await page.locator('#enterprise-details').waitFor();assert.match(await page.locator('#enterprise-dialog-title').innerText(),new RegExp(r.titulo));await page.locator('#enterprise-close').click();
    const immutable=['movimento','movimento_caixa','ciencia','leitura_aviso'].includes(kind)||kind==='briefing';
    if(!immutable){await page.evaluate(r=>DirectEnterprise.openForm(r),r);await page.locator('#enterprise-fields input[name=titulo]').fill(r.titulo+' QA');await page.locator('#enterprise-form button[type=submit]').click();await page.locator('#enterprise-review').waitFor();const response=page.waitForResponse(res=>res.request().method()==='POST'&&res.url().includes('/api/empresa/registro'));await page.locator('#enterprise-confirm').click();const res=await response;assert.equal(res.status(),200,kind+':'+await res.text());await page.locator('#enterprise-dialog').waitFor({state:'hidden'});const saved=await api('GET','/api/empresa/registro?id='+r.id);assert.equal(saved.versao,r.versao+1);for(const field of spec.fields)if(r.dados[field.name]!==undefined)assert.deepEqual(saved.dados[field.name],r.dados[field.name],kind+' preserved '+field.name);}
    if(!await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)){await page.screenshot({path:'/tmp/direct-enterprise-overflow.png',fullPage:true});console.error('OVERFLOW',await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,nodes:[...document.querySelectorAll('#empresa-page *')].filter(n=>n.getClientRects().length&&n.getBoundingClientRect().right>innerWidth+2).map(n=>({tag:n.tagName,id:n.id,cls:n.className,width:n.getBoundingClientRect().width,right:n.getBoundingClientRect().right})).slice(0,25)})));throw Error(kind+' overflow '+name+' '+width);}
  }
  await page.evaluate(()=>location.hash='#empresa?tipo=tarefa');await page.waitForFunction(()=>document.getElementById('enterprise-kind-title').textContent===DirectEnterprise.model.schema.entities.tarefa.label);await page.locator('#enterprise-new').click();await page.locator('#enterprise-cancel').click();assert.equal(await page.locator('#enterprise-dialog').evaluate(e=>e.open),false);
  await page.getByText('Como começar e treinar a equipe',{exact:true}).click().catch(async e=>{await page.screenshot({path:'/tmp/direct-enterprise-summary-error.png',fullPage:true});console.error(await page.getByText('Como começar e treinar a equipe',{exact:true}).evaluate(n=>({button:n.getBoundingClientRect().toJSON(),hit:document.elementFromPoint(n.getBoundingClientRect().x+10,n.getBoundingClientRect().y+10)?.outerHTML.slice(0,250)})));throw e;});await page.locator('#enterprise-training').click().catch(async e=>{await page.screenshot({path:'/tmp/direct-enterprise-training-error.png',fullPage:true});console.error(await page.locator('#enterprise-training').evaluate(n=>({button:n.getBoundingClientRect().toJSON(),parent:n.parentElement.getBoundingClientRect().toJSON(),hit:document.elementFromPoint(n.getBoundingClientRect().x+10,n.getBoundingClientRect().y+10)?.outerHTML.slice(0,300)})));throw e;});await page.getByRole('button',{name:'Financeiro ou administrador',exact:true}).click();assert.match(await page.locator('#enterprise-details').innerText(),/Correto/);await page.locator('#enterprise-close').click();
  await page.evaluate(()=>location.hash='#empresa?tipo=conta');await page.locator('#enterprise-bank-section').waitFor();await page.locator('#enterprise-bank-account').selectOption(String(fixtures.conta.id));await page.locator('#enterprise-bank-file').setInputFiles({name:'qa.csv',mimeType:'text/csv',buffer:Buffer.from('data;valor;descricao;identificador\n08/10/2026;-30,00;Transporte QA;QA-'+name+width)});await page.locator('#enterprise-bank-import').click();await page.locator('#enterprise-review').waitFor();await page.locator('#enterprise-confirm').click();await page.locator('#enterprise-dialog').waitFor({state:'hidden'});await page.locator('#enterprise-bank-load').click();await page.getByRole('button',{name:'Conferir vínculo',exact:true}).last().click();await page.getByLabel('Tipo do vínculo').selectOption('ignorar');await page.getByLabel('Justificativa da conferência').fill('Linha de ensaio sem vínculo');await page.locator('#enterprise-confirm').click();await page.locator('#enterprise-dialog').waitFor({state:'hidden'});
  await page.locator('#enterprise-bank-file').setInputFiles({name:'columns.csv',mimeType:'text/csv',buffer:Buffer.from('Dia;Quantia;Texto\n08/10/2026;30,00;QA mapeamento')});await page.locator('#enterprise-bank-import').click();await page.getByRole('button',{name:'Revisar colunas escolhidas'}).waitFor();await page.locator('#enterprise-details').getByLabel('Data',{exact:true}).selectOption('0');await page.locator('#enterprise-details').getByLabel('Valor com sinal').selectOption('1');await page.locator('#enterprise-details').getByLabel('Descrição',{exact:true}).selectOption('2');await page.getByRole('button',{name:'Revisar colunas escolhidas'}).click();await page.locator('#enterprise-review').waitFor();await page.locator('#enterprise-cancel').click();
  for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}
  await page.reload();await page.waitForFunction(()=>window.DirectEnterprise&&document.getElementById('enterprise-count').textContent.includes('registro'));assert.deepEqual(errors,[]);await page.screenshot({path:'/tmp/direct-enterprise-'+name+'-'+width+'.png',fullPage:true});console.log(name+' '+width+': all 35 forms read; editable forms reviewed/saved, detail, cancel, training, bank import/mapping/review, reload and responsive layout passed.');await context.close();
 }}finally{await browser.close();}}
} catch(e){console.error(serverErrors.slice(-2000));throw e;}finally{child.kill();await new Promise(r=>child.once('exit',r));await rm(work,{recursive:true,force:true});}
