import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtemp,rm} from 'node:fs/promises';import net from 'node:net';import os from 'node:os';import path from 'node:path';import {chromium,webkit} from 'playwright';
const root=process.cwd(),work=await mkdtemp(path.join(os.tmpdir(),'direct-management-')),socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));const url='http://127.0.0.1:'+port;
const child=spawn(process.env.PYTHON||'python3',['server.py'],{cwd:root,env:{...process.env,DIARISTAS_DB_PATH:path.join(work,'test.db'),DIARISTAS_PORT:String(port)},stdio:['ignore','ignore','pipe']});let serverErrors='';child.stderr.on('data',d=>serverErrors+=d.toString());
const api=async(method,route,body)=>{const r=await fetch(url+route,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();assert.ok(r.ok,route+':'+JSON.stringify(d));return d;};
let serial=999301000;const cpfFor=n=>{let v=String(n);for(let size=9;size<=10;size++){const sum=[...v].reduce((t,x,i)=>t+Number(x)*(size+1-i),0),digit=sum*10%11;v+=digit===10?'0':String(digit);}return v;};
try{
 for(let i=0;i<80;i++){try{await api('GET','/api/lojas');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 const stores=await api('GET','/api/lojas'),store=stores.find(s=>s.rede==='Super do Povo'&&s.nome==='Meireles'),other=stores.find(s=>s.rede==='Hipermarket');assert.ok(store&&other);
 const invite=await api('POST','/api/lojas/'+store.id+'/link',{acao:'consultar'}),otherLink=await api('POST','/api/lojas/'+other.id+'/link',{acao:'consultar'}),token=invite.token;
 const date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());let done=0;
 for(const [engine,name]of (process.env.DIRECT_MANAGEMENT_SMOKE?[[chromium,'Chromium']]:(process.env.DIRECT_MANAGEMENT_WEBKIT?[[webkit,'WebKit']]:[[chromium,'Chromium'],[webkit,'WebKit']]))){
 const browser=await engine.launch();try{for(const width of process.env.DIRECT_MANAGEMENT_SMOKE?[1280]:[1280,390,320]){
 const context=await browser.newContext({viewport:{width,height:844},isMobile:width<500,hasTouch:width<500}),admin=await context.newPage(),client=await context.newPage(),errors=[];
 for(const page of [admin,client])page.on('pageerror',e=>errors.push(e.message));
 await admin.addInitScript(()=>{window.copies=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.copies.push(text)}});window.print=()=>window.printed=document.querySelector('.management-print-text')?.textContent;});
 await client.goto(url+'/loja.html#convite='+token);await client.locator('#store-portal-app').waitFor();assert.match(await client.locator('#store-portal-title').innerText(),/Meireles/);
 await client.locator('#store-request-sector').selectOption({label:'Repositor de FLV'});await client.locator('#store-request-days').fill('2');await client.locator('#store-request-start').fill(date);await client.locator('#store-request-time').fill('07:00');await client.locator('#store-request-end').fill('15:20');
 client.once('dialog',d=>d.accept());await client.locator('#store-request-submit').click();await client.waitForFunction(()=>document.querySelector('#store-portal-feedback').textContent.includes('enviada'));
 const requests=await api('GET','/api/solicitacoes-lojas'),request=requests.find(r=>r.estado==='pendente');assert.ok(request);assert.equal((await api('GET','/api/pedidos')).length,done,'Loja não publica pedido sem Direct');
 await admin.goto(url+'/#pedidos');await admin.locator('#store-requests-button').waitFor();await admin.waitForFunction(()=>Number(document.querySelector('#store-requests-count').textContent)>0);await admin.locator('#store-requests-button').click();await admin.locator('#management-body').getByRole('button',{name:'Revisar pedido'}).click().catch(async e=>{await admin.screenshot({path:'/tmp/direct-management-debug.png',fullPage:true});console.error('HANDLER',await admin.evaluate(()=>({open:document.querySelector('#management-dialog').open,handler:String(document.querySelector('#store-requests-button').onclick),hash:location.hash})),errors);console.error('QUEUE DEBUG',await admin.locator('#management-body').innerText(),await admin.locator('#crm-feedback').innerText(),JSON.stringify(await api('GET','/api/solicitacoes-lojas')),serverErrors.slice(-4000));throw e;});await admin.locator('#order-dialog').waitFor();assert.equal(await admin.locator('#order-unit').inputValue(),'Meireles');assert.equal(await admin.locator('.order-shift-date').count(),2);
 await admin.locator('#order-save-button').click();await admin.locator('#order-dialog').waitFor({state:'hidden'});const storedRequests=await api('GET','/api/solicitacoes-lojas'),approved=storedRequests.find(r=>r.id===request.id);assert.equal(approved.estado,'aprovada');const orderId=approved.pedido_id;assert.ok(orderId);
 const worker=await api('POST','/api/diaristas',{nome:'Pessoa Loja '+name+' '+width,cpf:cpfFor(++serial),setores:['Repositor de FLV'],pode_se_deslocar:true,trabalhando:false,disponibilidade:['segunda','terca','quarta','quinta','sexta','sabado','domingo'].map(dia=>({dia,inicio:'00:00',fim:'23:59'}))});
 const slots=(await api('GET','/api/pedidos')).find(o=>o.id===orderId).turnos;await api('POST','/api/pedidos/'+orderId+'/escalas',{datas:slots.map(t=>t.data),diarista_id:worker.id});
 // Another store cannot see this request/order/team.
 const otherData=await api('POST','/api/loja-portal/orders',{p_token:otherLink.token});assert.equal(otherData.pedidos.some(o=>o.id===orderId),false);
 await client.locator('#store-tab-orders').click();await client.locator('#store-orders-refresh').click();const card=client.locator('#store-portal-orders article').filter({has:client.getByRole('heading',{name:'Pedido #'+orderId+' · Repositor de FLV',exact:true})});await card.waitFor();await card.locator('summary').first().click();await card.getByText(worker.nome,{exact:true}).first().waitFor();client.once('dialog',d=>d.accept());await card.getByRole('button',{name:'Conferir presença'}).click();await client.waitForFunction(()=>document.querySelector('#store-portal-feedback').textContent.includes('Conferência enviada'));
 const scale=(await api('GET','/api/pedidos/'+orderId+'/escalas'))[0];assert.equal(scale.status,'escalada');assert.equal((await api('GET','/api/diaristas/'+worker.id+'/diarias')).length,0,'Portal não gera pagamento antes da revisão');
 await admin.locator('#nav-crm').click();await admin.waitForFunction(()=>!document.querySelector('#store-pending-panel').hidden);await admin.locator('#store-pending-panel>summary').click();admin.once('dialog',d=>d.accept());
 const appliedResponse=admin.waitForResponse(response=>response.request().method()==='PATCH'&&new URL(response.url()).pathname.startsWith('/api/conferencias-lojas/'));
 await admin.locator('#store-pending-list').getByRole('button',{name:'Aplicar presença',exact:true}).click();const applied=await appliedResponse;assert.equal(applied.status(),200);assert.equal((await applied.json()).ok,true);
 await admin.waitForFunction(()=>document.querySelector('#store-requests-count').textContent==='0');
 const dailyRows=await api('GET','/api/diaristas/'+worker.id+'/diarias');assert.equal(dailyRows.length,1,'Conferência aprovada cria exatamente uma diária');const daily=dailyRows[0];assert.equal(daily.valor_centavos,9000);assert.equal(daily.valor_recebido_centavos,13400);await admin.evaluate(()=>loadHome());
 await admin.locator('#daily-summary-button').click();await admin.locator('#management-preview').waitFor().catch(async e=>{await admin.screenshot({path:'/tmp/direct-management-daily-debug.png',fullPage:true});console.error('DAILY DEBUG',await admin.evaluate(()=>({date:homeToday(),open:document.querySelector('#management-dialog').open,body:document.querySelector('#management-body').textContent,feedback:document.querySelector('#management-feedback').textContent})),errors);throw e;});assert.match(await admin.locator('#management-preview').inputValue(),new RegExp(worker.nome));await admin.locator('#management-copy').click();assert.match(await admin.evaluate(()=>copies.at(-1)),/RESUMO DA OPERAÇÃO/);await admin.locator('#management-close').click();
 await admin.locator('#nav-redes').click();await admin.locator('#stores-network-filter').selectOption('Super do Povo');await admin.locator('#stores-search').fill('Meireles');assert.equal(await admin.getByRole('button',{name:'↗ Link da loja',exact:true}).count(),0);await admin.getByRole('button',{name:'Relatório mensal de Meireles',exact:true}).click();await admin.locator('#management-preview').waitFor();assert.match(await admin.locator('#management-preview').inputValue(),/RELATÓRIO DE ATENDIMENTO/);assert.doesNotMatch(await admin.locator('#management-preview').inputValue(),new RegExp(worker.cpf));await admin.locator('#management-print').click();assert.match(await admin.evaluate(()=>printed),/Meireles/);await admin.locator('#management-copy').click();assert.match(await admin.evaluate(()=>copies.at(-1)),/Presenças:/);await admin.locator('#management-close').click();
 await admin.locator('#nav-financeiro').click();await admin.locator('#cash-agenda>summary').click();await admin.waitForFunction(()=>document.querySelector('#cash-agenda-summary').children.length===4);const cashNumber=async i=>Number((await admin.locator('#cash-agenda-summary strong').nth(i).innerText()).replace(/\D/g,''));const beforePaid=await cashNumber(3),beforePending=await cashNumber(1);
 await api('PATCH','/api/diaristas/'+worker.id+'/diarias/'+daily.id+'/pagamento',{data_pagamento:date,valor:'90.00',forma_pagamento:'Pix',vencimento_pagamento:daily.vencimento_pagamento});await admin.evaluate(()=>loadFinance());await admin.waitForFunction(()=>document.querySelector('#cash-agenda-summary').children.length===4);assert.equal(await cashNumber(3),beforePaid+9000);assert.equal(await cashNumber(1),beforePending-9000);
 assert.ok(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));assert.ok(await client.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));if(width<500)assert.ok(await client.evaluate(()=>[...document.querySelectorAll('input,select,textarea')].filter(x=>x.getClientRects().length).every(x=>parseFloat(getComputedStyle(x).fontSize)>=16)));
 for(const theme of ['light','dark']){await admin.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert.ok(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}
 await admin.locator('#cash-agenda').screenshot({path:'/tmp/direct-lote2-agenda-'+name+'-'+width+'.png',animations:'disabled'});await client.screenshot({path:'/tmp/direct-lote2-loja-'+name+'-'+width+'.png',animations:'disabled'});assert.deepEqual(errors,[]);console.log(name+' '+width+': portal restrito, pedido revisado, escala, conferência→financeiro, resumo, relatório, impressão, agenda, cópia e layout OK');done++;await context.close();
 }}finally{await browser.close();}}
 await api('POST','/api/lojas/'+store.id+'/link',{acao:'revogar'});const revoked=await fetch(url+'/api/loja-portal/context',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_token:token})});assert.equal(revoked.status,400);
}finally{child.kill();await new Promise(r=>child.once('exit',r));await rm(work,{recursive:true,force:true});}
