import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';import {mkdtemp,rm} from 'node:fs/promises';import net from 'node:net';import os from 'node:os';import path from 'node:path';import {chromium,webkit} from 'playwright';
const root=process.cwd(),work=await mkdtemp(path.join(os.tmpdir(),'direct-network-')),socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));const url='http://127.0.0.1:'+port;
const child=spawn(process.env.PYTHON||'python3',['server.py'],{cwd:root,env:{...process.env,DIARISTAS_DB_PATH:path.join(work,'test.db'),DIARISTAS_PORT:String(port)},stdio:['ignore','ignore','pipe']});let logs='';child.stderr.on('data',d=>logs+=d);
const api=async(route,body)=>{const r=await fetch(url+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();assert.ok(r.ok,route+JSON.stringify(d));return d;};
try{
 for(let i=0;i<80;i++){try{await api('/api/lojas');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 const stores=await api('/api/lojas'),ours=stores.filter(s=>s.rede==='Super do Povo'),other=stores.find(s=>s.rede==='Hipermarket'),otherLink=await api('/api/redes-links',{rede:'Hipermarket'});
 const foreign=await api('/api/rede-portal/submit',{p_token:otherLink.codigo,p_loja_id:other.id,p_chave:crypto.randomUUID(),p_dados:{setor:'Repositor de FLV',quantidade_diaristas:1,turnos:[{data:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza'}).format(new Date()),inicio:'07:00',fim:'15:20'}],contato:'EXCLUSIVO HIPERMARKET',observacoes:''}});
 for(const [engine,name]of [[chromium,'Chromium'],[webkit,'WebKit']]){const browser=await engine.launch();try{for(const width of [1280,390,320]){
 const context=await browser.newContext({viewport:{width,height:844},isMobile:width<500,hasTouch:width<500}),admin=await context.newPage(),client=await context.newPage(),errors=[];for(const p of [admin,client])p.on('pageerror',e=>errors.push(e.message));await admin.addInitScript(()=>{window.copies=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.copies.push(text)}});});
 await admin.goto(url+'/#pedidos-links');const card=admin.locator('.network-category-card').filter({has:admin.getByRole('heading',{name:'Super do Povo',exact:true})});await card.waitFor();await card.click();await admin.locator('#network-detail').waitFor();assert.equal(await admin.locator('#network-page-title').textContent(),'Super do Povo');assert.equal(await admin.locator('#network-requests-list').getByText('EXCLUSIVO HIPERMARKET',{exact:false}).count(),0);assert.equal(await admin.getByRole('button',{name:/Renovar|Revogar|Gerar link/}).count(),0);await admin.getByRole('button',{name:'Copiar link',exact:true}).click();const link=await admin.evaluate(()=>copies.at(-1));assert.match(link,/\/r\/[A-Za-z0-9_-]{16}$/);await client.goto(link);await client.locator('#store-portal-app').waitFor();assert.equal(await client.locator('#network-store-select option').count(),ours.length+1);assert.ok(await client.locator('#store-request-submit').isDisabled());
 await client.locator('#network-store-select').selectOption(String(ours[0].id));assert.ok(await client.locator('#store-request-submit').isEnabled());assert.ok(await client.locator('#network-store-select').evaluate(e=>e.getBoundingClientRect().height>=44));assert.ok(await client.locator('#store-request-sector').evaluate(e=>e.getBoundingClientRect().height>=44));await client.locator('#store-request-sector').selectOption('Repositor de FLV');await client.locator('#store-request-days').fill('2');await client.locator('#store-request-quantity').fill('3');await client.locator('#store-request-contact').fill('Responsável '+name+' '+width);await client.locator('#store-request-notes').fill('Entrada principal');assert.match(await client.locator('#store-request-preview').innerText(),/6 diária/);const before=(await api('/api/pedidos')).length;
 client.once('dialog',d=>d.accept());await client.locator('#store-request-submit').click();await client.getByText(/Solicitação #.*enviada/).waitFor();assert.equal((await api('/api/pedidos')).length,before);await client.locator('#store-tab-orders').click();await client.locator('#store-sent-requests article').first().waitFor();await client.locator('#network-store-select').selectOption(String(ours[1].id));await client.getByText('Nenhuma solicitação enviada.',{exact:true}).waitFor();
 await admin.locator('#network-links-refresh').click();await admin.locator('#network-requests-list').getByRole('button',{name:'Revisar pedido'}).last().click();await admin.locator('#order-dialog').waitFor();assert.equal(await admin.locator('#order-unit').inputValue(),ours[0].nome);assert.equal(await admin.locator('.order-shift-date').count(),2);await admin.locator('#order-save-button').click();await admin.locator('#order-dialog').waitFor({state:'hidden'});assert.equal((await api('/api/pedidos')).length,before+1);
 await client.locator('#network-store-select').selectOption(String(ours[0].id));await client.locator('#store-portal-orders article').first().waitFor();assert.ok(await client.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await admin.locator('#nav-pedidos-links').click();await card.click();await admin.locator('#network-detail').waitFor();await admin.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth+2);
 await admin.locator('#network-history-status').selectOption('aprovada');await admin.getByRole('button',{name:/Ver pedido #/}).last().waitFor();assert.ok(await admin.locator('#network-requests-list').textContent().then(t=>!t.includes('EXCLUSIVO HIPERMARKET')));await admin.locator('#network-history-search').fill('SEM RESULTADO');await admin.getByText('Nenhuma solicitação encontrada com estes filtros.').waitFor();await admin.locator('#network-history-search').fill('');await admin.locator('#network-history-status').selectOption('');await admin.reload();await admin.locator('#network-detail').waitFor();await admin.getByRole('button',{name:'Copiar link',exact:true}).click();assert.equal(await admin.evaluate(()=>copies.at(-1)),link);
 await admin.getByRole('link',{name:'← Todas as redes'}).click();await admin.locator('.network-category-card').filter({has:admin.getByRole('heading',{name:'Hipermarket',exact:true})}).click();await admin.getByText('Solicitante: EXCLUSIVO HIPERMARKET',{exact:true}).waitFor();assert.ok(!(await admin.locator('#network-requests-list').textContent()).includes('Responsável '+name+' '+width));await admin.getByRole('link',{name:'← Todas as redes'}).click();await card.click();await admin.locator('#network-links-refresh').click();await admin.getByRole('button',{name:'Copiar link',exact:true}).click();assert.equal(await admin.evaluate(()=>copies.at(-1)),link);
 await admin.locator('#nav-redes').click();assert.equal(await admin.getByRole('button',{name:'↗ Link da loja',exact:true}).count(),0);await admin.locator('#nav-pedidos-links').click();await card.click();await client.goto(link);await client.reload();await client.locator('#store-portal-app').waitFor();
 await admin.screenshot({path:'/tmp/direct-network-'+name+'-'+width+'.png',fullPage:true});await client.goto(await admin.evaluate(()=>copies.at(-1)));await client.locator('#store-portal-app').waitFor();await client.locator('#network-store-select').selectOption(String(ours[0].id));await client.screenshot({path:'/tmp/direct-network-portal-'+name+'-'+width+'.png',fullPage:true});await admin.route('**/api/redes-links',async route=>{await new Promise(r=>setTimeout(r,200));await route.continue();});await admin.evaluate(()=>{document.querySelector('#network-links-refresh').click();window.dispatchEvent(new Event('direct:signed-out'));});await admin.waitForTimeout(350);assert.equal(await admin.locator('.network-category-card').count(),0);assert.equal(await admin.locator('#network-requests-list').textContent(),'');assert.deepEqual(errors,[]);console.log(name+' '+width+': link por rede, loja, pedido, revisão, histórico isolado, link fixo e layout OK');await context.close();
 }}finally{await browser.close();}}
}finally{child.kill();await new Promise(r=>child.once('exit',r));await rm(work,{recursive:true,force:true});}
