import assert from'node:assert/strict';import{spawn}from'node:child_process';import{mkdtemp,rm}from'node:fs/promises';import net from'node:net';import os from'node:os';import path from'node:path';import{chromium}from'playwright';
const root=decodeURIComponent(new URL('..',import.meta.url).pathname);const dir=await mkdtemp(path.join(os.tmpdir(),'direct-large-')),s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const port=s.address().port;await new Promise(r=>s.close(r));const base='http://127.0.0.1:'+port,child=spawn(process.env.PYTHON||'python3',['server.py'],{cwd:root,env:{...process.env,DIARISTAS_DB_PATH:dir+'/db.sqlite',DIARISTAS_PORT:String(port)},stdio:'ignore'});
async function api(url,data){const response=await fetch(base+url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();assert.ok(response.ok,result.erro);return result;}
function cpf(i){let v=String(700000000+i);for(const length of[9,10]){let sum=0;for(let j=0;j<length;j++)sum+=Number(v[j])*(length+1-j);const n=(sum*10)%11;v+=n===10?0:n;}return v;}
let browser;try{for(let i=0;i<50;i++){try{const r=await fetch(base);await r.arrayBuffer();if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 for(let i=0;i<31;i++){await api('/api/diaristas',{nome:'Pessoa '+String(i).padStart(3,'0'),cpf:cpf(i)});await api('/api/pedidos',{supermercado:'Super do Povo',unidade:'Meireles',setor:'Repositor de FLV',quantidade_diaristas:2,turnos:['2026-10-06','2026-10-07','2026-10-08'].map(data=>({data,inicio:'07:00',fim:'15:20'})),situacao:'novo'});await api('/api/financeiro',{tipo:'despesa',descricao:'Teste '+i,categoria:'Outros',contraparte:'Teste',valor:'10.00',vencimento:'2026-10-04'});}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:320,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/#diaristas');await page.waitForFunction(()=>records.length===31);assert.equal(await page.locator('#rows tr').count(),25);assert.equal(await page.locator('#total-count').innerText(),'31');await page.locator('#workers-pagination').getByText('Próxima →').click();assert.equal(await page.locator('#rows tr').count(),6);await page.locator('#search').fill('Pessoa 000');await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===1);assert.equal(await page.locator('#rows tr').count(),1);assert.equal(await page.locator('#workers-pagination').isVisible(),false);
 await page.locator('#nav-pedidos').click();await page.waitForFunction(()=>orderRecords.length===31);assert.equal(await page.locator('#orders-rows tr').count(),25);assert.equal(await page.locator('#orders-demand-count').innerText(),'186');await page.locator('#orders-pagination').getByText('Próxima →').click();assert.equal(await page.locator('#orders-rows tr').count(),6);
 await page.locator('#nav-financeiro').click();await page.locator('#finance-month').fill('2026-10');await page.waitForFunction(()=>financeRecords.length===31);assert.equal(await page.locator('#finance-rows tr').count(),25);assert.equal((await page.locator('#forecast-revenue').innerText()).replace(/\D/g,''),'2492400');assert.equal((await page.locator('#forecast-cost').innerText()).replace(/\D/g,''),'1674000');await page.locator('#finance-pagination').getByText('Próxima →').click();assert.equal(await page.locator('#finance-rows tr').count(),6);assert.equal((await page.locator('#finance-payable').innerText()).replace(/\D/g,''),'31000');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));assert.deepEqual(errors,[]);console.log('31 diaristas, 31 pedidos, 186 diárias previstas e 31 lançamentos: paginação, busca, totais financeiros completos e largura 320px OK');
}finally{await browser?.close();child.kill();await rm(dir,{recursive:true,force:true});}
