import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {chromium,webkit} from 'playwright';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const server=http.createServer(async(req,res)=>{try{const file=path.join(root,'static',req.url.split('?')[0]);const data=await readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(data);}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);
const jobs=[{id:1,rede:'Hipermarket',loja:'Vila União',setor:'FLV',endereco:'Endereço sintético de teste',valor_centavos:8500,turnos:[{data:tomorrow,inicio:'07:00',fim:'15:20',vagas:1}]}];
try{for(const [engine,name] of [[chromium,'Chromium'],[webkit,'WebKit']]){const browser=await engine.launch();try{for(const width of [1280,390,320]){
 const context=await browser.newContext({viewport:{width,height:850}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let logged=false,registered=false,accepted=false,signup=0,accepts=0;
 const user={id:'11111111-1111-4111-8111-111111111111',aud:'authenticated',role:'authenticated',email:'teste@example.invalid',email_confirmed_at:new Date().toISOString(),created_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{direct_cadastro:{nome:'Pessoa sintética',cpf:'52998224725',setores:[]}}};
 const token=[Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),Buffer.from(JSON.stringify({sub:user.id,role:'authenticated',exp:Math.floor(Date.now()/1000)+3600,iat:Math.floor(Date.now()/1000)})).toString('base64url'),'synthetic'].join('.');
 await page.route('https://jxthqgtzybcyediyciqc.supabase.co/**',async route=>{const p=new URL(route.request().url()).pathname;let data;if(p.endsWith('/direct_portal_orders'))data=accepted?[]:jobs;else if(p.endsWith('/direct_portal_me'))data=registered?{status:'ativo',nome:'Pessoa sintética',escalas:accepted?[{id:1,pedido_id:1,rede:'Hipermarket',loja:'Vila União',setor:'FLV',data:tomorrow,inicio:'07:00',fim:'15:20',status:'escalada'}]:[]}:{status:'sem_cadastro'};else if(p.endsWith('/direct_portal_register')){registered=true;data={status:'ativo',nome:'Pessoa sintética'};}else if(p.endsWith('/direct_portal_accept')){assert.ok(logged&&registered);assert.deepEqual(route.request().postDataJSON().p_datas,[tomorrow]);accepted=true;accepts++;data={dias:1,mensagem:'Escala confirmada.'};}else if(p==='/auth/v1/signup'){signup++;assert.equal(route.request().postDataJSON().data.direct_cadastro.cpf,'52998224725');data={...user,identities:[]};}else if(p==='/auth/v1/token'){logged=true;data={access_token:token,refresh_token:'synthetic-refresh',token_type:'bearer',expires_in:3600,user};}else if(p==='/auth/v1/logout'){logged=false;data={};}else if(p==='/auth/v1/user')data=user;else throw Error('Endpoint não previsto: '+p);await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});});
 await page.goto(url+'/cadastro.html');await page.locator('[name=nome]').fill('Pessoa sintética');await page.locator('[name=cpf]').fill('11111111111');await page.locator('[name=email]').fill('teste@example.invalid');await page.locator('[name=senha]').fill('SyntheticTest123!');await page.locator('[name=confirmar]').fill('SyntheticTest123!');await page.locator('[name=consentimento]').check();await page.getByRole('button',{name:'Salvar meu cadastro'}).click();await page.getByText('Confira o CPF:').waitFor();assert.equal(signup,0);
 await page.locator('[name=cpf]').fill('52998224725');await page.locator('[name=confirmar]').fill('OutraSenha123!');await page.getByRole('button',{name:'Salvar meu cadastro'}).click();await page.getByText('As senhas precisam ser iguais.').waitFor();assert.equal(signup,0);
 await page.locator('[name=confirmar]').fill('SyntheticTest123!');await page.getByRole('button',{name:'Salvar meu cadastro'}).click();await page.getByText(/Enviamos a confirmação/).waitFor();assert.equal(signup,1);assert.equal(registered,false,'Sem confirmação de e-mail não grava');
 await page.goto(url+'/vagas.html');await page.getByRole('button',{name:'Quero estes dias'}).waitFor();await page.getByRole('button',{name:'Quero estes dias'}).click();await page.locator('#access-dialog').waitFor({state:'visible'});assert.equal(accepts,0,'Sem acesso não confirma pedido');
 await page.locator('#access-email').fill('teste@example.invalid');await page.locator('#access-password').fill('SyntheticTest123!');await page.locator('#access-form button[type=submit]').click();await page.locator('#access-dialog').waitFor({state:'hidden'});await page.getByText(/Seu cadastro está ativo/).waitFor();assert.ok(registered);
 await page.locator('#search').fill('açougue');await page.getByText('Nenhuma vaga corresponde à busca.').waitFor();await page.locator('#search').fill('Vila Uniao');await page.getByRole('button',{name:'Quero estes dias'}).waitFor();
 await page.locator('.shift-choice input').uncheck();await page.getByRole('button',{name:'Quero estes dias'}).click();await page.getByText('Selecione pelo menos um dia.').waitFor();assert.equal(accepts,0);
 await page.locator('.shift-choice input').check();await page.getByRole('button',{name:'Quero estes dias'}).click();await page.locator('#confirm-dialog').waitFor({state:'visible'});assert.equal(accepts,0,'Revisão não altera escala');await page.getByRole('button',{name:'Voltar',exact:true}).click();assert.equal(accepts,0);await page.getByRole('button',{name:'Quero estes dias'}).click();await page.getByRole('button',{name:'Confirmo que vou',exact:true}).click();await page.getByText('Confirmou que vai',{exact:true}).waitFor();assert.equal(accepts,1);await page.getByText('Nenhuma diária disponível no momento. Volte mais tarde.').waitFor();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));assert.ok(await page.locator('#search').evaluate(e=>parseFloat(getComputedStyle(e).fontSize))>=16);assert.deepEqual(errors,[]);
 await page.getByRole('button',{name:'Sair',exact:true}).click();await page.locator('#my-shifts-section').waitFor({state:'hidden'});await page.getByRole('button',{name:'Entrar no meu cadastro',exact:true}).waitFor();
 console.log(`${name} ${width}: cadastro, validação CPF/senha, e-mail, sessão, busca, revisão, escala, saída, layout e fonte OK`);await context.close();
 }}finally{await browser.close();}}}finally{server.close();}
