-- Somente dados sintéticos; rollback inclusive dos convites e contadores de consulta.
begin;
do $$
declare uid uuid:=gen_random_uuid();invite jsonb;unused jsonb;r jsonb;wid bigint;other_worker bigint;oid bigint;blocked_order bigint;overlap_order bigint;
 d date:=(now() at time zone 'America/Fortaleza')::date+2;token text:=repeat('d',64);turnos jsonb;payload jsonb;
begin
 if exists(select 1 from public.diaristas where cpf in ('52998224725','11144477735')) then raise exception 'Fixture CPF já existe; use outra fixture sem alterar pessoas reais.';end if;
 insert into auth.users(id,email,email_confirmed_at) values(uid,'compact-portal-test@example.invalid',now());
 insert into public.direct_staff(email,role,active) values('compact-portal-test@example.invalid','operacao',true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',uid,'email','compact-portal-test@example.invalid','role','authenticated')::text,true);
 invite:=public.direct_portal_create_invite(null,30);unused:=public.direct_portal_create_invite(null,30);
 perform set_config('request.jwt.claims','{}',true);
 insert into direct_private.portal_vagas_link(id,token) values(true,token) on conflict(id) do update set token=excluded.token;
 payload:=jsonb_build_object('nome','Pessoa Sintética Verificação','cpf','52998224725','telefone','85999991234','data_nascimento','1990-04-10','cep','61600000','logradouro','Rua sintética','numero','12','bairro','Centro','cidade','Caucaia','uf','CE','setores',jsonb_build_array('FLV'),'disponibilidade',jsonb_build_array(jsonb_build_object('dia','segunda','inicio','00:00','fim','23:59')),'trabalhando',false,'pode_se_deslocar',true,'transporte','Ônibus','consentimento',true);
 perform public.direct_portal_submit(payload,invite->>'cadastro_token');
 select id into wid from public.diaristas where cpf='52998224725';
 insert into public.diaristas(nome,cpf,setores,disponibilidade) values('Outra Pessoa Sintética','11144477735','["FLV"]','[]') returning id into other_worker;
 select jsonb_agg(jsonb_build_object('data',d+n,'inicio','07:00','fim','15:20') order by n) into turnos from generate_series(0,6) n;
 insert into public.pedidos(supermercado,unidade,setor,quantidade_diaristas,turnos) values('Portal identidade teste','Unidade sintética','FLV',1,turnos) returning id into oid;
 r:=public.direct_portal_check_worker(token,'painel','  pessoa   sintetica verificacao  ','529.982.247-25',oid);
 if not (r->>'autorizado')::boolean or r?'cpf' or r?'diarista_id' or r?'nome' then raise exception 'Identificação normalizada falhou ou expôs ficha';end if;
 if (public.direct_portal_check_worker(token,'painel','Nome Errado','52998224725',oid)->>'autorizado')::boolean then raise exception 'Nome incorreto autorizado';end if;
 if (public.direct_portal_check_worker(token,'painel','Pessoa Inexistente','12345678909',oid)->>'autorizado')::boolean then raise exception 'CPF desconhecido autorizado';end if;
 if (public.direct_portal_check_worker(repeat('0',64),'painel','Pessoa Sintética Verificação','52998224725',oid)->>'autorizado')::boolean then raise exception 'Token inválido autorizado';end if;
 if (public.direct_portal_check_worker(unused->>'vagas_token','vagas','Pessoa Sintética Verificação','52998224725',oid)->>'autorizado')::boolean then raise exception 'Link individual alheio autorizado';end if;
 if not (public.direct_portal_check_worker(invite->>'vagas_token','vagas','Pessoa Sintética Verificação','52998224725',oid)->>'autorizado')::boolean then raise exception 'Link individual correto não autorizado';end if;
 update public.diaristas set bloqueada=true where id=wid;
 if (public.direct_portal_check_worker(token,'painel','Pessoa Sintética Verificação','52998224725',oid)->>'autorizado')::boolean then raise exception 'Pessoa bloqueada autorizada';end if;
 begin perform public.direct_portal_claim_order(token,'painel','Pessoa Sintética Verificação','52998224725',oid);raise exception 'FALHOU: bloqueado pegou escala';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 update public.diaristas set bloqueada=false,trabalhando=true,rede_trabalho='Portal identidade teste',local_trabalho='Unidade sintética' where id=wid;
 if (public.direct_portal_check_worker(token,'painel','Pessoa Sintética Verificação','52998224725',oid)->>'autorizado')::boolean then raise exception 'Mesma empresa autorizada';end if;
 begin perform public.direct_portal_claim_order(token,'painel','Pessoa Sintética Verificação','52998224725',oid);raise exception 'FALHOU: mesma empresa pegou escala';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 update public.diaristas set trabalhando=false,rede_trabalho='',local_trabalho='' where id=wid;
 r:=public.direct_portal_claim_order(token,'painel','Pessoa Sintética Verificação','52998224725',oid);
 if not (r->>'confirmado')::boolean or (r->>'dias')::int<>7 or (select count(*) from public.pedido_escalas where pedido_id=oid and diarista_id=wid and confirmacao='confirmou' and status='escalada')<>7 then raise exception 'Não confirmou as sete diárias';end if;
 if (public.direct_portal_claim_order(token,'painel','Pessoa Sintética Verificação','52998224725',oid)->>'dias')::int<>0 then raise exception 'Clique repetido duplicou escala';end if;
 if public.direct_portal_board_orders(token) @> jsonb_build_array(jsonb_build_object('id',oid)) then raise exception 'Pedido preenchido continuou disponível';end if;
 if not exists(select 1 from public.pedidos where id=oid and situacao='confirmado') then raise exception 'Pedido não confirmou no sistema';end if;
 insert into public.pedidos(supermercado,unidade,setor,quantidade_diaristas,turnos) values('Portal identidade teste','Unidade sintética','FLV',1,turnos) returning id into blocked_order;
 insert into public.pedido_escalas(pedido_id,diarista_id,data,disponibilidade_pedido_confirmada) values(blocked_order,other_worker,d+3,true);
 begin perform public.direct_portal_claim_order(token,'painel','Pessoa Sintética Verificação','52998224725',blocked_order);raise exception 'FALHOU: aceitou escala incompleta';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 if exists(select 1 from public.pedido_escalas where pedido_id=blocked_order and diarista_id=wid) then raise exception 'Gravou parcialmente antes da vaga indisponível';end if;
 insert into public.pedidos(supermercado,unidade,setor,quantidade_diaristas,turnos) values('Portal identidade teste','Outra unidade','FLV',1,turnos) returning id into overlap_order;
 if (public.direct_portal_claim_order(invite->>'vagas_token','vagas','Pessoa Sintética Verificação','52998224725',overlap_order)->>'dias')::int<>7 then raise exception 'Bloqueou sobreposição autorizada entre pedidos';end if;
 if has_table_privilege('anon','direct_private.portal_identity_limits','select') or has_function_privilege('anon','direct_private.portal_identity(text,text,text,text)','execute') or not has_function_privilege('anon','public.direct_portal_check_worker(text,text,text,text,bigint)','execute') then raise exception 'Privilégios incorretos';end if;
 -- Conferências de CPF inexistente consomem a cota, sem expor cadastros ou gravar escala.
 update direct_private.portal_identity_limits set tentativas=60 where chave=extensions.digest(token||':ip:sem-ip','sha256');
 r:=public.direct_portal_check_worker(token,'painel','Pessoa Sintética Verificação','52998224725',oid);
 if (r->>'autorizado')::boolean or r->>'mensagem' not like 'Muitas conferências%' then raise exception 'Limite de consultas não aplicado';end if;
 raise notice 'PORTAL IDENTIDADE OK: 7 dias, normalização, nome/CPF, convite, bloqueio, empresa, capacidade, atomicidade, idempotência, sobreposição e sigilo';
end $$;
rollback;
