import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createSignupHandler} from '../supabase/functions/portal-cadastro/handler.mjs';
const good={convite:'a'.repeat(64),email:'teste@example.invalid',senha:'SyntheticTest123!',dados:{nome:'Pessoa sintética',cpf:'52998224725'}};
const origin='https://sistemadirectpromocoes-zeta.vercel.app';
function fixture(fail){const calls=[];const client={rpc:async(name,args)=>{calls.push({name,args});if(fail===name)return {error:{message:'Convite inválido.'}};return {data:'11111111-1111-4111-8111-111111111111'};},auth:{admin:{createUser:async args=>{calls.push({name:'createUser',args});return fail==='createUser'?{error:{message:'already registered'}}:{data:{user:{id:'synthetic-id'}}};},deleteUser:async id=>{calls.push({name:'deleteUser',id});return{};}}}};return {calls,handler:createSignupHandler({SUPABASE_URL:'https://example.invalid',SUPABASE_SERVICE_ROLE_KEY:'server-only-synthetic'},()=>client)};}
function request(body=good,source=origin){return new Request('https://example.invalid',{method:'POST',headers:{origin:source,'Content-Type':'application/json'},body:JSON.stringify(body)});}
test('Sem convite/origem/senha não usa a API administrativa',async()=>{for(const [body,source] of [[{...good,convite:''},origin],[good,'https://untrusted.invalid'],[{...good,senha:'short'},origin]]){const {handler,calls}=fixture();assert.ok((await handler(request(body,source))).status>=400);assert.equal(calls.length,0);}});
test('Convite rejeitado impede criar conta',async()=>{const {handler,calls}=fixture('direct_portal_signup_prepare');assert.equal((await handler(request())).status,400);assert.equal(calls.length,1);});
test('Conta criada por convite sem e-mail, senha somente no Auth',async()=>{const {handler,calls}=fixture();const r=await handler(request());assert.equal(r.status,200);assert.deepEqual(await r.json(),{created:true});assert.deepEqual(calls.map(c=>c.name),['direct_portal_signup_prepare','createUser','direct_portal_signup_finish']);assert.equal(calls[1].args.email_confirm,true);assert.ok(calls[1].args.app_metadata.direct_invite_signup);assert.ok(!JSON.stringify(calls.filter(c=>c.name!=='createUser')).includes(good.senha));});
test('Erro do Auth libera reserva para tentar novamente, sem sobrescrever conta existente',async()=>{const {handler,calls}=fixture('createUser');assert.equal((await handler(request())).status,400);assert.equal(calls.at(-1).name,'direct_portal_signup_release');assert.ok(!calls.some(c=>c.name==='deleteUser'));});
test('Falha em vincular não deixa nova conta órfã',async()=>{const {handler,calls}=fixture('direct_portal_signup_finish');assert.equal((await handler(request())).status,400);assert.deepEqual(calls.slice(-2).map(c=>c.name),['deleteUser','direct_portal_signup_release']);});
