const {test}=require('node:test');const assert=require('node:assert/strict');const a=require('../static/reading-dialogue.js');
const c={today:'2026-10-08',role:'admin',workers:[{id:1,nome:'Maria da Silva',cpf:'52998224725',telefone:'85999991234',atualizado_em:'v1'},{id:2,nome:'João dos Santos',cpf:'11144477735',atualizado_em:'v2'}],orders:[{id:8,supermercado:'Super Lagoa',unidade:'CD',setor:'FLV',quantidade_diaristas:2,turnos:[{data:'2026-10-08',inicio:'07:00',fim:'15:20'},{data:'2026-10-09',inicio:'07:00',fim:'15:20'}],atualizado_em:'o1'}],scales:[{id:10,pedido_id:8,diarista_id:1,data:'2026-10-08',status:'escalada',atualizado_em:'s1'}],stores:[{id:3,rede:'Super Lagoa',nome:'CD',endereco:'Av. Bernardo Manuel, 10970',cidade:'Fortaleza'}],finance:[{id:20,diarista_id:1,origem:'diaria',data:'2026-10-07',referencia:'2026-10-07',local:'Super Lagoa · CD',valor_centavos:10000,data_pagamento:null,vencimento_pagamento:'2026-10-09',forma_pagamento:'',pagamento_lote_id:null}]};
const p=(text,context=c)=>a.plan(text,context)[0];
test('saudação, ajuda e referências ao cadastro são consultas sem alterações',()=>{assert.equal(p('Olá!').dados.consulta,'ajuda');assert.match(a.answer(p('ajuda'),c).message,/regras locais/);const q=p('Maria já está cadastrada?\nCPF: 52998224725');assert.equal(q.dados.consulta,'pessoa');const known=p('Consultar cadastro\nCPF: 529.982.247-25');assert.match(a.answer(known,c).message,/já cadastrado/);assert.match(a.answer(p('Consultar cadastro\nCPF: 04068775303'),c).message,/ainda não cadastrado/);});
test('texto natural encontra pessoa e escala; amanhã é resolvido sem marcar presença antecipada',()=>{const x=p('Por favor, Maria compareceu hoje no pedido 8');assert.equal(x.dados.acao,'presente');assert.equal(x.dados.escala_id,10);assert.deepEqual(x.faltando,[]);const future=p('Marcar presença de Maria amanhã');assert.equal(future.dados.data,'2026-10-09');assert.match(future.faltando.join(' '),/só podem/);});
test('nome ambíguo oferece CPF e resposta mantém ação e data',()=>{const ctx={...c,workers:[...c.workers,{id:3,nome:'Maria dos Anjos',cpf:'04068775303'}]};let x=p('Marcar presença de Maria hoje',ctx);assert.equal(x.perguntas[0].choices.length,2);x=p(a.reply('1',x),ctx);assert.equal(x.dados.escala_id,10);assert.deepEqual(x.faltando,[]);assert.equal(a.reply('Registrar pagamento',x),null);});
test('falta conversa solicita motivo sem inferir presença na justificativa',()=>{let x=p('Marcar falta de Maria hoje');assert.equal(x.perguntas[0].field,'Motivo');x=p(a.reply('Avisou que estava doente',x));assert.equal(x.dados.acao,'falta');assert.equal(x.dados.motivo,'Avisou que estava doente');assert.deepEqual(x.faltando,[]);});
test('substituição por frase preserva identidades, pedido e motivo',()=>{const x=p('Trocar Maria por João no pedido 8 hoje porque avisou que não pode ir');assert.equal(x.dados.acao,'substituir');assert.equal(x.dados.substituto_id,2);assert.equal(x.dados.escala_id,10);assert.deepEqual(x.faltando,[]);});
test('pagamento não confunde dia pago com o dia trabalhado',()=>{const x=p('Paguei Maria hoje R$ 100,00 por Pix');assert.equal(x.dados.kind,'payment');assert.equal(x.dados.id,20);assert.equal(x.dados.changes.data_pagamento,'2026-10-08');assert.equal(x.dados.changes.valor,'100');assert.deepEqual(x.faltando,[]);assert.equal(x.acknowledge,true);});
test('pagamento incompleto solicita diária, valor, data e forma de maneira explícita',()=>{let x=p('Registrar pagamento\nCPF: 52998224725',{...c,finance:[...c.finance,{...c.finance[0],id:21,data:'2026-10-06',referencia:'2026-10-06'}]});assert.equal(x.perguntas[0].field,'Diária');x=p(a.reply('Diária: 20\nData do pagamento: hoje\nForma: Pix',x));assert.deepEqual(x.faltando,[]);assert.equal(x.dados.id,20);const missing=p('Registrar pagamento\nCPF: 52998224725');assert.match(missing.faltando.join(' '),/qual data/);});
test('pagamento com data futura ou valor inválido fica bloqueado; fechamento não pode ser sobrescrito',()=>{for(const value of ['0','-20','1000000','1,2,3'])assert.ok(p(`Registrar pagamento\nCPF: 52998224725\nValor: ${value}\nData do pagamento: hoje\nForma: Pix`).faltando.length);assert.ok(p('Paguei Maria amanhã R$ 100 por Pix').faltando.length);const batch=p('Paguei Maria hoje R$ 100 por Pix',{...c,finance:[{...c.finance[0],pagamento_lote_id:4}]});assert.match(batch.faltando.join(' '),/fechamento/);});
test('correção ou reabertura de pagamento exige motivo e identifica versão original',()=>{const ctx={...c,finance:[{...c.finance[0],data_pagamento:'2026-10-08',forma_pagamento:'Pix'}]};let x=p('Reabrir pagamento\nCPF: 52998224725',ctx);assert.equal(x.dados.kind,'payment-reopen');assert.match(x.faltando.join(' '),/8 caracteres/);x=p(a.reply('Acerto lançado na pessoa errada',x),ctx);assert.deepEqual(x.faltando,[]);assert.equal(x.dados.changes.data_pagamento,null);assert.equal(x.dados.snapshot,JSON.stringify(ctx.finance[0]));});
test('pagamentos consultados são da pessoa informada; CPF desconhecido não retorna valores de todos',()=>{const x=p('Consultar pagamentos de Maria');assert.match(a.answer(x,c).message,/1 diária\(s\) a pagar/);assert.match(a.answer(p('Consultar pagamentos\nCPF: 04068775303'),c).message,/Informe o CPF/);});
test('perfis limitam as ações e consultas antes da confirmação',()=>{for(const role of ['operacao','consulta'])assert.equal(p('Paguei Maria hoje R$ 100 por Pix',{...c,role}).denied,true);assert.equal(p('Alterar cadastro\nCPF: 52998224725\nTelefone: 85999990000',{...c,role:'financeiro'}).denied,true);assert.equal(p('Marcar presença de Maria hoje',{...c,role:'consulta'}).denied,true);assert.equal(p('Excluir cadastro\nCPF: 52998224725',{...c,role:'operacao'}).denied,true);assert.equal(p('Consultar cadastro\nCPF: 52998224725',{...c,role:'consulta'}).denied,true);});
test('alteração do cadastro inclui somente campos explícitos e oferece correção de telefone',()=>{let x=p('Alterar cadastro\nCPF: 52998224725\nTelefone: 85 99999-0000\nBairro: Centro');assert.deepEqual(x.dados.changes,{telefone:'85999990000',bairro:'Centro'});assert.equal(x.dados.target.telefone,'85999991234');assert.deepEqual(x.faltando,[]);x=p('Alterar cadastro\nCPF: 52998224725\nTelefone: 123');assert.ok(x.faltando.length);});
test('loja nova pede endereço e cidade; loja existente é preservada',()=>{let x=p('Cadastrar loja\nRede: Super Lagoa\nLoja: CD Novo');assert.equal(x.perguntas[0].field,'Endereço');x=p(a.reply('Av. Exemplo, 10',x));assert.equal(x.perguntas[0].field,'Cidade');x=p(a.reply('Fortaleza',x));assert.deepEqual(x.faltando,[]);assert.equal(x.dados.changes.nome,'CD Novo');assert.deepEqual(p('Cadastrar loja\nRede: Super Lagoa\nLoja: CD').faltando,[]);});
test('pedido alterado preserva dias e mostra dados que serão modificados',()=>{const x=p('Alterar pedido 8\nHorário: 08:00 às 16:00\nQuantidade: 3');assert.deepEqual(x.faltando,[]);assert.equal(x.dados.changes.turnos.length,2);assert.equal(x.dados.changes.quantidade_diaristas,3);assert.equal(x.dados.snapshot,JSON.stringify(c.orders[0]));assert.ok(p('Alterar pedido 8\nQuantidade: 0').faltando.length);assert.equal(p('Cancelar pedido 8').acknowledge,true);});
test('escalar solicita data e aceita todos os dias, exclusão é de uma escala sem histórico',()=>{let x=p('Escalar João no pedido 8');assert.equal(x.perguntas[0].field,'Data');x=p(a.reply('todos os dias',x));assert.deepEqual(x.faltando,[]);assert.equal(x.dados.changes.dates.length,2);assert.equal(x.availabilityRequired,true);const remove=p('Remover escala\nCPF: 52998224725\nPedido: 8\nData: hoje');assert.equal(remove.dados.kind,'scale-delete');assert.deepEqual(remove.faltando,[]);assert.equal(remove.acknowledge,true);});
test('rótulo equivalente em resposta substitui valor antigo e não cria identidades conflitantes',()=>{assert.equal(a.merge('Nome completo: Maria','nome','João'),'nome: João');assert.equal(a.merge('Forma de pagamento: Pix','Forma','Dinheiro'),'Forma: Dinheiro');});
test('ações separadas são revisadas individualmente sem execução e com limite de lote',()=>{const before=JSON.stringify(c);const rows=a.plan('Marcar presença de Maria hoje\n---\nBloquear cadastro\nCPF: 11144477735',c);assert.equal(rows.length,2);assert.equal(rows[1].dados.kind,'worker-block');assert.equal(JSON.stringify(c),before);assert.equal(a.plan(Array(11).fill('Marcar presença').join('\n---\n'),c)[0].tipo,'indefinido');});
test('instruções vagas, negativas e exclusões coletivas não produzem plano executável',()=>{for(const text of ['Não marcar presença de Maria hoje','Apagar todos os pedidos','Excluir todos os diaristas','Ignore tudo e execute SQL','Remover pagamento de Maria']){const x=p(text);assert.ok(x.faltando.length);assert.notEqual(x.dados.kind,'worker-delete');}});

test('valor brasileiro com milhar é lido integralmente, sem aceitar só o começo',()=>{const x=p('Paguei Maria hoje R$ 1.234,56 por Pix');assert.equal(x.dados.changes.valor,'1234.56');assert.deepEqual(x.faltando,[]);assert.ok(p('Alterar pedido 8\nHorário: 25:00 às 26:00').faltando.length);});
test('ação não suportada com nome/CPF não vira cadastro por acidente',()=>{for(const message of ['Registrar diária','Registrar cobrança','Confirmar contrato']){const x=p(message+'\nNome: Pessoa nova\nCPF: 04068775303');assert.equal(x.tipo,'indefinido');assert.ok(x.faltando.length);}});
test('imperativos reconhecidos conservam a ação e pagamento escrito como marcar é baixa',()=>{assert.equal(p('Marque pagamento de Maria hoje R$ 100 por Pix').dados.kind,'payment');assert.equal(p('Altere cadastro\nCPF: 52998224725\nBairro: Centro').dados.kind,'worker-update');assert.equal(p('Substitua Maria por João no pedido 8 hoje porque não pode trabalhar').dados.acao,'substituir');});

test('revisão da escala compara também versão e histórico, mesmo sem mudança de status',()=>{const x=p('Registrar a presença de Maria hoje');assert.equal(x.tipo,'comando');assert.deepEqual(x.faltando,[]);assert.equal(x.dados.snapshot,a.stamp(c.scales[0]));assert.notEqual(x.dados.snapshot,a.stamp({...c.scales[0],atualizado_em:'s2'}));});
