const {test}=require('node:test');const assert=require('node:assert/strict');const {compose,payment}=require('../static/messages-model.js');
const order={id:1,supermercado:'Super do Povo',unidade:'Meireles',setor:'Repositor de FLV',quantidade_diaristas:1,situacao:'confirmado',turnos:[{data:'2026-10-03',inicio:'07:00',fim:'15:20'},{data:'2026-10-04',inicio:'07:00',fim:'15:20'}]};
const stores=[{rede:'Super do Povo',nome:'Meireles',endereco:'Rua Júlio Ibiapina, 291',bairro:'Meireles',cidade:'Fortaleza',uf:'CE'}];
const person={id:4,pedido_id:1,diarista_id:2,diarista_nome:'Pessoa Teste',data:'2026-10-03',status:'escalada',confirmacao:'confirmou',cpf:'12345678900'};
test('endereço copiável usa negrito do WhatsApp e somente a loja correta',()=>{assert.equal(compose('address',{order,stores}),'*Rede:* Super do Povo\n*Loja:* Meireles\n*Endereço:* Rua Júlio Ibiapina, 291, Meireles, Fortaleza/CE');assert.match(compose('address',{order,stores:[{...stores[0],rede:'Hipermarket'}]}),/Confirmar endereço/);});
test('escala mostra equipe por dia, substituição e confirmação distintas da presença',()=>{const text=compose('team',{order,stores,scales:[person,{...person,id:5,diarista_id:3,status:'desistiu',diarista_nome:'Desistente'},{...person,id:6,diarista_id:7,diarista_nome:'Substituto',data:'2026-10-04',status:'presente'}]});assert.match(text,/03\/10\/2026.*07:00 às 15:20/);assert.match(text,/Pessoa Teste \(confirmou que vai\)/);assert.match(text,/Substituto \(presença registrada\)/);assert.doesNotMatch(text,/Desistente|12345678900|CPF/);});
test('divulgação inclui só dias com vaga e não ignora escala ao escolher uma pessoa',()=>{const text=compose('vacancy',{order,stores,scales:[person],personId:99,today:'2026-10-03'});assert.doesNotMatch(text,/03\/10\/2026/);assert.match(text,/04\/10\/2026/);assert.match(text,/todos os dias/);assert.doesNotMatch(text,/Pessoa Teste/);assert.throws(()=>compose('vacancy',{order:{...order,situacao:'cancelado'},stores}),/não está disponível/);assert.throws(()=>compose('vacancy',{order,scales:[person,{...person,data:'2026-10-04'}],today:'2026-10-03'}),/não tem vagas/);assert.doesNotMatch(compose('vacancy',{order,scales:[{...person,confirmacao:'recusou'}],today:'2026-10-03'}),/03\/10\/2026/);assert.throws(()=>compose('vacancy',{order,scales:[],today:'2026-10-04',time:'08:00'}),/não tem vagas/);});
test('lembrete individual limita datas à pessoa selecionada e evita mensagens vencidas',()=>{const text=compose('reminder',{order,stores,scales:[person],personId:2,today:'2026-10-03'});assert.match(text,/Pessoa Teste/);assert.doesNotMatch(text,/04\/10\/2026/);assert.throws(()=>compose('reminder',{order,scales:[person],personId:2,today:'2026-10-04'}),/Não há escala ativa/);});
test('pagamento separa realizado e previsto, não mostra receita e não soma valor desconhecido',()=>{const rows=[{diarista_id:2,contraparte:'Pessoa Teste',data:'2026-10-03',local:'Super do Povo · Meireles',setor:'FLV',valor_centavos:9000,valor_recebido_centavos:13400,vencimento:'2026-10-15'},{diarista_id:2,contraparte:'Pessoa Teste',data:'2026-10-04',local:'Super do Povo · Meireles',setor:'FLV',valor_centavos:9000,data_pagamento:'2026-10-05'}];const text=payment(rows);assert.match(text,/Total a pagar:\* R\$\s90,00/);assert.match(text,/Total pago:\* R\$\s90,00/);assert.match(text,/Pagamento previsto: 15\/10\/2026/);assert.doesNotMatch(text,/134,00/);assert.match(payment([{...rows[0],valor_centavos:null}]),/Valor a confirmar/);assert.throws(()=>payment([...rows,{...rows[0],diarista_id:3}]),/mesma pessoa/);});
