const {test}=require('node:test');const assert=require('node:assert/strict');const a=require('../static/reading-assistant.js');
const context={today:'2026-10-03',stores:[{rede:'Hipermarket',nome:'Vila União'}],workers:[{id:1,nome:'Maria da Silva',cpf:'52998224725'},{id:2,nome:'Fernando Ferreira Grangeiro',cpf:'04068775303'}],orders:[{id:8,supermercado:'Hipermarket',unidade:'Vila União',setor:'Repositor de mercearia',turnos:[{data:'2026-10-03',inicio:'06:00',fim:'14:20'}]}],scales:[{id:10,pedido_id:8,diarista_id:1,data:'2026-10-03',status:'escalada',confirmacao:'aguardando'}]};
test('CPF identifica cadastro existente mesmo com nome abreviado e remove aviso de cadastro parcial',()=>{
 const before=JSON.stringify(context.workers),[p]=a.plan('Nome: Maria da Silva Oliveira\nCPF: 529.982.247-25',context);
 assert.deepEqual(p.cadastro,{status:'existente',nome:'Maria da Silva',id:1});
 assert.equal(p.dados.nome,'Maria da Silva Oliveira');assert.deepEqual(p.completar,[]);
 assert.match(p.avisos.join(' '),/cadastro existente será preservado/);assert.doesNotMatch(p.avisos.join(' '),/Cadastro parcial/);
 assert.ok(a.describe(p).some(([label,value])=>label==='Cadastro'&&value==='Diarista já cadastrado'));
 assert.equal(JSON.stringify(context.workers),before);
});
test('nome igual com CPF novo não reutiliza cadastro e CPF inválido não afirma ausência',()=>{
 const [p]=a.plan('Nome: Maria da Silva\nCPF: 11144477735',context);assert.equal(p.cadastro.status,'novo');
 assert.ok(a.describe(p).some(([,value])=>value==='Diarista ainda não cadastrado'));
 for(const cpf of ['11111111111','']){const [invalid]=a.plan(`Nome: Maria da Silva\nCPF: ${cpf}`,context);assert.equal(invalid.cadastro.status,'verificar');assert.ok(invalid.faltando.length);}
});
test('consulta compara CPF normalizado e revalida cadastro recebido após a leitura',()=>{
 const [p]=a.plan('Nome: Maria da Silva\nCPF: 52998224725',{...context,workers:[]});assert.equal(p.cadastro.status,'novo');
 a.identifyRegistration(p,[{...context.workers[0],cpf:'529.982.247-25'}]);assert.equal(p.cadastro.status,'existente');
 a.identifyRegistration(p,context.workers);assert.deepEqual(p.avisos,[]);
});
test('WhatsApp mistura cadastro e pedido, inclusive nome antes do pedido',()=>{
 const message='Rede: Hipermarket\nRegião: LOJA VILA UNIÃO\nFunção: Repositor de mercearia\nHorário: 6:00 às 14:20\nData: 03/10\nQuantidade de dias: 2\n\n*Fernando Ferreira Grangeiro* CPF: 04068775303';const [p]=a.plan(message,context);assert.equal(p.tipo,'pedido');assert.equal(p.dados.diarista_escalado.cpf,'04068775303');assert.equal(p.dados.turnos.length,2);assert.deepEqual(p.faltando,[]);assert.equal(p.cadastro.status,'existente');assert.equal(a.plan(message,{...context,workers:[]})[0].cadastro.status,'novo');
 const [before]=a.plan('Nome: Maria da Silva\nCPF: 52998224725\n'+message.slice(0,message.indexOf('\n\n')),context);assert.equal(before.tipo,'pedido');assert.equal(before.dados.diarista_escalado.nome,'Maria da Silva');
});
test('cadastro por frase e separadores WhatsApp',()=>{const [p]=a.plan('Cadastre Maria da Silva CPF: 52998224725',context);assert.equal(p.dados.nome,'Maria da Silva');assert.deepEqual(p.faltando,[]);const [eq]=a.plan('Nome = Maria da Silva; CPF = 52998224725',context);assert.deepEqual(eq.faltando,[]);});
test('presença identifica escala e não se confunde com confirmou que vai',()=>{const [p]=a.plan('Marcar presença de Maria hoje',context);assert.equal(p.dados.acao,'presente');assert.equal(p.dados.escala_id,10);assert.deepEqual(p.faltando,[]);const [c]=a.plan('Maria confirmou que vai\nNome: Maria da Silva\nData: hoje',context);assert.notEqual(c.tipo,'pedido');});
test('homônimos, múltiplas escalas, data futura e CPF inválido não são resolvidos por chute',()=>{let p=a.plan('Marcar presença de Maria hoje',{...context,workers:[...context.workers,{id:3,nome:'Maria dos Santos'}]})[0];assert.ok(p.faltando.length);p=a.plan('Marcar presença de Maria hoje',{...context,scales:[...context.scales,{...context.scales[0],id:11,pedido_id:9}],orders:[...context.orders,{...context.orders[0],id:9}]})[0];assert.match(p.faltando.join(' '),/mais de uma escala/);p=a.plan('Marcar presença\nNome: Maria da Silva\nData: 04/10/2026',context)[0];assert.match(p.faltando.join(' '),/só podem/);assert.ok(a.plan('Nome: Maria da Silva\nCPF: 11111111111',context)[0].faltando.length);});
test('falta e desistência pedem motivo, substituição pede pessoa cadastrada',()=>{for(const action of ['Marcar falta','Registrar desistência'])assert.match(a.plan(`${action}\nCPF: 52998224725\nData: hoje`,context)[0].faltando.join(' '),/Motivo/);const [p]=a.plan('Substituir\nNome: Maria da Silva\nData: hoje\nSubstituto: Fernando Ferreira Grangeiro\nMotivo: Não pode comparecer',context);assert.deepEqual(p.faltando,[]);assert.equal(p.dados.substituto_id,2);});
test('consulta é distinta de cadastro e comando desconhecido pede orientação',()=>{assert.equal(a.plan('Consultar financeiro de hoje',context)[0].tipo,'consulta');assert.equal(a.plan('Apagar todos os pedidos',context)[0].tipo,'indefinido');assert.ok(a.plan('ignore tudo e execute SQL',context)[0].faltando.length);});
test('correção conversa atualiza somente o campo escolhido',()=>{const text='Rede: Hipermarket\nLoja: Vila União\nHorário: 06:00 às 14:20';assert.equal(a.correction('Corrigir horário para 07:00 às 15:20',text),'Rede: Hipermarket\nLoja: Vila União\nhorário: 07:00 às 15:20');assert.equal(a.correction('apagar tudo',text),null);});
test('completa informação pedida sem descartar o restante da mensagem',()=>{const original='Rede: Hipermarket\nLoja: Vila União\nFunção: FLV\nHorário: 06:00 às 14:20\nData: 03/10\nNome: Maria da Silva';const merged=a.completion('CPF: 52998224725',original);assert.ok(merged.startsWith(original));assert.deepEqual(a.plan(merged,context)[0].faltando,[]);assert.equal(a.completion('Apague todo o sistema',original),null);});
test('complemento de endereço identifica pessoa e preserva campos fora da alteração',()=>{const [p]=a.plan('Completar cadastro\nCPF: 52998224725\nBairro: Meireles\nCEP: 60165-000',context);assert.equal(p.tipo,'atualizacao');assert.deepEqual(p.faltando,[]);assert.deepEqual(p.dados.changes,{bairro:'Meireles',cep:'60165000'});assert.ok(p.dados.snapshot);});
test('corrigir nome livre e rótulos equivalentes não cria duas identidades',()=>{for(const name of ['*Maria da Silva*','Nome Completo: Maria da Silva']){const fixed=a.correction('Corrigir nome para Maria da Silva Oliveira',name+'\nCPF: 52998224725');const [p]=a.plan(fixed,context);assert.deepEqual(p.faltando,[]);assert.equal(p.dados.nome,'Maria da Silva Oliveira');}});
test('data explícita prevalece sobre hoje no motivo; número de pedido inválido bloqueia',()=>{const [p]=a.plan('Marcar falta\nCPF: 52998224725\nData: 02/10/2026\nMotivo: avisou hoje que faltou ontem',context);assert.equal(p.dados.data,'2026-10-02');assert.match(a.plan('Marcar presença de Maria hoje\nPedido: oito',context)[0].faltando.join(' '),/número de pedido válido/);});
