const {test}=require('node:test');const assert=require('node:assert/strict');const {build,filter,counts,networkNames}=require('../static/crm-model.js');
const order={id:1,supermercado:'Super do Povo',unidade:'Meireles',setor:'FLV',situacao:'confirmado',quantidade_diaristas:2,turnos:[{data:'2026-09-30',inicio:'07:00',fim:'15:20'}]};
const scale={id:2,pedido_id:1,diarista_id:3,diarista_nome:'Pessoa Teste',data:'2026-09-30',status:'escalada',confirmacao:'confirmou'};
test('pedido confirmado mantém vagas e presença pendente como etapas abertas, sem inventar presença',()=>{const r=build({orders:[order],scales:[scale]},'2026-09-30');assert.equal(r.find(x=>x.key==='pedido:1').stage,'confirmado');assert.equal(r.find(x=>x.key==='escala:2').stage,'aberto');assert.ok(r.some(x=>x.key==='vaga:1:2026-09-30'));assert.equal(counts(r).aberto,2);assert.equal(new Set(r.map(x=>x.key)).size,r.length);});
test('disponibilidade futura, presença, validação e falta possuem estados distintos',()=>{const input={orders:[order],scales:[scale]};assert.equal(build(input,'2026-09-29').find(x=>x.key==='escala:2').stage,'confirmado');input.scales=[{...scale,status:'presente',loja_validacao:'pendente'}];assert.equal(build(input,'2026-09-30').find(x=>x.key==='escala:2').stage,'confirmado');input.scales[0].loja_validacao='validado';assert.equal(build(input,'2026-09-30').find(x=>x.key==='escala:2').stage,'concluido');input.scales=[{...scale,status:'falta'}];assert.equal(build(input,'2026-09-30').find(x=>x.key==='escala:2').stage,'aberto');assert.match(build(input,'2026-09-30').find(x=>x.kind==='escala'&&x.key.startsWith('vaga')).title,/2 vaga/);});
test('recebimento parcial, conferência, pagamento, cancelamento e exclusão são derivados dos registros',()=>{const invoice={id:4,rede:'Super do Povo',status:'aberta',valor_centavos:26800,valor_recebido_centavos:10000,vencimento:'2026-09-20',itens:[{diaria_id:5}],conferencia:'conferida'};const f={id:5,origem:'diaria',pedido_escala_id:2,valor_centavos:9000,valor_recebido_centavos:13400,tipo:'despesa',contraparte:'Pessoa Teste',descricao:'Diária',vencimento:'2026-09-30'};let r=build({orders:[order],scales:[{...scale,status:'presente'}],finance:[f],invoices:[invoice]},'2026-09-30');assert.equal(r.find(x=>x.key==='cobranca:4').amount,16800);assert.equal(r.find(x=>x.key==='cobranca:4').overdue,true);assert.equal(r.find(x=>x.key==='cobranca:4').stage,'confirmado');assert.equal(r.some(x=>x.key==='faturar:5'),false);r=build({orders:[order],scales:[scale],finance:[{...f,data_pagamento:'2026-09-30'}],invoices:[{...invoice,valor_recebido_centavos:26800}]},'2026-09-30');assert.equal(r.find(x=>x.key==='cobranca:4').stage,'concluido');assert.equal(r.find(x=>x.kind==='pagamento').stage,'concluido');r=build({orders:[{...order,situacao:'cancelado'}],scales:[scale]},'2026-09-30');assert.equal(r.some(x=>x.key.startsWith('vaga')),false);assert.equal(r.find(x=>x.key==='escala:2').stage,'cancelado');assert.deepEqual(build({},'2026-09-30'),[]);});
test('busca sem acentos, tipos, redes, prazo vencido e datas filtram corretamente',()=>{const r=build({orders:[order],scales:[{...scale,data:'2026-09-29'}],workers:[{id:3,nome:'João',telefone:'',bloqueada:false}]},'2026-09-30');assert.equal(filter(r,{search:'joao'})[0].kind,'cadastro');assert.ok(filter(r,{network:'super do povo'}).every(x=>x.network==='Super do Povo'));assert.ok(filter(r,{start:'2026-09-30',end:'2026-09-30'}).every(x=>x.date==='2026-09-30'));assert.ok(filter(r,{overdue:true}).every(x=>x.overdue));assert.equal(filter(r,{kind:'pagamento'}).length,0);});
test('leituras, ocorrências, cadastros e contratos só refletem informações reais',()=>{const r=build({readings:[{id:1,status:'pendente',tipo:'pedido',faltando:['rede']},{id:2,status:'resolvido'}],occurrences:[{id:1,pedido_id:1,estado:'resolvida',tipo:'atraso',descricao:'Resolvido'}],workers:[{id:1,nome:'Bloqueada',bloqueada:true},{id:2,nome:'Atual',telefone:'85999999999',disponibilidade_confirmada_em:'2026-09-30'}],contracts:[{id:1,rede:'Super do Povo',fim:'2026-10-10'}]},'2026-09-30');assert.equal(r.filter(x=>x.kind==='cadastro').length,0);assert.equal(r.find(x=>x.key==='leitura:1').stage,'aberto');assert.equal(r.find(x=>x.key==='leitura:2').stage,'concluido');assert.equal(r.find(x=>x.kind==='contrato').stage,'aberto');assert.equal(r.find(x=>x.kind==='ocorrencia').stage,'concluido');});

assert.deepEqual(networkNames([{network:'Super do povo'},{network:'Super do Povo'}],[{rede:'Super do Povo'}]),['Super do Povo']);
assert.equal(build({finance:[{id:1,origem:'manual',referencia:'2026-09-30',vencimento:null,descricao:'Teste'}]},'2026-09-30')[0].date,'2026-09-30');
