import assert from 'node:assert/strict';import {spawn}from'node:child_process';import{mkdtemp,rm}from'node:fs/promises';import os from'node:os';import path from'node:path';import net from'node:net';import{chromium,webkit}from'playwright';
const folder=await mkdtemp(path.join(os.tmpdir(),'direct-usability-')),socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));const url='http://127.0.0.1:'+port,child=spawn(process.env.PYTHON||'python3',['server.py'],{env:{...process.env,DIARISTAS_DB_PATH:path.join(folder,'test.db'),DIARISTAS_PORT:String(port)},stdio:'ignore'});
let serial=999710100;const nextCpf=()=>{let v=String(++serial);for(let size=9;size<=10;size++){const n=[...v].reduce((a,x,i)=>a+Number(x)*(size+1-i),0)*10%11;v+=n===10?'0':String(n);}return v;};
const api=async(method,route,body)=>{const r=await fetch(url+route,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),d=await r.json();assert.ok(r.ok,JSON.stringify(d));return d;};
try{for(let i=0;i<80;i++){try{await api('GET','/api/lojas');break;}catch{}await new Promise(r=>setTimeout(r,100));}
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),tomorrow=new Date(today+'T12:00:00');tomorrow.setDate(tomorrow.getDate()+1);const second=tomorrow.toISOString().slice(0,10),availability=['segunda','terca','quarta','quinta','sexta','sabado','domingo'].map(dia=>({dia,inicio:'00:00',fim:'23:59'}));
for(const [engine,name]of[[chromium,'Chromium'],[webkit,'WebKit']])for(const width of[1280,390,320]){
 const worker=await api('POST','/api/diaristas',{nome:'Original Pesquisa João '+name+' '+width,cpf:nextCpf(),setores:['FLV'],disponibilidade:availability,pode_se_deslocar:true}),sub=await api('POST','/api/diaristas',{nome:'Substituta Completa '+name+' '+width,cpf:nextCpf(),setores:['FLV'],disponibilidade:availability,pode_se_deslocar:true}),order=await api('POST','/api/pedidos',{supermercado:'Super do Povo',unidade:'Meireles',setor:'FLV',quantidade_diaristas:1,turnos:[today,second].map(data=>({data,inicio:'07:00',fim:'15:20'}))});
 await api('POST',`/api/pedidos/${order.id}/escalas`,{diarista_id:worker.id,datas:[today,second]});const scale=(await api('GET',`/api/pedidos/${order.id}/escalas`))[0];
 const browser=await engine.launch(),context=await browser.newContext({viewport:{width,height:844},isMobile:width<500,hasTouch:width<500}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.copies=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async t=>copies.push(t)}});});
 await page.goto(url+'/#crm');await page.waitForFunction(()=>window.DirectUI&&window.DirectHub);await page.locator('#global-search-button').click();await page.locator('#global-search-input').fill('joao');const result=page.locator('.search-result[data-kind=diarista]').filter({hasText:worker.nome});await result.waitFor();await result.click();await page.locator('#detail-dialog').waitFor();assert.equal(await page.locator('#detail-title').innerText(),worker.nome);await page.locator('#detail-close-button').click();await page.locator('#global-search-button').click();await page.locator('#global-search-input').fill('meireles');const storeResult=page.locator('.search-result[data-kind=loja]').filter({hasText:'Super do Povo'});await storeResult.waitFor();await storeResult.click();await page.locator('#redes-page').waitFor();await page.waitForFunction(()=>document.querySelector('#stores-search').value==='Meireles');assert.equal(await page.locator('#stores-search').inputValue(),'Meireles');
 await page.locator('#nav-crm').click();await page.evaluate(()=>loadHome());const pending=page.locator(`[data-crm-key="pedido:${order.id}"][data-view="pending"]`);await pending.waitFor();await pending.locator('.queue-organize>summary').click();await pending.getByLabel('Responsável',{exact:true}).fill('Operação Direct');await pending.getByLabel('Próxima ação',{exact:true}).fill('Conferir resposta amanhã');const due=new Date(Date.now()+86400000);const local=new Date(due-due.getTimezoneOffset()*60000).toISOString().slice(0,16);await pending.getByLabel('Adiar até (opcional)',{exact:true}).fill(local);await page.evaluate(()=>loadHome());assert.equal(await pending.getByLabel('Responsável',{exact:true}).inputValue(),'Operação Direct');await pending.getByRole('button',{name:'✓ Salvar',exact:true}).click();await pending.waitFor({state:'hidden'});await page.locator('#crm-snoozed').click();await pending.waitFor();assert.match(await pending.innerText(),/Operação Direct/);await pending.locator('.queue-organize>summary').click();await pending.getByRole('button',{name:'↻ Retomar agora'}).click();await pending.waitFor({state:'hidden'});await page.locator('#crm-pending').click();await pending.waitFor();assert.equal((await api('GET','/api/pedidos')).find(o=>o.id===order.id).situacao,'confirmado','Adiar não muda status de pedido');
 await page.evaluate(id=>openOrderDetail(id),order.id);await page.locator('#order-detail-store').waitFor();const row=page.locator(`[data-scale-id="${scale.id}"]`);await row.getByRole('button',{name:/^Substituir /}).click();await page.locator('.replacement-suggestions').waitFor();await page.locator('.replacement-candidate').first().waitFor();await page.getByLabel('Pessoa substituta de '+worker.nome,{exact:true}).selectOption(String(sub.id));await page.getByRole('radio',{name:/Este dia e os dias restantes do pedido/}).check();await page.locator('.order-substitute-panel').getByRole('button',{name:'♧ Copiar convite',exact:true}).click();await page.waitForFunction(()=>copies.length>0);const copied=await page.evaluate(()=>copies.at(-1));assert.match(copied,/Substituta Completa/);assert.match(copied,/Rua Júlio Ibiapina/);assert.ok(copied.includes(second.split('-').reverse().join('/')));assert.ok(!copied.includes(sub.cpf));await page.locator('.order-substitute-panel').getByLabel('Resposta da pessoa substituta').selectOption('confirmou');await page.getByRole('button',{name:'✓ Registrar resposta',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#direct-notice').textContent.includes('Resposta registrada'));assert.equal((await api('GET','/api/substituicao-contatos'))[0].resposta,'confirmou');assert.equal((await api('GET','/api/financeiro')).length,0);
 await page.getByLabel('Motivo da desistência para substituir').fill('Solicitou substituição para todos os dias');await page.getByLabel(/Confirmei a disponibilidade da pessoa substituta/).check();await page.getByRole('button',{name:'Salvar substituição',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#order-detail-success').textContent.includes('Substituição registrada'));const scales=await api('GET',`/api/pedidos/${order.id}/escalas`);assert.equal(scales.filter(s=>s.diarista_id===sub.id).length,2);assert.equal(scales.filter(s=>s.status==='desistiu').length,2);assert.equal((await api('GET','/api/financeiro')).length,0);
 // Desistência retira os dias restantes; substituição permite escolher só um dia e depois completar o restante.
 await page.locator('#order-detail-close').click();
 const thirdDate=new Date(second+'T12:00:00');thirdDate.setDate(thirdDate.getDate()+1);const third=thirdDate.toISOString().slice(0,10);
 const next=await api('POST','/api/pedidos',{supermercado:'Super do Povo',unidade:'Meireles',setor:'FLV',quantidade_diaristas:1,turnos:[today,second,third].map(data=>({data,inicio:'07:00',fim:'15:20'}))});
 await api('POST',`/api/pedidos/${next.id}/escalas`,{diarista_id:worker.id,datas:[today,second]});
 await page.evaluate(async id=>{await loadOrders();await openOrderDetail(id)},next.id);
 const original=(await api('GET',`/api/pedidos/${next.id}/escalas`))[0];
 page.once('dialog',d=>d.accept('Não pode continuar neste pedido'));
 await page.getByRole('button',{name:`Desistência de ${worker.nome} em ${today.split('-').reverse().join('/')}`,exact:true}).click();
 await page.locator('.order-substitute-panel').waitFor();
 let released=await api('GET',`/api/pedidos/${next.id}/escalas`);assert.ok(released.every(s=>s.status==='desistiu'));assert.equal(released.length,2);
 assert.ok(await page.getByRole('radio',{name:/Somente este dia/}).isChecked());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));assert.ok(await page.locator('.order-substitute-panel').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await page.locator('.replacement-scope').scrollIntoViewIfNeeded();await page.screenshot({path:`/tmp/direct-replacement-${name}-${width}.png`});
 await page.getByLabel('Pessoa substituta de '+worker.nome,{exact:true}).selectOption(String(sub.id));
 await page.getByRole('button',{name:'Salvar substituição',exact:true}).click();await page.locator('.order-substitute-panel').waitFor({state:'hidden'});await page.waitForFunction(()=>!orderDetailBusy);
 released=await api('GET',`/api/pedidos/${next.id}/escalas`);assert.deepEqual(released.filter(s=>s.diarista_id===sub.id).map(s=>s.data),[today]);
 const later=released.find(s=>s.diarista_id===worker.id&&s.data===second);await page.locator(`[data-scale-id="${later.id}"]`).getByRole('button',{name:/^Substituir /}).click();
 await page.getByLabel('Pessoa substituta de '+worker.nome,{exact:true}).selectOption(String(sub.id));await page.getByRole('radio',{name:/Este dia e os dias restantes do pedido/}).check();
 await page.getByRole('button',{name:'Salvar substituição',exact:true}).click();await page.locator('.order-substitute-panel').waitFor({state:'hidden'});await page.waitForFunction(()=>!orderDetailBusy);
 released=await api('GET',`/api/pedidos/${next.id}/escalas`);assert.deepEqual(released.filter(s=>s.diarista_id===sub.id).map(s=>s.data),[today,second,third]);assert.equal((await api('GET','/api/financeiro')).length,0);
 for(const theme of['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));if(width<500)assert.ok(await page.evaluate(()=>[...document.querySelectorAll('input,select,textarea')].filter(x=>x.getClientRects().length).every(x=>parseFloat(getComputedStyle(x).fontSize)>=16)));await page.screenshot({path:`/tmp/direct-usability-${name}-${width}-${theme}.png`});}
 await api('PUT',`/api/pedidos/${order.id}`,{...order,situacao:'cancelado'});await api('PUT',`/api/pedidos/${next.id}`,{...next,situacao:'cancelado'});
 assert.deepEqual(errors,[]);await browser.close();console.log(`${name} ${width}: busca, fila, adiamento, resposta, convite sem CPF, substituição em lote, finanças e temas OK`);
}
}finally{child.kill();await rm(folder,{recursive:true,force:true});}
