-- Integração real com dados sintéticos e rollback, sem remover pedidos reais.
begin;
do $$
declare uid uuid:=gen_random_uuid();w1 bigint;w2 bigint;o1 bigint;o2 bigint;o3 bigint;past bigint;remaining bigint;board text;i jsonb;list jsonb;
 d date:=(now() at time zone 'America/Fortaleza')::date+3;t jsonb;
begin
 insert into auth.users(id,email,email_confirmed_at) values(uid,'vagas-sintetico@example.invalid',now());
 insert into public.direct_staff(email,role,active) values('vagas-sintetico@example.invalid','operacao',true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',uid,'email','vagas-sintetico@example.invalid','role','authenticated')::text,true);
 insert into public.diaristas(nome,cpf,setores) values('Vagas sintético um','52998224725','["FLV"]') returning id into w1;
 insert into public.diaristas(nome,cpf,setores) values('Vagas sintético dois','11144477735','["FLV"]') returning id into w2;
 board:=public.direct_portal_board_link()->>'token';
 if board is distinct from public.direct_portal_board_link()->>'token' then raise exception 'Link compartilhado mudou';end if;
 i:=public.direct_portal_vacancies_invite(w1);
 if not (public.direct_portal_context(i->>'vagas_token','vagas')->>'cadastrado')::boolean then raise exception 'Link de vagas não vinculou cadastro existente';end if;
 begin perform public.direct_portal_vacancies_invite(0);raise exception 'FALHOU: convite sem cadastro';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 update public.diaristas set bloqueada=true where id=w2;
 begin perform public.direct_portal_vacancies_invite(w2);raise exception 'FALHOU: convite bloqueado';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 update public.diaristas set bloqueada=false where id=w2;
 t:=jsonb_build_array(jsonb_build_object('data',d,'inicio','07:00','fim','15:20'),jsonb_build_object('data',d+1,'inicio','07:00','fim','15:20'));
 insert into public.pedidos(supermercado,unidade,setor,quantidade_diaristas,turnos) values('Portal vagas teste','Loja sintética','FLV',1,t) returning id into o1;
 list:=public.direct_portal_vacancies();
 if not list @> jsonb_build_array(jsonb_build_object('id',o1)) then raise exception 'Pedido gravado não aparece no painel';end if;
 perform set_config('request.jwt.claims','{}',true);
 if not public.direct_portal_board_orders(board) @> jsonb_build_array(jsonb_build_object('id',o1)) then raise exception 'Link compartilhado não mostra pedido';end if;
 begin perform public.direct_portal_board_orders(repeat('0',64));raise exception 'FALHOU: token errado';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 begin perform public.direct_portal_take_order(o1,board,'52998224725');raise exception 'FALHOU: link compartilhado escalou';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 if not public.direct_portal_orders(i->>'vagas_token') @> jsonb_build_array(jsonb_build_object('id',o1)) then raise exception 'Pedido gravado não aparece no link';end if;
 begin perform public.direct_portal_vacancies();raise exception 'FALHOU: anônimo leu painel';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 insert into public.pedido_escalas(pedido_id,diarista_id,data,disponibilidade_pedido_confirmada) values(o1,w1,d,true);
 if public.direct_portal_orders(i->>'vagas_token') @> jsonb_build_array(jsonb_build_object('id',o1)) then raise exception 'Escala sem vaga em todos os dias ficou pública';end if;
 insert into public.pedido_escalas(pedido_id,diarista_id,data,disponibilidade_pedido_confirmada) values(o1,w1,d+1,true);
 if not exists(select 1 from public.pedidos where id=o1) or (select jsonb_array_length(turnos) from public.pedidos where id=o1)<>2 then raise exception 'Publicação alterou/excluiu pedido interno';end if;
 update public.pedido_escalas set status='desistiu',desistencia_motivo='Desistência sintética de teste' where pedido_id=o1;
 if not public.direct_portal_orders(i->>'vagas_token') @> jsonb_build_array(jsonb_build_object('id',o1)) then raise exception 'Desistência não reabriu vagas';end if;
 update public.pedidos set situacao='cancelado' where id=o1;
 if public.direct_portal_orders(i->>'vagas_token') @> jsonb_build_array(jsonb_build_object('id',o1)) then raise exception 'Cancelado publicado';end if;
 insert into public.pedidos(supermercado,unidade,setor,quantidade_diaristas,turnos) values('Portal vagas teste','Duas vagas','FLV',2,t) returning id into o2;
 insert into public.pedido_escalas(pedido_id,diarista_id,data,disponibilidade_pedido_confirmada) values(o2,w1,d,true),(o2,w1,d+1,true);
 if not public.direct_portal_orders(i->>'vagas_token') @> jsonb_build_array(jsonb_build_object('id',o2)) then raise exception 'Pedido com vaga restante sumiu';end if;
 insert into public.pedido_escalas(pedido_id,diarista_id,data,disponibilidade_pedido_confirmada) values(o2,w2,d,true),(o2,w2,d+1,true);
 if public.direct_portal_orders(i->>'vagas_token') @> jsonb_build_array(jsonb_build_object('id',o2)) then raise exception 'Pedido preenchido permanece público';end if;
 if public.direct_portal_board_orders(board) @> jsonb_build_array(jsonb_build_object('id',o2)) then raise exception 'Preenchido ficou no link compartilhado';end if;
 if not exists(select 1 from public.pedidos where id=o2) then raise exception 'Pedido preenchido excluído';end if;
 insert into public.pedidos(supermercado,unidade,setor,quantidade_diaristas,turnos) values('Portal vagas teste','Exclusão sem escala','FLV',1,t) returning id into o3;
 delete from public.pedidos where id=o3;
 if public.direct_portal_orders(i->>'vagas_token') @> jsonb_build_array(jsonb_build_object('id',o3)) then raise exception 'Excluído publicado';end if;
 insert into public.pedidos(supermercado,unidade,setor,quantidade_diaristas,turnos) values('Portal vagas teste','Passado','FLV',1,jsonb_build_array(jsonb_build_object('data',d-5,'inicio','07:00','fim','15:20'))) returning id into past;
 if public.direct_portal_orders(i->>'vagas_token') @> jsonb_build_array(jsonb_build_object('id',past)) then raise exception 'Pedido iniciado publicado';end if;
 insert into public.pedidos(supermercado,unidade,setor,quantidade_diaristas,turnos) values('Portal vagas teste','Dias restantes','FLV',1,jsonb_build_array(jsonb_build_object('data',d-5,'inicio','06:00','fim','14:20'),jsonb_build_object('data',d+3,'inicio','06:00','fim','14:20'))) returning id into remaining;
 select item into list from jsonb_array_elements(public.direct_portal_board_orders(board)) item where (item->>'id')::bigint=remaining;
 if list is null or jsonb_array_length(list->'turnos')<>1 then raise exception 'Pedido iniciado não mostrou somente dias futuros';end if;
 if (public.direct_portal_take_order(remaining,i->>'vagas_token','52998224725')->>'dias')::int<>1 then raise exception 'Não escalou todos os dias restantes';end if;
 if exists(select 1 from public.pedido_escalas where pedido_id=remaining and data=d-5) then raise exception 'Escalou dia passado';end if;
 if public.direct_portal_board_orders(board) @> jsonb_build_array(jsonb_build_object('id',remaining)) then raise exception 'Restante preenchido ainda disponível';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',uid,'email','vagas-sintetico@example.invalid','role','authenticated')::text,true);
 update public.direct_staff set role='financeiro' where email='vagas-sintetico@example.invalid';
 begin perform public.direct_portal_vacancies();raise exception 'FALHOU: financeiro acessou painel';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 update public.direct_staff set role='consulta' where email='vagas-sintetico@example.invalid';
 begin perform public.direct_portal_vacancies_invite(w1);raise exception 'FALHOU: consulta gerou convite';exception when others then if sqlerrm like 'FALHOU:%' then raise;end if;end;
 if has_function_privilege('anon','public.direct_portal_vacancies()','execute') or has_function_privilege('anon','public.direct_portal_vacancies_invite(bigint)','execute') or has_function_privilege('anon','public.direct_portal_orders_internal()','execute') then raise exception 'Painel interno aberto';end if;
 if has_table_privilege('anon','direct_private.portal_vagas_link','select') or has_table_privilege('authenticated','direct_private.portal_vagas_link','select') or has_function_privilege('anon','public.direct_portal_board_link()','execute') then raise exception 'Segredo compartilhado exposto';end if;
 raise notice 'VAGAS OK: cadastro vinculado, publicação automática, escala inteira, vagas restantes, desistência, cancelamento, exclusão, histórico e permissões';
end $$;
rollback;
