create function public.direct_empresa_painel(p jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare member text:=direct_private.empresa_role();start_day date:=coalesce(nullif(p->>'inicio','')::date,date_trunc('month',now() at time zone 'America/Fortaleza')::date);end_day date:=coalesce(nullif(p->>'fim','')::date,(now() at time zone 'America/Fortaleza')::date);today date:=(now() at time zone 'America/Fortaleza')::date;orders bigint[];result jsonb;revenue bigint;cost bigint;expenses bigint;missing bigint;expected bigint;planned bigint;estimated bigint;
begin
 if start_day>end_day or end_day-start_day>366 then raise exception 'Escolha um período de até 366 dias.';end if;
 select coalesce(array_agg(o.id),'{}') into orders from public.pedidos o where o.situacao<>'cancelado' and (coalesce(p->>'rede','')='' or o.supermercado=p->>'rede') and (coalesce(p->>'loja','')='' or o.unidade=p->>'loja') and (coalesce(p->>'setor','')='' or o.setor=p->>'setor') and
 (coalesce(p->>'campanha_id','')='' or exists(select 1 from public.empresa_registros v where v.tipo='vinculo' and v.pedido_id=o.id and v.campanha_id=(p->>'campanha_id')::bigint and direct_private.empresa_visible(v))) and
 (coalesce(p->>'cliente_id','')='' or exists(select 1 from public.empresa_registros v where v.tipo='vinculo' and v.pedido_id=o.id and v.cliente_id=(p->>'cliente_id')::bigint and direct_private.empresa_visible(v))) and
 (direct_private.empresa_scope(null) or exists(select 1 from public.empresa_registros v where v.tipo='vinculo' and v.pedido_id=o.id and direct_private.empresa_visible(v)));
 select jsonb_build_object('inicio',start_day,'fim',end_day,'gerado_em',clock_timestamp(),
 'demanda',coalesce((select sum(o.quantidade_diaristas) from public.pedidos o cross join lateral jsonb_array_elements(o.turnos) t where o.id=any(orders) and (t->>'data')::date between start_day and end_day),0),
 'preenchidas',count(*) filter(where s.status not in ('falta','desistiu')),'presencas',count(*) filter(where s.status='presente'),'faltas',count(*) filter(where s.status='falta'),
 'presencas_pendentes',count(*) filter(where s.status='escalada' and s.data<=today),'registros_considerados',count(*),
 'fontes',jsonb_build_array('Pedidos','Escalas e presenças','Diárias vinculadas'),
 'pedidos',(select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'titulo','#'||o.id||' · '||o.supermercado||' · '||o.unidade)),'[]') from public.pedidos o where o.id=any(orders) and exists(select 1 from jsonb_array_elements(o.turnos)t where (t->>'data')::date between start_day and end_day))) into result from public.pedido_escalas s where s.pedido_id=any(orders) and s.data between start_day and end_day;
 result:=result||jsonb_build_object('execucao',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(
  select o.supermercado rede,(t->>'data')::date data,sum(o.quantidade_diaristas) demanda,
  sum((select count(*) from public.pedido_escalas s where s.pedido_id=o.id and s.data=(t->>'data')::date and s.status not in ('falta','desistiu'))) preenchidas,
  sum((select count(*) from public.pedido_escalas s where s.pedido_id=o.id and s.data=(t->>'data')::date and s.status='presente')) presencas,
  sum((select count(*) from public.pedido_escalas s where s.pedido_id=o.id and s.data=(t->>'data')::date and s.confirmacao='confirmada')) confirmadas,
  bool_or(exists(select 1 from public.empresa_registros c where c.tipo='fechamento' and c.status='fechado' and c.dados->>'data'=t->>'data' and c.pedido_id is null and c.campanha_id is not distinct from nullif(p->>'campanha_id','')::bigint and c.cliente_id is not distinct from nullif(p->>'cliente_id','')::bigint)) fechado
  from public.pedidos o cross join lateral jsonb_array_elements(o.turnos)t where o.id=any(orders) and (t->>'data')::date between start_day and end_day group by o.supermercado,t->>'data' order by data,rede limit 200)x));
 if member in ('admin','financeiro') then
  select coalesce(sum(d.valor_recebido_centavos),0),coalesce(sum(d.valor_centavos),0),count(*) filter(where d.valor_centavos is null or d.valor_recebido_centavos is null) into revenue,cost,missing from public.diarias d join public.pedido_escalas s on s.id=d.pedido_escala_id where s.pedido_id=any(orders) and d.data between start_day and end_day;
  select coalesce(sum((r.dados->>'valor_centavos')::bigint),0) into expenses from public.empresa_registros r where tipo='despesa' and status in ('aprovada','paga') and (r.dados->>'data')::date between start_day and end_day and direct_private.empresa_visible(r) and (coalesce(p->>'cliente_id','')='' or cliente_id=(p->>'cliente_id')::bigint) and (coalesce(p->>'campanha_id','')='' or campanha_id=(p->>'campanha_id')::bigint) and ((coalesce(p->>'rede','')='' and coalesce(p->>'loja','')='' and coalesce(p->>'setor','')='') or pedido_id=any(orders)) and lower(coalesce((select c.dados->>'centro_custo' from public.empresa_registros c where c.id=(r.dados->>'categoria_id')::bigint),'')) not in ('administração','administracao');
  select coalesce(sum(o.quantidade_diaristas*(q.dados->>'custo_unitario_centavos')::bigint),0) into expected from public.empresa_registros q join public.pedidos o on o.id=q.pedido_id cross join lateral jsonb_array_elements(o.turnos)t where q.tipo='proposta' and q.status='convertida' and o.id=any(orders) and (t->>'data')::date between start_day and end_day;
  select coalesce(sum((q.dados->>'custo_unitario_centavos')::bigint),0) into planned from public.pedido_escalas s join public.empresa_registros q on q.pedido_id=s.pedido_id and q.tipo='proposta' and q.status='convertida' where s.pedido_id=any(orders) and s.status not in ('falta','desistiu') and s.data between start_day and end_day;
  select coalesce(sum((r.dados->>'orcamento_custo_centavos')::bigint),0) into estimated from public.empresa_registros r where tipo='orcamento' and status='aprovado' and direct_private.empresa_visible(r) and exists(select 1 from public.empresa_registros c where c.id=r.campanha_id and (c.dados->>'inicio')::date<=end_day and (c.dados->>'fim')::date>=start_day) and (coalesce(p->>'campanha_id','')='' or r.campanha_id=(p->>'campanha_id')::bigint) and (coalesce(p->>'cliente_id','')='' or r.cliente_id=(p->>'cliente_id')::bigint);
  result:=result||jsonb_build_object('aportes_centavos',(select coalesce(sum((c.dados->>'valor_centavos')::bigint),0) from public.empresa_registros c where c.tipo='movimento_caixa' and c.dados->>'tipo'='aporte' and (c.dados->>'data')::date between start_day and end_day),'retiradas_centavos',(select coalesce(sum((c.dados->>'valor_centavos')::bigint),0) from public.empresa_registros c where c.tipo='movimento_caixa' and c.dados->>'tipo'='retirada' and (c.dados->>'data')::date between start_day and end_day),'receita_real_centavos',revenue,'diarias_custo_centavos',cost,'despesas_aprovadas_centavos',expenses,'margem_contribuicao_centavos',revenue-cost-expenses,'valores_incompletos',missing,'custo_estimado_campanhas_centavos',estimated,'custo_contratado_propostas_centavos',expected,'custo_planejado_propostas_centavos',planned,
  'saldo_atrasado_centavos',(select coalesce(sum(c.valor_centavos-coalesce((select sum(r.valor_centavos) from public.cobranca_recebimentos r where r.cobranca_id=c.id and not r.estornado),0)),0) from public.cobrancas c where c.status='aberta' and c.vencimento<today and exists(select 1 from public.cobranca_itens i where i.cobranca_id=c.id and i.pedido_id=any(orders))),
  'cobrancas_atrasadas',(select count(*) from public.cobrancas c where c.status='aberta' and c.vencimento<today and exists(select 1 from public.cobranca_itens i where i.cobranca_id=c.id and i.pedido_id=any(orders))));
 end if;return result;
end;$$;
create function public.direct_empresa_cobrancas(p jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare member text:=direct_private.empresa_role();begin if member not in ('admin','financeiro') then raise exception 'Seu perfil não pode consultar cobranças.' using errcode='42501';end if;
 return (select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select c.*,coalesce((select sum(r.valor_centavos) from public.cobranca_recebimentos r where r.cobranca_id=c.id and not r.estornado),0) valor_recebido_centavos from public.cobrancas c where c.status='aberta' and (direct_private.empresa_scope(null) or exists(select 1 from public.cobranca_itens i join public.empresa_registros v on v.pedido_id=i.pedido_id where i.cobranca_id=c.id and v.tipo='vinculo' and direct_private.empresa_visible(v))) and (coalesce(p->>'cliente_id','')='' and coalesce(p->>'campanha_id','')='' or exists(select 1 from public.cobranca_itens i join public.empresa_registros v on v.pedido_id=i.pedido_id where i.cobranca_id=c.id and v.tipo='vinculo' and (coalesce(p->>'cliente_id','')='' or v.cliente_id=(p->>'cliente_id')::bigint) and (coalesce(p->>'campanha_id','')='' or v.campanha_id=(p->>'campanha_id')::bigint))) order by c.vencimento limit 500)x);
end;$$;
create function public.direct_empresa_reservas(p jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare member text:=direct_private.empresa_role();o public.pedidos;today date:=(now() at time zone 'America/Fortaleza')::date;
begin if member not in ('admin','operacao') then raise exception 'Seu perfil não pode selecionar equipe.' using errcode='42501';end if;
 select * into o from public.pedidos where id=(p->>'pedido_id')::bigint;
 if o.id is null or (not direct_private.empresa_scope(null) and not exists(select 1 from public.empresa_registros v where v.pedido_id=o.id and v.tipo='vinculo' and direct_private.empresa_visible(v))) then raise exception 'Pedido fora do escopo.' using errcode='42501';end if;
 return jsonb_build_object('pedido_id',o.id,'datas',(select jsonb_agg(t->>'data') from jsonb_array_elements(o.turnos)t),'items',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(
 select w.id,w.nome,true elegivel,jsonb_build_array(case when exists(select 1 from jsonb_array_elements_text(w.setores)s where lower(s)=lower(o.setor)) then 'Experiência declarada na função' else 'Função não consta na experiência declarada' end)||coalesce((select jsonb_agg('Conferido: '||r.titulo) from public.empresa_registros r where r.tipo='qualificacao' and r.diarista_id=w.id and r.status='conferida' and ((r.dados->>'validade')::date is null or (r.dados->>'validade')::date>=greatest(today,(select max((t->>'data')::date) from jsonb_array_elements(o.turnos)t)))),'[]') motivos,
 jsonb_build_array('Confirmar interesse e disponibilidade para este pedido antes de escalar.') avisos
 from public.diaristas w where not w.bloqueada order by exists(select 1 from jsonb_array_elements_text(w.setores)s where lower(s)=lower(o.setor)) desc,w.nome limit 100)x));
end;$$;

-- Every new API denies public/anonymous execution unless explicitly external.
do $$declare f record;begin for f in select n.nspname,p.proname,pg_get_function_identity_arguments(p.oid) args from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='direct_private' and p.proname like 'empresa_%') or (n.nspname='public' and p.proname like 'direct_empresa_%') loop
 execute format('revoke all on function %I.%I(%s) from public,anon,authenticated',f.nspname,f.proname,f.args);
 if f.nspname='public' then execute format('grant execute on function %I.%I(%s) to authenticated',f.nspname,f.proname,f.args);end if;
end loop;end;$$;
grant execute on function public.direct_empresa_relatorio_publico(jsonb) to anon;
-- Helpers called by RLS policies need execution, and still use trusted membership.
grant execute on function direct_private.empresa_contract(),direct_private.empresa_visible(public.empresa_registros),direct_private.empresa_scope(bigint) to authenticated;

insert into public.empresa_registros(tipo,titulo,status,dados,chave,autor)
 select 'categoria',name,'ativo',jsonb_build_object('tipo','despesa','centro_custo',case when name='Administração' then 'Administração' else 'Serviços' end),'seed:categoria:'||name,'Sistema' from unnest(array['Transporte','Alimentação','Materiais','Administração'])name;
insert into public.empresa_registros(tipo,titulo,status,dados,chave,autor)
 select 'rede',min(rede),'ativo',jsonb_build_object('tipo','supermercado'),'seed:rede:'||min(rede),'Sistema' from public.lojas group by lower(trim(rede));
