-- Additive business workspace. Existing records and identifiers are preserved.
create table public.empresa_registros (
 id bigint generated by default as identity primary key,tipo text not null,titulo text not null check(length(trim(titulo)) between 1 and 180),
 status text not null,dados jsonb not null check(jsonb_typeof(dados)='object'),
 cliente_id bigint references public.empresa_registros(id),campanha_id bigint references public.empresa_registros(id),
 pedido_id bigint references public.pedidos(id),diarista_id bigint references public.diaristas(id),loja_id bigint references public.lojas(id),
 chave text not null unique check(length(chave) between 8 and 180),versao bigint not null default 1,
 autor text not null,criado_em timestamptz not null default now(),atualizado_em timestamptz not null default now()
);
create index empresa_tipo_cliente on public.empresa_registros(tipo,cliente_id,id desc);
create index empresa_pedido on public.empresa_registros(pedido_id,tipo);
create index empresa_campanha on public.empresa_registros(campanha_id,tipo);
create index empresa_diarista on public.empresa_registros(diarista_id,tipo);
create index empresa_loja on public.empresa_registros(loja_id,tipo);
create unique index empresa_vinculo_unico on public.empresa_registros(pedido_id) where tipo='vinculo';
create unique index empresa_ciencia_unica on public.empresa_registros((dados->>'briefing_id'),diarista_id) where tipo='ciencia';
create unique index empresa_leitura_unica on public.empresa_registros((dados->>'aviso_id'),autor) where tipo='leitura_aviso';
create unique index empresa_fechamento_unico on public.empresa_registros((dados->>'data'),coalesce(pedido_id,0),coalesce(cliente_id,0),coalesce(campanha_id,0)) where tipo='fechamento';
create table public.empresa_extrato (
 id bigint generated by default as identity primary key,conta_id bigint not null references public.empresa_registros(id),
 chave text not null unique,data date not null,valor_centavos bigint not null check(valor_centavos<>0 and abs(valor_centavos)<=1000000000),
 descricao text not null,identificador text not null default '',estado text not null default 'pendente' check(estado in ('pendente','conciliado','ignorada')),
 destino_tipo text,destino_id bigint,motivo text not null default '',versao bigint not null default 1,
 criado_em timestamptz not null default now(),atualizado_em timestamptz not null default now()
);
create index empresa_extrato_conta_data on public.empresa_extrato(conta_id,data desc,id desc);
create unique index empresa_extrato_baixa on public.empresa_extrato(destino_tipo,destino_id) where estado='conciliado' and destino_tipo in ('lancamento','lote_pagamento');
create table public.empresa_anexos (
 id bigint generated by default as identity primary key,registro_id bigint not null references public.empresa_registros(id),
 nome text not null,mime text not null check(mime in ('image/jpeg','image/png','image/webp')),
 bytes bigint not null check(bytes between 1 and 1048576),caminho text not null unique,
 sha256 text not null check(sha256 ~ '^[a-f0-9]{64}$'),criado_em timestamptz not null default now(),autor text not null
);
create index empresa_anexos_registro on public.empresa_anexos(registro_id);
create table direct_private.empresa_compartilhamentos (
 id bigint generated by default as identity primary key,registro_id bigint not null unique references public.empresa_registros(id),
 codigo text not null unique default translate(encode(extensions.gen_random_bytes(18),'base64'),'+/','-_'),criado_em timestamptz not null default now()
);
alter table direct_private.empresa_compartilhamentos enable row level security;
revoke all on direct_private.empresa_compartilhamentos from public,anon,authenticated;
alter table public.financeiro_lancamentos add column empresa_registro_id bigint references public.empresa_registros(id);
create unique index financeiro_empresa_unico on public.financeiro_lancamentos(empresa_registro_id) where empresa_registro_id is not null;

create function direct_private.empresa_role() returns text language plpgsql stable security definer set search_path='' as $$
declare r text:=direct_private.member_role();begin
 if auth.uid() is null or coalesce(r,'') not in ('admin','operacao','financeiro','consulta') then raise exception 'Entre com um perfil autorizado.' using errcode='42501';end if;return r;
end;$$;
create function direct_private.empresa_scope(cid bigint) returns boolean language sql stable security definer set search_path='' as $$
 select direct_private.member_role()='admin' or not exists(select 1 from public.empresa_registros where tipo='acesso' and status='ativo' and lower(dados->>'email')=lower(auth.jwt()->>'email')) or exists(select 1 from public.empresa_registros where tipo='acesso' and status='ativo' and lower(dados->>'email')=lower(auth.jwt()->>'email') and cliente_id=cid)
$$;
create function direct_private.empresa_visible(r public.empresa_registros) returns boolean language plpgsql stable security definer set search_path='' as $$
declare member text:=direct_private.member_role();spec jsonb:=direct_private.empresa_contract()->'entities'->r.tipo;
begin
 if auth.uid() is null or not coalesce(spec->'read' ? member,false) then return false;end if;
 if r.tipo='leitura_aviso' and member<>'admin' then return r.autor=auth.jwt()->>'email';end if;
 if r.tipo='aviso' and member<>'admin' and ((r.dados->>'perfil' not in ('todos',member)) or (coalesce(r.dados->>'email','')<>'' and lower(r.dados->>'email')<>lower(auth.jwt()->>'email'))) then return false;end if;
 if r.tipo in ('categoria','material','lote','movimento','conta','rede','checklist_modelo','qualificacao','frase','regra','leitura_aviso','acesso') and r.cliente_id is null then return true;end if;
 return direct_private.empresa_scope(case when r.tipo='cliente' then r.id else r.cliente_id end);
end;$$;
do $$declare t text;begin foreach t in array array['empresa_registros','empresa_extrato','empresa_anexos'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on public.%I from public,anon,authenticated',t);
 execute format('grant select on public.%I to authenticated',t);
 execute format('create trigger audit_empresa after insert or update or delete on public.%I for each row execute function direct_private.log_change()',t);
 execute format('create trigger empresa_revision after insert or update or delete on public.%I for each statement execute function direct_private.bump_revision()',t);
end loop;end;$$;
create policy empresa_read on public.empresa_registros for select to authenticated using(direct_private.empresa_visible(empresa_registros));
create policy empresa_bank_read on public.empresa_extrato for select to authenticated using((select direct_private.member_role()) in ('admin','financeiro'));
create policy empresa_attachment_read on public.empresa_anexos for select to authenticated using(exists(select 1 from public.empresa_registros r where r.id=registro_id));

create function direct_private.empresa_get(rid bigint,kind text default null) returns public.empresa_registros language plpgsql stable security definer set search_path='' as $$
declare r public.empresa_registros;begin select * into r from public.empresa_registros where id=rid;
 if r.id is null or (kind is not null and r.tipo<>kind) or not direct_private.empresa_visible(r) then raise exception 'Registro não disponível para seu perfil.' using errcode='42501';end if;return r;
end;$$;
create function direct_private.empresa_stock(rid bigint) returns bigint language plpgsql stable security definer set search_path='' as $$
declare r public.empresa_registros:=direct_private.empresa_get(rid,'material');begin
 return (r.dados->>'quantidade_inicial')::bigint+coalesce((select sum((dados->>'quantidade')::bigint*case when dados->>'tipo' in ('entrada','devolucao') then 1 else -1 end) from public.empresa_registros where tipo='movimento' and (dados->>'material_id')::bigint=rid),0);
end;$$;
create function direct_private.empresa_form_data(kind text,d jsonb) returns jsonb language sql immutable set search_path='' as $$select coalesce(jsonb_object_agg(k,v),'{}') from jsonb_each(d) x(k,v) where exists(select 1 from jsonb_array_elements(direct_private.empresa_contract()->'entities'->kind->'fields') a where a->>'name'=k)$$;
create function direct_private.empresa_validate(kind text,raw jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare spec jsonb:=direct_private.empresa_contract()->'entities'->kind;f jsonb;n text;t text;v jsonb;d jsonb:='{}';ref public.empresa_registros;target text;native boolean;test boolean;value text;
begin
 if spec is null or jsonb_typeof(raw)<>'object' then raise exception 'Formulário inválido.';end if;
 if exists(select 1 from jsonb_object_keys(raw) k where not exists(select 1 from jsonb_array_elements(spec->'fields') x where x->>'name'=k)) then raise exception 'Campos não reconhecidos.';end if;
 for f in select * from jsonb_array_elements(spec->'fields') loop
  n:=f->>'name';t:=f->>'type';v:=raw->n;value:=trim(raw->>n);
  if v is null or v='null'::jsonb or value='' or v='[]'::jsonb then if (f->>'required')::boolean then raise exception 'Preencha %.',f->>'label';end if;continue;end if;
  if t in ('integer','money','ref') then
   if jsonb_typeof(v)<>'number' or value !~ '^[0-9]+$' or value::numeric<coalesce((f->>'min')::numeric,1) or value::numeric>coalesce((f->>'max')::numeric,9007199254740991) then raise exception 'Valor inválido: %.',f->>'label';end if;
  elsif t in ('lines','ids','answers') then
   if jsonb_typeof(v)<>'array' or jsonb_array_length(v)>100 then raise exception 'Lista inválida: %.',f->>'label';end if;
   if t='lines' and exists(select 1 from jsonb_array_elements(v) x where jsonb_typeof(x)<>'string' or length(trim(x#>>'{}')) not between 1 and 500) then raise exception 'Perguntas inválidas.';end if;
   if t='ids' and (exists(select 1 from jsonb_array_elements(v) x where jsonb_typeof(x)<>'number' or (x#>>'{}') !~ '^[1-9][0-9]*$') or (select count(distinct x) from jsonb_array_elements(v)x)<>jsonb_array_length(v)) then raise exception 'IDs de diárias inválidos.';end if;
   if t='answers' and exists(select 1 from jsonb_array_elements(v) x where jsonb_typeof(x)<>'object' or jsonb_typeof(x->'pergunta')<>'string' or jsonb_typeof(x->'resposta')<>'string' or length(x->>'pergunta')>500 or length(x->>'resposta')>2000 or exists(select 1 from jsonb_object_keys(x) k where k not in ('pergunta','resposta'))) then raise exception 'Respostas inválidas.';end if;
  else
   if jsonb_typeof(v)<>'string' or length(value)>coalesce((f->>'maxLength')::int,case when t='textarea' then 4000 else 180 end) then raise exception 'Texto inválido: %.',f->>'label';end if;
   if t='choice' and not (f->'options' ? value) then raise exception 'Opção inválida: %.',f->>'label';end if;
   if t='date' then if value !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'Data inválida.';end if;perform value::date;end if;
   if t='datetime' then if value !~ '(Z|[+-][0-9]{2}:[0-9]{2})$' then raise exception 'Informe o fuso horário.';end if;perform value::timestamptz;end if;
   if t='time' and value !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then raise exception 'Horário inválido.';end if;
   if t='email' and value !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception 'E-mail inválido.';end if;
   v:=to_jsonb(value);
  end if;
  if t='ref' then
   target:=f->>'target';native:=target in ('pedido','diarista','loja','cobranca');
   if native then
    if target='pedido' then select exists(select 1 from public.pedidos where id=value::bigint) into test;
    elsif target='diarista' then select exists(select 1 from public.diaristas where id=value::bigint) into test;
    elsif target='cobranca' then if direct_private.empresa_role() not in ('admin','financeiro') then raise exception 'Sem permissão para cobranças.' using errcode='42501';end if;select exists(select 1 from public.cobrancas where id=value::bigint) into test;
    else select exists(select 1 from public.lojas where id=value::bigint) into test;end if;
    if not test then raise exception 'Vínculo não encontrado: %.',f->>'label';end if;
   else ref:=direct_private.empresa_get(value::bigint,target);end if;
  end if;
  d:=d||jsonb_build_object(n,v);
 end loop;
 if d ? 'inicio' and d ? 'fim' and d->>'inicio'>d->>'fim' then raise exception 'Confira início e fim.';end if;
 if d ? 'campanha_id' then ref:=direct_private.empresa_get((d->>'campanha_id')::bigint,'campanha');if d ? 'cliente_id' and d->>'cliente_id'<>ref.dados->>'cliente_id' then raise exception 'O cliente deve ser o contratante da campanha.';end if;d:=d||jsonb_build_object('cliente_id',ref.cliente_id);end if;
 return d;
end;$$;

create function direct_private.empresa_closing(d jsonb) returns jsonb language sql stable security definer set search_path='' as $$
 with scope as(select p.id from public.pedidos p where p.situacao<>'cancelado' and (not d ? 'pedido_id' or p.id=(d->>'pedido_id')::bigint) and (not d ? 'campanha_id' or exists(select 1 from public.empresa_registros v where v.tipo='vinculo' and v.pedido_id=p.id and v.campanha_id=(d->>'campanha_id')::bigint)) and (not d ? 'cliente_id' or exists(select 1 from public.empresa_registros v where v.tipo='vinculo' and v.pedido_id=p.id and v.cliente_id=(d->>'cliente_id')::bigint)))
 select jsonb_build_object('vagas_pendentes',(select coalesce(sum(greatest(0,(select count(*)*o.quantidade_diaristas from jsonb_array_elements(o.turnos) t where t->>'data'=d->>'data')-(select count(*) from public.pedido_escalas s where s.pedido_id=o.id and s.data=(d->>'data')::date and s.status not in ('falta','desistiu')))),0) from public.pedidos o join scope p on p.id=o.id),'presencas_pendentes',(select count(*) from public.pedido_escalas s join scope p on p.id=s.pedido_id where s.data=(d->>'data')::date and s.status='escalada'),
 'valores_incompletos',(select count(*) from public.diarias t join public.pedido_escalas s on s.id=t.pedido_escala_id join scope p on p.id=s.pedido_id where t.data=(d->>'data')::date and (t.valor_centavos is null or t.valor_recebido_centavos is null)),
 'ocorrencias_abertas',(select count(*) from public.ocorrencias o join scope p on p.id=o.pedido_id where o.estado='aberta'),
 'conferencias_loja',(select count(*) from public.loja_validacoes v join public.pedido_escalas s on s.id=v.escala_id join scope p on p.id=s.pedido_id where s.data=(d->>'data')::date and v.estado='pendente'))
$$;

create function public.direct_empresa_registro(p jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare member text:=direct_private.empresa_role();kind text:=p->>'tipo';spec jsonb:=direct_private.empresa_contract()->'entities'->kind;
 rid bigint:=nullif(p->>'id','')::bigint;r public.empresa_registros;old public.empresa_registros;d jsonb;state text;f jsonb;filtered jsonb;q jsonb;item jsonb;required boolean;applicable boolean;condition text[];balance bigint;held bigint;category public.empresa_registros;total bigint;cnt bigint;snapshot jsonb;
begin
 if kind is null then return to_jsonb(direct_private.empresa_get(rid));end if;
 if not coalesce(spec->'write' ? member,false) then raise exception 'Seu perfil não pode alterar esta informação.' using errcode='42501';end if;
 state:=coalesce(p->>'status',spec->'statuses'->>0);if not spec->'statuses' ? state then raise exception 'Situação inválida.';end if;
 if length(trim(coalesce(p->>'titulo',''))) not between 1 and 180 then raise exception 'Informe um título.';end if;
 if rid is not null then old:=direct_private.empresa_get(rid,kind);select * into old from public.empresa_registros where id=rid for update;if old.versao<>coalesce((p->>'versao')::bigint,0) then raise exception 'Outra pessoa alterou o registro. Atualize antes de salvar.';end if;
 else
  if coalesce(p->>'chave','') !~ '^[A-Za-z0-9:_-]{8,180}$' then raise exception 'Chave de envio inválida.';end if;
  perform pg_advisory_xact_lock(hashtextextended(p->>'chave',0));
  select * into r from public.empresa_registros where chave=p->>'chave';
 end if;
 d:=direct_private.empresa_validate(kind,coalesce(p->'dados','{}'));
 if not direct_private.empresa_scope((d->>'cliente_id')::bigint) and kind not in ('material','lote','movimento','categoria','conta','rede','checklist_modelo','qualificacao','frase','regra','leitura_aviso') then raise exception 'Cliente fora do seu escopo.' using errcode='42501';end if;
 if r.id is not null then filtered:=(select coalesce(jsonb_object_agg(k,v),'{}') from jsonb_each(r.dados) x(k,v) where exists(select 1 from jsonb_array_elements(spec->'fields') a where a->>'name'=k));if r.tipo<>kind or r.titulo<>trim(p->>'titulo') or r.status<>state or filtered<>direct_private.empresa_form_data(kind,d) then raise exception 'Envio já registrado com outros dados.';end if;return to_jsonb(direct_private.empresa_get(r.id));end if;
 if old.id is not null and ((kind='proposta' and old.status in ('enviada','aprovada','perdida','convertida')) or (kind='briefing' and old.status='publicado') or (kind='relatorio' and old.status='aprovado') or (kind='checklist' and old.status='concluido') or (kind='fechamento' and old.status='fechado') or kind in ('movimento','movimento_caixa','ciencia','leitura_aviso') or kind='orcamento' and old.status='aprovado' or kind='pagamento_revisao' and old.status='registrado') then
  filtered:=(select coalesce(jsonb_object_agg(k,v),'{}') from jsonb_each(old.dados) x(k,v) where exists(select 1 from jsonb_array_elements(spec->'fields') a where a->>'name'=k));
  if filtered<>direct_private.empresa_form_data(kind,d) or (state<>old.status and not(kind='proposta' and old.status='enviada' and state in ('aprovada','perdida'))) or old.titulo<>trim(p->>'titulo') then raise exception 'Esta versão está preservada. Crie uma nova versão.';end if;
 end if;
 if kind='movimento_caixa' and (d->>'valor_centavos')::bigint<=0 then raise exception 'Informe valor maior que zero.';end if;
 if kind='feedback' and (d->>'nota')::int not between 1 and 5 then raise exception 'A nota deve ficar entre 1 e 5.';end if;
 if kind='tarefa' and state='concluida' and length(coalesce(d->>'resolucao',''))<5 then raise exception 'Registre a resolução da tarefa.';end if;
 if kind='visita' and state='realizada' and coalesce(d->>'resultado','')='' then raise exception 'Registre o resultado da visita.';end if;
 if kind='fechamento' and state='fechado' then
  if (d->>'data')::date>(now() at time zone 'America/Fortaleza')::date then raise exception 'Feche somente um dia já iniciado.';end if;q:=direct_private.empresa_closing(d);d:=d||jsonb_build_object('pendencias',q);
  if exists(select 1 from jsonb_each_text(q) where value::bigint>0) and length(coalesce(d->>'justificativa',''))<8 then raise exception 'Resolva ou justifique as pendências antes de fechar.';end if;
 end if;
 if kind='ciencia' then r:=direct_private.empresa_get((d->>'briefing_id')::bigint,'briefing');if r.status<>'publicado' then raise exception 'Confirme uma versão publicada.';end if;end if;
 if kind='checklist' then
  r:=direct_private.empresa_get((d->>'modelo_id')::bigint,'checklist_modelo');
  if exists(select 1 from jsonb_array_elements(d->'respostas') a where not(r.dados->'perguntas' ? (a->>'pergunta'))) or (select count(distinct a->>'pergunta') from jsonb_array_elements(d->'respostas') a)<>jsonb_array_length(d->'respostas') then raise exception 'Respostas não correspondem ao modelo.';end if;
  if state='concluido' then for q in select * from jsonb_array_elements(r.dados->'perguntas') loop
   condition:=regexp_match(q#>>'{}','\[se (.+?)=(.+?)\]');applicable:=condition is null or exists(select 1 from jsonb_array_elements(d->'respostas') a where a->>'pergunta'=trim(condition[1]) and lower(trim(a->>'resposta'))=lower(trim(condition[2])));
   if left(q#>>'{}',1)='*' and applicable and not exists(select 1 from jsonb_array_elements(d->'respostas') a where a->>'pergunta'=q#>>'{}' and length(trim(a->>'resposta'))>0) then raise exception 'Responda as perguntas obrigatórias aplicáveis.';end if;
  end loop;end if;d:=d||jsonb_build_object('perguntas_snapshot',r.dados->'perguntas');
 end if;
 if kind='amostra' then balance:=(d->>'saldo_inicial')::bigint+(d->>'recebidas')::bigint-(d->>'distribuidas')::bigint-(d->>'perdas')::bigint-(d->>'devolvidas')::bigint;if balance<0 then raise exception 'Unidades distribuídas excedem o disponível.';end if;if coalesce((d->>'vendas')::bigint,0)>0 and coalesce(d->>'fonte_vendas','')='' then raise exception 'Informe a fonte das vendas observadas.';end if;d:=d||jsonb_build_object('saldo_final',balance);end if;
 if kind='movimento' and old.id is null then
  perform 1 from public.empresa_registros where id=(d->>'material_id')::bigint for update;
  if (d->>'quantidade')::bigint<=0 then raise exception 'Informe uma quantidade maior que zero.';end if;
  if d->>'tipo' not in ('entrada','devolucao') and (d->>'quantidade')::bigint>direct_private.empresa_stock((d->>'material_id')::bigint) then raise exception 'Saldo insuficiente do material.';end if;
  if d ? 'lote_id' then r:=direct_private.empresa_get((d->>'lote_id')::bigint,'lote');if r.dados->>'material_id'<>d->>'material_id' or (d->>'tipo' in ('entrega','consumo') and (r.dados->>'validade')::date<(d->>'data')::date) then raise exception 'Confira o material e a validade do lote.';end if;end if;
  if d->>'tipo'='devolucao' then select coalesce(sum((dados->>'quantidade')::bigint*case when dados->>'tipo'='entrega' then 1 when dados->>'tipo'='devolucao' then -1 else 0 end),0) into held from public.empresa_registros where tipo='movimento' and dados->>'material_id'=d->>'material_id' and dados->>'diarista_id' is not distinct from d->>'diarista_id' and dados->>'campanha_id' is not distinct from d->>'campanha_id';if (d->>'quantidade')::bigint>held then raise exception 'Devolução excede o material entregue.';end if;end if;
 end if;
 if kind='material' and old.id is not null and old.dados->>'quantidade_inicial'<>d->>'quantidade_inicial' and exists(select 1 from public.empresa_registros where tipo='movimento' and dados->>'material_id'=old.id::text) then raise exception 'Registre uma movimentação para corrigir o saldo.';end if;
 if kind='despesa' then
  category:=direct_private.empresa_get((d->>'categoria_id')::bigint,'categoria');if category.dados->>'tipo'<>'despesa' or (d->>'valor_centavos')::bigint<=0 then raise exception 'Confira categoria e valor da despesa.';end if;
  if state in ('aprovada','recusada','paga') and member not in ('admin','financeiro') then raise exception 'Somente Financeiro/Admin pode aprovar ou pagar despesas.' using errcode='42501';end if;
  if old.id is null and state not in ('rascunho','enviada') then raise exception 'Envie a despesa antes de aprovar.';end if;
  if old.id is not null then
   if not(case old.status when 'rascunho' then state in ('rascunho','enviada') when 'enviada' then state in ('enviada','aprovada','recusada') when 'recusada' then state in ('recusada','rascunho','enviada') when 'aprovada' then state in ('aprovada','paga') else state='paga' end) then raise exception 'Transição de despesa inválida.';end if;
   if old.status in ('aprovada','paga') and (old.titulo<>trim(p->>'titulo') or exists(select 1 from unnest(array['valor_centavos','categoria_id','data','vencimento','contraparte','pedido_id','cliente_id','campanha_id']) k where old.dados->k is distinct from d->k)) then raise exception 'Preserve a despesa aprovada; faça um ajuste financeiro separado.';end if;
  end if;
  if state='recusada' and length(coalesce(d->>'motivo',''))<5 then raise exception 'Explique a recusa.';end if;
  if state='paga' and (not d ? 'data_pagamento' or not d ? 'forma') then raise exception 'Informe data e forma de pagamento.';end if;
 end if;
 if kind='pagamento_revisao' then
  if state='registrado' then raise exception 'Use Registrar pagamento para concluir a conferência aprovada.';end if;
  select count(*),sum(valor_centavos),jsonb_agg(jsonb_build_object('id',id,'diarista_id',diarista_id,'valor_centavos',valor_centavos,'data_pagamento',data_pagamento) order by id) into cnt,total,snapshot from public.diarias where id in(select value::text::bigint from jsonb_array_elements(d->'diaria_ids')) and diarista_id=(d->>'diarista_id')::bigint and valor_centavos is not null and data_pagamento is null;
  if cnt<>jsonb_array_length(d->'diaria_ids') then raise exception 'Confira beneficiário, valores e diárias pendentes.';end if;
  if state='aprovado' and (old.id is null or old.status<>'preparado' or old.dados->'diarias_snapshot'<>snapshot) then raise exception 'Prepare novamente: as diárias mudaram ou não foram conferidas.';end if;
  d:=d||jsonb_build_object('valor_conferido_centavos',total,'diarias_snapshot',snapshot);
 end if;
 if kind='proposta' then
  if (d->>'dias')::int not between 1 and 90 or (d->>'pessoas')::int not between 1 and 100 or d->>'hora_inicio'>=d->>'hora_fim' then raise exception 'Confira dias, pessoas e horário.';end if;
  if old.id is null and state<>'rascunho' or state='convertida' then raise exception 'Prepare a proposta; use Gerar pedido para converter.';end if;
  d:=d||jsonb_build_object('receita_prevista_centavos',(d->>'dias')::bigint*(d->>'pessoas')::bigint*(d->>'valor_unitario_centavos')::bigint,'custo_previsto_centavos',(d->>'dias')::bigint*(d->>'pessoas')::bigint*(d->>'custo_unitario_centavos')::bigint+(d->>'extras_centavos')::bigint);
 end if;
 if kind='relatorio' and state='aprovado' and length(coalesce(d->>'aprovado_por',''))=0 then raise exception 'Registre quem revisou o relatório.';end if;
 if kind='leitura_aviso' then r:=direct_private.empresa_get((d->>'aviso_id')::bigint,'aviso');d:=d||jsonb_build_object('autor',auth.jwt()->>'email');select * into r from public.empresa_registros where tipo='leitura_aviso' and dados->>'aviso_id'=d->>'aviso_id' and autor=auth.jwt()->>'email' for update;if old.id is null and r.id is not null then return to_jsonb(r);end if;end if;
 if kind='acesso' and not exists(select 1 from public.direct_staff where lower(email)=lower(d->>'email') and active) then raise exception 'Escolha um funcionário ativo.';end if;
 if old.id is null then
  insert into public.empresa_registros(tipo,titulo,status,dados,cliente_id,campanha_id,pedido_id,diarista_id,loja_id,chave,autor) values(kind,trim(p->>'titulo'),state,d,(d->>'cliente_id')::bigint,(d->>'campanha_id')::bigint,(d->>'pedido_id')::bigint,(d->>'diarista_id')::bigint,(d->>'loja_id')::bigint,p->>'chave',auth.jwt()->>'email') returning * into r;
 else update public.empresa_registros set titulo=trim(p->>'titulo'),status=state,dados=d,cliente_id=(d->>'cliente_id')::bigint,campanha_id=(d->>'campanha_id')::bigint,pedido_id=(d->>'pedido_id')::bigint,diarista_id=(d->>'diarista_id')::bigint,loja_id=(d->>'loja_id')::bigint,versao=versao+1,atualizado_em=clock_timestamp() where id=old.id returning * into r;end if;
 if kind='despesa' and state in ('aprovada','paga') then
  insert into public.financeiro_lancamentos(tipo,descricao,categoria,contraparte,valor_centavos,vencimento,data_pagamento,forma_pagamento,observacoes,empresa_registro_id) values('despesa',r.titulo,category.titulo,d->>'contraparte',(d->>'valor_centavos')::bigint,(d->>'vencimento')::date,(d->>'data_pagamento')::date,coalesce(d->>'forma',''),d->>'justificativa',r.id) on conflict(empresa_registro_id) where empresa_registro_id is not null do nothing;
  if state='paga' then update public.financeiro_lancamentos set data_pagamento=(d->>'data_pagamento')::date,forma_pagamento=d->>'forma',atualizado_em=clock_timestamp() where empresa_registro_id=r.id;end if;
 end if;
 select * into r from public.empresa_registros where id=r.id;return to_jsonb(r);
end;$$;

create function public.direct_empresa_lista(p jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare member text:=direct_private.empresa_role();kind text:=p->>'tipo';page int:=greatest(1,coalesce((p->>'pagina')::int,1));size int:=least(50,greatest(1,coalesce((p->>'tamanho')::int,25)));total bigint;items jsonb;
begin
 if not coalesce(direct_private.empresa_contract()->'entities'->kind->'read' ? member,false) then raise exception 'Seu perfil não pode consultar esta área.' using errcode='42501';end if;
 with filtered as(select r.* from public.empresa_registros r where r.tipo=kind and direct_private.empresa_visible(r) and (coalesce(p->>'busca','')='' or r.titulo ilike '%'||(p->>'busca')||'%' or r.dados::text ilike '%'||(p->>'busca')||'%') and (coalesce(p->>'status','')='' or r.status=p->>'status') and (coalesce(p->>'cliente_id','')='' or r.cliente_id=(p->>'cliente_id')::bigint) and (coalesce(p->>'campanha_id','')='' or r.campanha_id=(p->>'campanha_id')::bigint) and (coalesce(p->>'pedido_id','')='' or r.pedido_id=(p->>'pedido_id')::bigint))
 select (select count(*) from filtered),(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select * from filtered order by id desc limit size offset (page-1)*size)x) into total,items;
 return jsonb_build_object('items',items,'total',total,'pagina',page,'tamanho',size);
end;$$;
create function public.direct_empresa_opcoes(p jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare member text:=direct_private.empresa_role();kind text:=p->>'tipo';search text:=coalesce(p->>'busca','');rid bigint:=nullif(p->>'id','')::bigint;result jsonb;
begin
 if kind='pedido' then select coalesce(jsonb_agg(to_jsonb(x)),'[]') into result from(select id,'Pedido #'||id||' · '||supermercado||' · '||unidade titulo from public.pedidos where (rid is null or id=rid) and (id::text||' '||supermercado||' '||unidade) ilike '%'||search||'%' order by id desc limit 100)x;
 elsif kind='diarista' then select coalesce(jsonb_agg(to_jsonb(x)),'[]') into result from(select id,nome titulo from public.diaristas where (rid is null or id=rid) and (nome||' '||cpf) ilike '%'||search||'%' order by id desc limit 100)x;
 elsif kind='cobranca' then if member not in ('admin','financeiro') then raise exception 'Sem permissão para cobranças.' using errcode='42501';end if;select coalesce(jsonb_agg(to_jsonb(x)),'[]') into result from(select id,'Cobrança #'||id||' · '||rede titulo from public.cobrancas where (rid is null or id=rid) and (id::text||' '||rede) ilike '%'||search||'%' order by id desc limit 100)x;
 elsif kind='loja' then select coalesce(jsonb_agg(to_jsonb(x)),'[]') into result from(select id,rede||' · '||nome titulo from public.lojas where (rid is null or id=rid) and (rede||' '||nome) ilike '%'||search||'%' order by id desc limit 100)x;
 else
  if not coalesce(direct_private.empresa_contract()->'entities'->kind->'read' ? member,false) then raise exception 'Tipo de busca não permitido.' using errcode='42501';end if;
  select coalesce(jsonb_agg(to_jsonb(x)),'[]') into result from(select id,titulo,status from public.empresa_registros r where tipo=kind and direct_private.empresa_visible(r) and (rid is null or id=rid) and (rid is not null or status not in ('arquivado','cancelada')) and titulo ilike '%'||search||'%' order by titulo limit 100)x;
 end if;return result;
end;$$;
create function public.direct_empresa_saldo(p jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$begin perform direct_private.empresa_role();return jsonb_build_object('saldo',direct_private.empresa_stock((p->>'material_id')::bigint));end;$$;
