create table public.pedido_escalas (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete restrict,
  diarista_id bigint not null references public.diaristas(id) on delete restrict,
  data date not null,
  status text not null default 'escalada' check (status in ('escalada', 'presente', 'falta')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (pedido_id, data, diarista_id)
);
create index idx_pedido_escalas_pedido_data on public.pedido_escalas (pedido_id, data);
create index idx_pedido_escalas_diarista on public.pedido_escalas (diarista_id);
alter table public.diarias add column pedido_escala_id bigint unique references public.pedido_escalas(id) on delete restrict;
alter table public.pedido_escalas enable row level security;
revoke all on public.pedido_escalas from anon;
grant select, insert, update, delete on public.pedido_escalas to authenticated;
grant usage, select on sequence public.pedido_escalas_id_seq to authenticated;
create policy "admin manages pedido escalas" on public.pedido_escalas for all to authenticated
  using ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))))
  with check ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))));

create function public.direct_validate_pedido_escala()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare
  v_order public.pedidos%rowtype;
begin
  if tg_op = 'UPDATE' then
    if (new.pedido_id, new.diarista_id, new.data) is distinct from (old.pedido_id, old.diarista_id, old.data) then
      raise exception 'A diarista e a data da escala não podem ser alteradas. Exclua a escala pendente e crie outra.';
    end if;
    if new.status = old.status then
      return new;
    end if;
    if old.status = 'presente' and new.status <> 'presente' and exists (
      select 1 from public.diarias where pedido_escala_id = old.id and data_pagamento is not null
    ) then
      raise exception 'A diária já foi paga. Corrija o pagamento antes de alterar a presença.';
    end if;
  elsif new.status <> 'escalada' then
    raise exception 'Uma nova escala deve começar como escalada.';
  end if;

  select * into v_order from public.pedidos where id = new.pedido_id for update;
  if not found then raise exception 'Pedido não encontrado.'; end if;
  if not exists (select 1 from jsonb_array_elements(v_order.turnos) t where t->>'data' = new.data::text) then
    raise exception 'A data escolhida não consta no pedido.';
  end if;
  if tg_op = 'INSERT' and not exists (
    select 1 from public.diaristas where id = new.diarista_id and not bloqueada
  ) then raise exception 'Escolha uma diarista cadastrada e não bloqueada.'; end if;
  if new.status <> 'falta' and (tg_op = 'INSERT' or old.status = 'falta') and (
    select count(*) from public.pedido_escalas
    where pedido_id = new.pedido_id and data = new.data and status <> 'falta'
  ) >= v_order.quantidade_diaristas then
    raise exception 'A quantidade de diaristas deste dia já foi preenchida.';
  end if;
  new.atualizado_em := now();
  return new;
end;
$$;
create trigger validate_pedido_escala before insert or update on public.pedido_escalas
for each row execute function public.direct_validate_pedido_escala();

create function public.direct_sync_pedido_presenca()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare
  v_order public.pedidos%rowtype;
begin
  if new.status = old.status then return null; end if;
  if new.status = 'presente' then
    select * into v_order from public.pedidos where id = new.pedido_id;
    insert into public.diarias (diarista_id, data, local, setor, observacoes, pedido_escala_id)
    values (new.diarista_id, new.data,
      v_order.supermercado || case when v_order.unidade = '' then '' else ' · ' || v_order.unidade end,
      v_order.setor, 'Presença no pedido #' || new.pedido_id, new.id);
  elsif old.status = 'presente' then
    delete from public.diarias where pedido_escala_id = new.id;
  end if;
  return null;
end;
$$;
create trigger sync_pedido_presenca after update of status on public.pedido_escalas
for each row execute function public.direct_sync_pedido_presenca();

create function public.direct_guard_pedido_history()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if tg_table_name = 'pedido_escalas' then
    if old.status <> 'escalada' then
      raise exception 'Presenças e faltas registradas não podem ser excluídas. Corrija a situação da escala.';
    end if;
  elsif tg_table_name = 'diarias' then
    if old.pedido_escala_id is not null and exists (
      select 1 from public.pedido_escalas where id = old.pedido_escala_id and status = 'presente'
    ) then raise exception 'Esta diária está vinculada a uma presença. Corrija a presença no pedido.'; end if;
  elsif tg_table_name = 'pedidos' and exists (
    select 1 from public.pedido_escalas where pedido_id = old.id
  ) then
    if tg_op = 'DELETE' or
      (new.supermercado, new.unidade, new.setor, new.quantidade_diaristas, new.turnos)
      is distinct from (old.supermercado, old.unidade, old.setor, old.quantidade_diaristas, old.turnos) then
      raise exception 'Este pedido já possui escalas. Preserve a equipe e as datas registradas.';
    end if;
  end if;
  if tg_op = 'UPDATE' then return new; end if;
  return old;
end;
$$;
create trigger guard_pedido_escala_delete before delete on public.pedido_escalas
for each row execute function public.direct_guard_pedido_history();
create trigger guard_pedido_diaria_delete before delete on public.diarias
for each row execute function public.direct_guard_pedido_history();
create trigger guard_pedido_change before update or delete on public.pedidos
for each row execute function public.direct_guard_pedido_history();
revoke execute on function public.direct_validate_pedido_escala(), public.direct_sync_pedido_presenca(), public.direct_guard_pedido_history() from public, anon, authenticated;
