alter table public.lojas add column if not exists responsavel text not null default '' check(length(responsavel)<=180);
alter table public.lojas add column if not exists telefone_contato text not null default '' check(length(telefone_contato)<=180);
alter table public.lojas add column if not exists entrada text not null default '' check(length(entrada)<=180);
alter table public.lojas add column if not exists apresentacao text not null default '' check(length(apresentacao)<=180);
alter table public.lojas add column if not exists uniforme text not null default '' check(length(uniforme)<=180);
alter table public.lojas add column if not exists orientacoes text not null default '' check(length(orientacoes)<=1000);
create table public.pedido_modelos (
 id bigint generated by default as identity primary key,
 nome text not null check(length(trim(nome)) between 1 and 120),
 dados jsonb not null check(jsonb_typeof(dados)='object'),
 criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create unique index pedido_modelos_nome_ci on public.pedido_modelos(lower(trim(nome)));
alter table public.pedido_modelos enable row level security;
revoke all on public.pedido_modelos from public,anon,authenticated;
grant select,insert,update,delete on public.pedido_modelos to authenticated;
grant usage,select on sequence public.pedido_modelos_id_seq to authenticated;
create policy modelos_select on public.pedido_modelos for select to authenticated using((select direct_private.member_role()) in ('admin','operacao'));
create policy modelos_insert on public.pedido_modelos for insert to authenticated with check((select direct_private.member_role()) in ('admin','operacao'));
create policy modelos_update on public.pedido_modelos for update to authenticated using((select direct_private.member_role()) in ('admin','operacao')) with check((select direct_private.member_role()) in ('admin','operacao'));
create policy modelos_delete on public.pedido_modelos for delete to authenticated using((select direct_private.member_role()) in ('admin','operacao'));
create function direct_private.validate_pedido_modelo() returns trigger language plpgsql security invoker set search_path='' as $$
declare t jsonb; n integer;
begin
 new.nome:=trim(new.nome);
 if jsonb_typeof(new.dados->'turnos') is distinct from 'array' then raise exception 'Modelo sem datas.';end if;
 if jsonb_array_length(new.dados->'turnos') not between 1 and 90 then raise exception 'Informe de 1 a 90 datas.';end if;
 if length(trim(coalesce(new.dados->>'setor',''))) not between 1 and 80 then raise exception 'Setor inválido.';end if;
 if not exists(select 1 from public.lojas where lower(rede)=lower(new.dados->>'supermercado') and lower(nome)=lower(new.dados->>'unidade')) then raise exception 'Escolha uma loja cadastrada.';end if;
 n:=(new.dados->>'quantidade_diaristas')::integer;if n is null or n not between 1 and 100 then raise exception 'Quantidade inválida.';end if;
 for t in select value from jsonb_array_elements(new.dados->'turnos') loop
  if jsonb_typeof(t)<>'object' or coalesce(t->>'data','') !~ '^\d{4}-\d{2}-\d{2}$' or (t->>'data')::date::text<>t->>'data'
   or coalesce(t->>'inicio','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or coalesce(t->>'fim','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or t->>'inicio'>=t->>'fim' then raise exception 'Data ou horário inválido.';end if;
 end loop;
 if (select count(distinct x.value->>'data') from jsonb_array_elements(new.dados->'turnos') as x(value))<>jsonb_array_length(new.dados->'turnos') then raise exception 'Datas repetidas.';end if;
 if length(coalesce(new.dados->>'observacoes',''))>500 or length(coalesce(new.dados->>'contato',''))>180 then raise exception 'Texto muito longo.';end if;
 new.dados:=jsonb_build_object('supermercado',new.dados->>'supermercado','unidade',new.dados->>'unidade','setor',new.dados->>'setor','quantidade_diaristas',n,'contato',coalesce(new.dados->>'contato',''),'observacoes',coalesce(new.dados->>'observacoes',''),'situacao','novo','turnos',new.dados->'turnos');
 new.atualizado_em:=now();return new;
end;$$;
revoke all on function direct_private.validate_pedido_modelo() from public,anon,authenticated;
create trigger validate_pedido_modelo before insert or update on public.pedido_modelos for each row execute function direct_private.validate_pedido_modelo();
create trigger audit_pedido_modelos after insert or update or delete on public.pedido_modelos for each row execute function direct_private.log_change();

-- A STABLE function shares the caller's MVCC snapshot for every table.
-- Private helper is not exposed; the public wrapper verifies a real admin session.
create or replace function direct_private.backup_snapshot() returns jsonb
language sql stable security invoker set search_path='' as $$
 with data as (select jsonb_build_object(
    'pedido_modelos', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.pedido_modelos t),
    'diaristas', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.diaristas t),
    'diarias', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.diarias t),
    'pedidos', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.pedidos t),
    'pedido_escalas', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.pedido_escalas t),
    'lojas', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.lojas t),
    'financeiro_lancamentos', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.financeiro_lancamentos t),
    'tarifas_redes', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.tarifas_redes t),
    'tarifas_setores', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.tarifas_setores t),
    'leituras_pendentes', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.leituras_pendentes t),
    'direct_staff', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.direct_staff t),
    'direct_auditoria', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.direct_auditoria t),
    'cobrancas', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.cobrancas t),
    'cobranca_itens', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.cobranca_itens t),
    'cobranca_recebimentos', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.cobranca_recebimentos t),
    'pagamento_lotes', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.pagamento_lotes t),
    'custos_extras', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.custos_extras t),
    'contratos', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.contratos t),
    'ocorrencias', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.ocorrencias t),
    'direct_admins', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.direct_admins t),
    'portal_cadastros', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from public.portal_cadastros t),
    'portal_config', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from direct_private.portal_config t),
    'portal_convites', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from direct_private.portal_convites t),
    'portal_registros', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from direct_private.portal_registros t),
    'portal_vagas_link', (select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text), '[]'::jsonb) from direct_private.portal_vagas_link t)
 ) tables)
 select jsonb_build_object('format','direct-data-v6','exportedAt',now(),
   'tables',data.tables,'snapshot',jsonb_build_object('consistent',true,
     'counts',(select jsonb_object_agg(key,jsonb_array_length(value)) from jsonb_each(data.tables))))
 from data;
$$;
