-- Motivo e autoria de faltas; substituição vinculada automaticamente à vaga do dia.
alter table public.pedido_escalas
  add column falta_motivo text,
  add column falta_confirmada_por text,
  add column falta_confirmada_em timestamptz,
  add column substituida_por_escala_id bigint references public.pedido_escalas(id) on delete set null;
create unique index pedido_escalas_substituta_unica
  on public.pedido_escalas(substituida_por_escala_id)
  where substituida_por_escala_id is not null;

create function direct_private.record_absence()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.status = 'falta' and (tg_op = 'INSERT' or old.status <> 'falta') then
    if length(btrim(coalesce(new.falta_motivo, ''))) < 5 or length(new.falta_motivo) > 300 then
      raise exception 'Informe o motivo da falta com 5 a 300 caracteres.';
    end if;
    new.falta_confirmada_por := (select auth.jwt() ->> 'email');
    new.falta_confirmada_em := now();
  elsif tg_op = 'UPDATE' and old.status = 'falta' and new.status <> 'falta' then
    new.falta_motivo := null;
    new.falta_confirmada_por := null;
    new.falta_confirmada_em := null;
    new.substituida_por_escala_id := null;
  elsif tg_op = 'UPDATE' and old.status = 'falta' and new.status = 'falta' then
    if (new.falta_motivo, new.falta_confirmada_por, new.falta_confirmada_em, new.substituida_por_escala_id)
       is distinct from (old.falta_motivo, old.falta_confirmada_por, old.falta_confirmada_em, old.substituida_por_escala_id)
       and new.substituida_por_escala_id is not distinct from old.substituida_por_escala_id then
      raise exception 'Histórico da falta não pode ser alterado diretamente.';
    end if;
  end if;
  return new;
end;
$$;
create trigger record_absence before insert or update on public.pedido_escalas
  for each row execute function direct_private.record_absence();

create function direct_private.link_substitute()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_absence bigint;
begin
  select id into v_absence from public.pedido_escalas
    where pedido_id = new.pedido_id and data = new.data and status = 'falta'
      and substituida_por_escala_id is null and id <> new.id
    order by id limit 1 for update;
  if v_absence is not null then
    update public.pedido_escalas set substituida_por_escala_id = new.id where id = v_absence;
  end if;
  return null;
end;
$$;
create trigger link_substitute after insert on public.pedido_escalas
  for each row execute function direct_private.link_substitute();
revoke execute on function direct_private.record_absence(), direct_private.link_substitute() from public, anon, authenticated;

-- Custos estimados por diária, sem presumir tarifa ou despesa da empresa.
create table public.custos_extras (
  id bigint generated by default as identity unique,
  rede text primary key references public.tarifas_redes(rede) on update cascade,
  transporte_centavos bigint not null default 0 check (transporte_centavos between 0 and 10000000),
  taxas_centavos bigint not null default 0 check (taxas_centavos between 0 and 10000000),
  outros_centavos bigint not null default 0 check (outros_centavos between 0 and 10000000),
  atualizado_em timestamptz not null default now()
);
insert into public.custos_extras(rede) select rede from public.tarifas_redes;
alter table public.custos_extras enable row level security;
revoke all on public.custos_extras from anon, authenticated;
grant select, insert, update on public.custos_extras to authenticated;
grant usage, select on sequence public.custos_extras_id_seq to authenticated;
create policy "extra costs select" on public.custos_extras for select to authenticated
  using ((select direct_private.member_role()) in ('admin','financeiro'));
create policy "extra costs insert" on public.custos_extras for insert to authenticated
  with check ((select direct_private.member_role()) in ('admin','financeiro'));
create policy "extra costs update" on public.custos_extras for update to authenticated
  using ((select direct_private.member_role()) in ('admin','financeiro'))
  with check ((select direct_private.member_role()) in ('admin','financeiro'));
create trigger audit_extra_costs after insert or update on public.custos_extras
  for each row execute function direct_private.log_change();
