alter table public.diaristas add column telefone text not null default '' check (telefone='' or telefone ~ '^[0-9]{10,13}$'),
 add column reserva boolean not null default false, add column disponibilidade_confirmada_em timestamptz;
alter table public.pedidos add column chave_operacao uuid unique;
alter table public.pedido_escalas
 add column confirmacao text not null default 'aguardando' check(confirmacao in ('aguardando','confirmou','recusou')),
 add column confirmacao_em timestamptz, add column confirmacao_por text,
 add column chegada_em timestamptz, add column saida_em timestamptz,
 add column loja_validacao text not null default 'pendente' check(loja_validacao in ('pendente','validado','divergencia')),
 add column loja_responsavel text not null default '' check(length(loja_responsavel)<=120),
 add column loja_observacao text not null default '' check(length(loja_observacao)<=1000),
 add column loja_validada_em timestamptz, add column loja_validada_por text;
alter table public.cobrancas add column conferencia text not null default 'pendente' check(conferencia in ('pendente','conferida','contestada')),
 add column conferencia_responsavel text not null default '' check(length(conferencia_responsavel)<=120),
 add column conferencia_motivo text not null default '' check(length(conferencia_motivo)<=1000), add column conferencia_em timestamptz;
create table public.contratos (
 id bigint generated by default as identity primary key, rede text not null references public.tarifas_redes(rede),
 loja text not null default '' check(length(loja)<=180), setor text not null default '' check(length(setor)<=80),
 inicio date not null, fim date check(fim>=inicio),
 valor_recebido_centavos bigint check(valor_recebido_centavos between 1 and 100000000),
 valor_pago_centavos bigint check(valor_pago_centavos between 1 and 100000000),
 prazo_dias integer not null default 30 check(prazo_dias between 0 and 365),
 responsavel text not null default '' check(length(responsavel)<=120), contato text not null default '' check(length(contato)<=120),
 regras text not null default '' check(length(regras)<=2000),
 versao_anterior_id bigint references public.contratos(id) on delete restrict, criado_em timestamptz not null default now());
create index contratos_abrangencia on public.contratos(rede,loja,setor,inicio);
create index contratos_anterior on public.contratos(versao_anterior_id);
alter table public.diarias add column contrato_id bigint references public.contratos(id) on delete restrict;
create index diarias_contrato on public.diarias(contrato_id);
create table public.ocorrencias (
 id bigint generated by default as identity primary key, pedido_id bigint not null references public.pedidos(id) on delete restrict,
 escala_id bigint references public.pedido_escalas(id) on delete restrict,
 tipo text not null check(tipo in ('atraso','troca_setor','saida_antecipada','reclamacao','elogio','outro')),
 descricao text not null check(length(btrim(descricao)) between 5 and 1000),
 estado text not null default 'aberta' check(estado in ('aberta','resolvida')),
 resolucao text not null default '' check(length(resolucao)<=1000), autor text not null default '', criado_em timestamptz not null default now(), resolvida_em timestamptz);
create index ocorrencias_pedido on public.ocorrencias(pedido_id); create index ocorrencias_escala on public.ocorrencias(escala_id);
alter table public.contratos enable row level security; alter table public.ocorrencias enable row level security;
revoke all on public.contratos,public.ocorrencias from anon,authenticated;
grant select on public.contratos to authenticated;
grant select,insert,update on public.ocorrencias to authenticated;
grant usage,select on sequence public.ocorrencias_id_seq to authenticated;
create policy contracts_read on public.contratos for select to authenticated using((select direct_private.member_role()) in ('admin','financeiro'));
create policy occurrences_read on public.ocorrencias for select to authenticated using((select direct_private.member_role()) in ('admin','operacao','financeiro'));
create policy occurrences_insert on public.ocorrencias for insert to authenticated with check((select direct_private.member_role()) in ('admin','operacao'));
create policy occurrences_update on public.ocorrencias for update to authenticated using((select direct_private.member_role()) in ('admin','operacao')) with check((select direct_private.member_role()) in ('admin','operacao'));
create trigger audit_contracts after insert or update on public.contratos for each row execute function direct_private.log_change();
create trigger audit_occurrences after insert or update on public.ocorrencias for each row execute function direct_private.log_change();

create function direct_private.guard_operation_metadata() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if tg_op='INSERT' then
  new.confirmacao := 'aguardando'; new.confirmacao_em:=null; new.confirmacao_por:=null;
  new.loja_validacao:='pendente'; new.loja_responsavel:=''; new.loja_observacao:=''; new.chegada_em:=null; new.saida_em:=null;
  new.loja_validada_em:=null; new.loja_validada_por:=null;
 else
  if (new.confirmacao,new.confirmacao_em,new.confirmacao_por) is distinct from (old.confirmacao,old.confirmacao_em,old.confirmacao_por) then
   if new.status<>'escalada' then raise exception 'Confirmação disponível apenas antes da presença/falta.'; end if;
   new.confirmacao_em:=now(); new.confirmacao_por:=(select auth.jwt()->>'email');
  end if;
  if (new.chegada_em,new.saida_em,new.loja_validacao,new.loja_responsavel,new.loja_observacao,new.loja_validada_em,new.loja_validada_por)
   is distinct from (old.chegada_em,old.saida_em,old.loja_validacao,old.loja_responsavel,old.loja_observacao,old.loja_validada_em,old.loja_validada_por) then
   if new.status<>'presente' or new.loja_validacao='pendente' or length(btrim(new.loja_responsavel))<2 then raise exception 'Confirme a presença e informe o responsável da loja.'; end if;
   if new.loja_validacao='divergencia' and length(btrim(new.loja_observacao))<5 then raise exception 'Descreva a divergência.'; end if;
   if (new.chegada_em is not null and ((new.chegada_em at time zone 'America/Fortaleza')::date<>new.data or new.chegada_em>now()+interval '1 minute'))
    or (new.saida_em is not null and ((new.saida_em at time zone 'America/Fortaleza')::date<>new.data or new.saida_em>now()+interval '1 minute' or new.chegada_em is null or new.saida_em<new.chegada_em)) then raise exception 'Confira os horários efetivos do dia, sem horários futuros.'; end if;
   new.loja_validada_em:=now(); new.loja_validada_por:=(select auth.jwt()->>'email');
  end if;
  if old.status='presente' and new.status<>'presente' then
   new.loja_validacao:='pendente'; new.loja_validada_em:=null; new.loja_validada_por:=null; new.chegada_em:=null; new.saida_em:=null; new.loja_responsavel:=''; new.loja_observacao:='';
  end if;
 end if;
 return new;
end $$;
create trigger guard_operation_metadata before insert or update on public.pedido_escalas for each row execute function direct_private.guard_operation_metadata();
create function direct_private.guard_occurrence() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if new.escala_id is not null and not exists(select 1 from public.pedido_escalas where id=new.escala_id and pedido_id=new.pedido_id) then raise exception 'Escala não pertence ao pedido.'; end if;
 if tg_op='INSERT' then new.autor:=(select auth.jwt()->>'email'); new.criado_em:=now(); new.estado:='aberta'; new.resolucao:=''; new.resolvida_em:=null;
 else
  if (new.pedido_id,new.escala_id,new.tipo,new.descricao,new.autor,new.criado_em) is distinct from (old.pedido_id,old.escala_id,old.tipo,old.descricao,old.autor,old.criado_em) then raise exception 'Preserve a ocorrência original. Registre a resolução.'; end if;
  if old.estado='resolvida' or new.estado<>'resolvida' or length(btrim(new.resolucao))<5 then raise exception 'Informe a resolução da ocorrência aberta.'; end if;
  new.resolvida_em:=now();
 end if;
 return new;
end $$;
create trigger guard_occurrence before insert or update on public.ocorrencias for each row execute function direct_private.guard_occurrence();

create function public.direct_create_contract(p jsonb) returns public.contratos language plpgsql security definer set search_path='' as $$
declare v public.contratos; old public.contratos; start_date date:=(p->>'inicio')::date; end_date date:=nullif(p->>'fim','')::date;
begin
 if auth.uid() is null or coalesce(direct_private.member_role(),'') not in ('admin','financeiro') then raise exception 'Sem permissão para contratos.'; end if;
 if start_date is null or (end_date is not null and end_date<start_date) then raise exception 'Confira a vigência.'; end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext((p->>'rede')||'|'||lower(coalesce(p->>'loja',''))||'|'||lower(coalesce(p->>'setor',''))));
 if coalesce(p->>'loja','')<>'' and not exists(select 1 from public.lojas where lower(rede)=lower(p->>'rede') and lower(nome)=lower(p->>'loja')) then raise exception 'Loja não cadastrada nessa rede.'; end if;
 if coalesce(p->>'setor','')<>'' and not exists(select 1 from public.tarifas_setores where lower(setor)=lower(p->>'setor')) then raise exception 'Setor não cadastrado nas configurações.'; end if;
 if nullif(p->>'versao_anterior_id','') is not null then
  select * into old from public.contratos where id=(p->>'versao_anterior_id')::bigint for update;
  if old.id is null or (old.rede,old.loja,old.setor) is distinct from (p->>'rede',coalesce(p->>'loja',''),coalesce(p->>'setor','')) or start_date<=old.inicio then raise exception 'Nova versão deve manter abrangência e começar depois da anterior.'; end if;
  if old.fim is null or old.fim>=start_date then update public.contratos set fim=start_date-1 where id=old.id; end if;
 end if;
 if exists(select 1 from public.contratos where rede=p->>'rede' and lower(loja)=lower(coalesce(p->>'loja','')) and lower(setor)=lower(coalesce(p->>'setor','')) and inicio<=coalesce(end_date,'9999-12-31'::date) and coalesce(fim,'9999-12-31'::date)>=start_date) then raise exception 'Há contrato sobreposto. Use Nova versão.'; end if;
 insert into public.contratos(rede,loja,setor,inicio,fim,valor_recebido_centavos,valor_pago_centavos,prazo_dias,responsavel,contato,regras,versao_anterior_id)
 values(p->>'rede',coalesce(p->>'loja',''),coalesce(p->>'setor',''),start_date,end_date,nullif(p->>'valor_recebido_centavos','')::bigint,nullif(p->>'valor_pago_centavos','')::bigint,coalesce((p->>'prazo_dias')::int,30),coalesce(p->>'responsavel',''),coalesce(p->>'contato',''),coalesce(p->>'regras',''),old.id) returning * into v;
 return v;
end $$;
revoke execute on function public.direct_create_contract(jsonb) from public,anon; grant execute on function public.direct_create_contract(jsonb) to authenticated;

create function direct_private.snapshot_contract() returns trigger language plpgsql security definer set search_path='' as $$
declare c public.contratos;
begin
 new.contrato_id:=null;
 if new.pedido_escala_id is not null then
  select ct.* into c from public.contratos ct join public.pedido_escalas s on s.id=new.pedido_escala_id join public.pedidos p on p.id=s.pedido_id
   where lower(ct.rede)=lower(p.supermercado) and (ct.loja='' or lower(ct.loja)=lower(p.unidade)) and (ct.setor='' or lower(ct.setor)=lower(p.setor)) and ct.inicio<=s.data and (ct.fim is null or ct.fim>=s.data)
   order by (case when ct.loja<>'' then 2 else 0 end+case when ct.setor<>'' then 1 else 0 end) desc,ct.inicio desc,ct.id desc limit 1;
  if c.id is not null then new.contrato_id:=c.id; new.valor_centavos:=coalesce(c.valor_pago_centavos,new.valor_centavos); new.valor_recebido_centavos:=coalesce(c.valor_recebido_centavos,new.valor_recebido_centavos); if new.valor_centavos is not null then new.vencimento_pagamento:=new.data; end if; end if;
 else new.contrato_id:=null;
 end if;
 return new;
end $$;
create trigger snapshot_contract before insert on public.diarias for each row execute function direct_private.snapshot_contract();
revoke execute on function direct_private.guard_operation_metadata(),direct_private.guard_occurrence(),direct_private.snapshot_contract() from public,anon,authenticated;

create function direct_private.guard_invoice_review() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if (new.conferencia,new.conferencia_responsavel,new.conferencia_motivo,new.conferencia_em) is distinct from (old.conferencia,old.conferencia_responsavel,old.conferencia_motivo,old.conferencia_em) then
  if new.status='cancelada' or new.conferencia='pendente' or length(btrim(new.conferencia_responsavel))<2 or (new.conferencia='contestada' and length(btrim(new.conferencia_motivo))<5) then raise exception 'Informe responsável e motivo da contestação.'; end if; new.conferencia_em:=now();
 end if;
 return new;
end $$;
create trigger guard_invoice_review before update on public.cobrancas for each row execute function direct_private.guard_invoice_review();
revoke execute on function direct_private.guard_invoice_review() from public,anon,authenticated;
create function public.direct_review_invoice(p_id bigint,p jsonb) returns void language plpgsql security definer set search_path='' as $$
begin
 if auth.uid() is null or coalesce(direct_private.member_role(),'') not in ('admin','financeiro') then raise exception 'Sem permissão para conferir cobrança.'; end if;
 if p->>'conferencia' not in ('conferida','contestada') then raise exception 'Selecione conferida ou contestada.'; end if;
 update public.cobrancas set conferencia=p->>'conferencia',conferencia_responsavel=coalesce(p->>'responsavel',''),conferencia_motivo=coalesce(p->>'motivo','') where id=p_id and status<>'cancelada';
 if not found then raise exception 'Cobrança não encontrada ou cancelada.'; end if;
end $$;
revoke execute on function public.direct_review_invoice(bigint,jsonb) from public,anon; grant execute on function public.direct_review_invoice(bigint,jsonb) to authenticated;

-- Horário da confirmação de disponibilidade pertence ao servidor.
create function direct_private.guard_worker_contact() returns trigger language plpgsql set search_path='' as $$
begin
 if tg_op='INSERT' then new.disponibilidade_confirmada_em:=null;
 elsif new.disponibilidade_confirmada_em is distinct from old.disponibilidade_confirmada_em then new.disponibilidade_confirmada_em:=now(); end if;
 return new;
end $$;
create trigger guard_worker_contact before insert or update on public.diaristas for each row execute function direct_private.guard_worker_contact();
create function direct_private.guard_contract_snapshot() returns trigger language plpgsql set search_path='' as $$
begin
 if new.contrato_id is distinct from old.contrato_id then raise exception 'O contrato de origem da diária é um registro histórico e não pode ser trocado.'; end if;
 return new;
end $$;
create trigger guard_contract_snapshot before update on public.diarias for each row execute function direct_private.guard_contract_snapshot();
revoke execute on function direct_private.guard_worker_contact(),direct_private.guard_contract_snapshot() from public,anon,authenticated;
