create function direct_private.normal_text(p text) returns text language sql immutable parallel safe set search_path='' as $$select lower(translate(coalesce(p,''),'áàãâäéèêëíìîïóòõôöúùûüçÁÀÃÂÄÉÈÊËÍÌÎÏÓÒÕÔÖÚÙÛÜÇ','aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC'));$$;
revoke all on function direct_private.normal_text(text) from public,anon,authenticated;
create function public.direct_search(p_query text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare member text:=direct_private.member_role(); q text:=direct_private.normal_text(trim(p_query));result jsonb;begin
if auth.uid() is null or coalesce(member,'') not in ('admin','operacao','financeiro','consulta') then raise exception 'Acesso não permitido.' using errcode='42501';end if;
if q ~ '^[0-9. /-]+$' then q:=regexp_replace(q,'[^0-9]','','g');end if;
if length(q)<2 then return '[]'::jsonb;end if;if length(q)>120 then raise exception 'Busca muito longa.';end if;
select coalesce(jsonb_agg(to_jsonb(r)),'[]'::jsonb) into result from (
 select * from (
 select 'diarista' kind,w.id,w.nome title,coalesce(w.bairro,'') detail,case when w.bloqueada then 'Bloqueado' else 'Cadastro' end status from public.diaristas w where member<>'consulta' and position(q in direct_private.normal_text(w.nome||' '||w.cpf))>0
 union all select 'loja',l.id,l.rede||' · '||l.nome,l.endereco,'Loja' from public.lojas l where position(q in direct_private.normal_text(l.rede||' '||l.nome||' '||coalesce(l.endereco,'')||' '||coalesce(l.bairro,'')||' '||coalesce(l.cidade,'')))>0
 union all select 'pedido',o.id,'Pedido #'||o.id||' · '||o.supermercado,o.unidade||' · '||o.setor,o.situacao from public.pedidos o where position(q in direct_private.normal_text(o.id::text||' '||o.supermercado||' '||o.unidade||' '||o.setor))>0 or exists(select 1 from public.pedido_escalas s join public.diaristas w on w.id=s.diarista_id where s.pedido_id=o.id and position(q in direct_private.normal_text(w.nome))>0)
 ) entries order by case when direct_private.normal_text(title) like q||'%' then 0 else 1 end,kind,title,id limit 30
)r;return result;end;$$;
revoke all on function public.direct_search(text) from public,anon,authenticated;
grant execute on function public.direct_search(text) to authenticated;
create function direct_private.pending_area(p_key text) returns text language sql immutable set search_path='' as $$
select case when p_key ~ '^pedido:[0-9]+$' then 'operacao' when p_key ~ '^(cadastro|leitura):[0-9]+$' then 'cadastros' when p_key ~ '^(finance:[a-z]+|pagamentos|faturar-pedido|cobranca|contrato):[a-zA-Z0-9_-]+$' then 'financeiro' when p_key ~ '^ocorrencia:[0-9]+$' then 'operacao' end;$$;
revoke all on function direct_private.pending_area(text) from public,anon,authenticated;
create table public.pendencia_acoes(id bigint generated by default as identity primary key,chave text not null unique,area text not null check(area in ('operacao','financeiro','cadastros')),responsavel text not null default '' check(length(responsavel)<=100),proxima_acao text not null default '' check(length(proxima_acao)<=300),adiada_ate timestamptz,atualizado_em timestamptz not null default now(),autor uuid);
alter table public.pendencia_acoes enable row level security;
revoke all on public.pendencia_acoes from public,anon,authenticated;
grant select on public.pendencia_acoes to authenticated;
create policy pending_read on public.pendencia_acoes for select to authenticated using((select direct_private.member_role())='admin' or area='financeiro' and (select direct_private.member_role())='financeiro' or area in ('operacao','cadastros') and (select direct_private.member_role())='operacao');
create function public.direct_pending_save(p jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare member text:=coalesce(direct_private.member_role(),'');a text:=direct_private.pending_area(p->>'chave');old public.pendencia_acoes;due timestamptz:=(p->>'adiada_ate')::timestamptz;result public.pendencia_acoes;begin
if auth.uid() is null or a is null or not(member='admin' or member='financeiro' and a='financeiro' or member='operacao' and a in ('operacao','cadastros')) then raise exception 'Sem permissão para organizar esta pendência.' using errcode='42501';end if;
if length(coalesce(p->>'responsavel',''))>100 or length(coalesce(p->>'proxima_acao',''))>300 then raise exception 'Texto muito longo.';end if;
if due is not null and (due<now() or due>now()+interval '30 days') then raise exception 'Escolha um prazo futuro de até 30 dias.';end if;
-- Lock the key even before its first insert, avoiding two initial saves racing.
perform pg_advisory_xact_lock(hashtextextended('direct-pending:'||(p->>'chave'),0));
select * into old from public.pendencia_acoes where chave=p->>'chave' for update;
if old.id is not null and ((p->>'expected_updated_at') is null or old.atualizado_em<>(p->>'expected_updated_at')::timestamptz) then raise exception 'Outra pessoa alterou esta organização. Atualize e compare antes de salvar.' using errcode='40001';end if;
insert into public.pendencia_acoes(chave,area,responsavel,proxima_acao,adiada_ate,autor) values(p->>'chave',a,coalesce(p->>'responsavel',''),coalesce(p->>'proxima_acao',''),due,auth.uid()) on conflict(chave) do update set responsavel=excluded.responsavel,proxima_acao=excluded.proxima_acao,adiada_ate=excluded.adiada_ate,atualizado_em=clock_timestamp(),autor=auth.uid() returning * into result;
return to_jsonb(result);end;$$;
revoke all on function public.direct_pending_save(jsonb) from public,anon,authenticated;
grant execute on function public.direct_pending_save(jsonb) to authenticated;
create trigger direct_revision after insert or update or delete on public.pendencia_acoes for each statement execute function direct_private.bump_revision();
create table public.substituicao_contatos(id bigint generated by default as identity primary key,escala_id bigint not null references public.pedido_escalas(id) on delete cascade,diarista_id bigint not null references public.diaristas(id) on delete cascade,resposta text not null check(resposta in ('aguardando','confirmou','recusou')),atualizado_em timestamptz not null default now(),unique(escala_id,diarista_id));
create index substituicao_contatos_diarista on public.substituicao_contatos(diarista_id);
alter table public.substituicao_contatos enable row level security;
revoke all on public.substituicao_contatos from public,anon,authenticated;
grant select on public.substituicao_contatos to authenticated;
create policy replacement_read on public.substituicao_contatos for select to authenticated using((select direct_private.member_role()) in ('admin','operacao'));
create function public.direct_replacement_response(p jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare result public.substituicao_contatos;begin
if auth.uid() is null or coalesce(direct_private.member_role(),'') not in ('admin','operacao') then raise exception 'Sem permissão.' using errcode='42501';end if;
if p->>'resposta' not in ('aguardando','confirmou','recusou') then raise exception 'Resposta inválida.';end if;
if not exists(select 1 from public.pedido_escalas s join public.pedidos o on o.id=s.pedido_id where s.id=(p->>'escala_id')::bigint and s.status<>'presente' and s.substituida_por_escala_id is null and o.situacao not in ('cancelado','concluido')) then raise exception 'Substituição indisponível.';end if;
if not exists(select 1 from public.diaristas where id=(p->>'diarista_id')::bigint and not bloqueada) then raise exception 'Cadastro indisponível.';end if;
insert into public.substituicao_contatos(escala_id,diarista_id,resposta) values((p->>'escala_id')::bigint,(p->>'diarista_id')::bigint,p->>'resposta') on conflict(escala_id,diarista_id) do update set resposta=excluded.resposta,atualizado_em=clock_timestamp() returning * into result;return to_jsonb(result);end;$$;
revoke all on function public.direct_replacement_response(jsonb) from public,anon,authenticated;
grant execute on function public.direct_replacement_response(jsonb) to authenticated;
create trigger direct_revision after insert or update or delete on public.substituicao_contatos for each statement execute function direct_private.bump_revision();
create function public.direct_replace_order_remaining(p_pedido_id bigint,p_escala_id bigint,p_diarista_id bigint,p_motivo text,p_disponibilidade_confirmada boolean) returns jsonb language plpgsql security definer set search_path='' as $$
declare old public.pedido_escalas;s public.pedido_escalas;result jsonb:='[]'::jsonb;begin
if auth.uid() is null or coalesce(direct_private.member_role(),'') not in ('admin','operacao') then raise exception 'Sem permissão.' using errcode='42501';end if;
perform 1 from public.pedidos where id=p_pedido_id for update;
select * into old from public.pedido_escalas where id=p_escala_id and pedido_id=p_pedido_id;
if old.id is null then raise exception 'Escala não encontrada.';end if;
for s in select * from public.pedido_escalas where pedido_id=p_pedido_id and diarista_id=old.diarista_id and data>=old.data and status<>'presente' and substituida_por_escala_id is null order by data,id for update loop
result:=result||jsonb_build_array(public.direct_replace_order_worker(p_pedido_id,s.id,p_diarista_id,p_motivo,p_disponibilidade_confirmada));end loop;
if jsonb_array_length(result)=0 then raise exception 'Nenhum dia para substituir.';end if;return result;end;$$;
revoke all on function public.direct_replace_order_remaining(bigint,bigint,bigint,text,boolean) from public,anon,authenticated;
grant execute on function public.direct_replace_order_remaining(bigint,bigint,bigint,text,boolean) to authenticated;
create function direct_private.backup_snapshot_v8() returns jsonb language sql stable security definer set search_path='' as $$
with data as(select direct_private.backup_snapshot_v7()->'tables'||jsonb_build_object('pendencia_acoes',(select coalesce(jsonb_agg(to_jsonb(t) order by id),'[]'::jsonb) from public.pendencia_acoes t),'substituicao_contatos',(select coalesce(jsonb_agg(to_jsonb(t) order by id),'[]'::jsonb) from public.substituicao_contatos t)) tables)
select jsonb_build_object('format','direct-data-v8','exportedAt',now(),'tables',tables,'snapshot',jsonb_build_object('consistent',true,'counts',(select jsonb_object_agg(key,jsonb_array_length(value)) from jsonb_each(data.tables)))) from data;$$;
revoke all on function direct_private.backup_snapshot_v8() from public,anon,authenticated;
create function public.direct_backup_snapshot_v8() returns jsonb language plpgsql stable security definer set search_path='' as $$begin if auth.uid() is null or coalesce(direct_private.member_role(),'')<>'admin' then raise exception 'Somente administrador.' using errcode='42501';end if;return direct_private.backup_snapshot_v8();end;$$;
revoke all on function public.direct_backup_snapshot_v8() from public,anon,authenticated;grant execute on function public.direct_backup_snapshot_v8() to authenticated;
do $$declare ddl text;begin select pg_get_functiondef('public.direct_backup_bundle(text,uuid)'::regprocedure) into ddl;execute replace(ddl,'direct_private.backup_snapshot_v7()','direct_private.backup_snapshot_v8()');end;$$;
