create table direct_private.rede_links (
 id bigint generated by default as identity primary key,
 rede text not null check(length(trim(rede)) between 1 and 180),
 token text not null unique default encode(extensions.gen_random_bytes(32),'hex'),
 ativo boolean not null default true,
 expira_em timestamptz not null default now()+interval '90 days',
 criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create unique index rede_links_network on direct_private.rede_links(lower(trim(rede)));
alter table direct_private.rede_links enable row level security;
revoke all on direct_private.rede_links from public,anon,authenticated;

create function direct_private.network_token(p_token text) returns text language plpgsql security invoker set search_path='' as $$
declare network text;
begin
 if coalesce(p_token,'') !~ '^[a-f0-9]{64}$' then raise exception 'Link inválido ou expirado. Peça um novo link à Direct.' using errcode='42501';end if;
 select rede into network from direct_private.rede_links where token=p_token and ativo and expira_em>now();
 if network is null then raise exception 'Link inválido ou expirado. Peça um novo link à Direct.' using errcode='42501';end if;
 return network;
end;$$;
create function direct_private.network_store(p_token text,p_loja_id bigint) returns public.lojas language plpgsql security invoker set search_path='' as $$
declare network text; store public.lojas;
begin
 network:=direct_private.network_token(p_token);
 select * into store from public.lojas where id=p_loja_id and lower(trim(rede))=lower(trim(network));
 if store.id is null then raise exception 'Escolha uma loja desta rede.' using errcode='42501';end if;
 return store;
end;$$;

create function public.direct_network_links() returns jsonb language plpgsql stable security definer set search_path='' as $$
begin
 if auth.uid() is null or coalesce(direct_private.member_role(),'') not in ('admin','operacao') then raise exception 'Sem permissão para links das redes.' using errcode='42501';end if;
 return (select coalesce(jsonb_agg(jsonb_build_object('rede',s.rede,'lojas',s.lojas,'token',case when x.ativo and x.expira_em>now() then x.token else null end,'ativo',coalesce(x.ativo,false),'expira_em',x.expira_em) order by s.rede),'[]'::jsonb) from (select min(rede) rede,count(*) lojas from public.lojas group by lower(trim(rede))) s left join direct_private.rede_links x on lower(trim(x.rede))=lower(trim(s.rede)));
end;$$;
create function public.direct_network_link(p_rede text,p_acao text default 'consultar') returns jsonb language plpgsql security definer set search_path='' as $$
declare link direct_private.rede_links; network text;
begin
 if auth.uid() is null or coalesce(direct_private.member_role(),'') not in ('admin','operacao') then raise exception 'Sem permissão para links das redes.' using errcode='42501';end if;
 if p_acao is null or p_acao not in ('consultar','renovar','revogar') then raise exception 'Ação inválida.';end if;
 select min(rede) into network from public.lojas where lower(trim(rede))=lower(trim(p_rede));
 if network is null then raise exception 'Rede sem lojas cadastradas.';end if;
 insert into direct_private.rede_links(rede) values(network) on conflict(lower(trim(rede))) do nothing;
 select * into link from direct_private.rede_links where lower(trim(rede))=lower(trim(network)) for update;
 if p_acao='renovar' then update direct_private.rede_links set token=encode(extensions.gen_random_bytes(32),'hex'),ativo=true,expira_em=now()+interval '90 days',atualizado_em=now() where id=link.id returning * into link;
 elsif p_acao='revogar' then update direct_private.rede_links set ativo=false,atualizado_em=now() where id=link.id returning * into link;end if;
 return jsonb_build_object('rede',network,'token',case when link.ativo and link.expira_em>now() then link.token else null end,'ativo',link.ativo,'expira_em',link.expira_em);
end;$$;
create function public.direct_network_context(p_token text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare network text;
begin
 network:=direct_private.network_token(p_token);
 return jsonb_build_object('rede',network,'lojas',(select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'rede',s.rede,'nome',s.nome,'endereco',s.endereco,'cidade',s.cidade,'uf',s.uf) order by s.nome,s.cidade),'[]'::jsonb) from public.lojas s where lower(trim(s.rede))=lower(trim(network))),'setores',(select coalesce(jsonb_agg(setor order by setor),'[]'::jsonb) from (select distinct setor from public.tarifas_setores) x));
end;$$;
create function public.direct_network_submit(p_token text,p_loja_id bigint,p_dados jsonb,p_chave uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare s public.lojas; data jsonb; r public.loja_solicitacoes;
begin
 perform direct_private.network_token(p_token);
 perform 1 from direct_private.rede_links where token=p_token for update;
 s:=direct_private.network_store(p_token,p_loja_id);
 -- Serialize with other requests to the same store, including its older portal.
 perform 1 from public.lojas where id=s.id for update;
 s:=direct_private.network_store(p_token,p_loja_id);
 data:=direct_private.store_draft(p_dados,s);
 if p_chave is null then raise exception 'Chave da solicitação ausente.';end if;
 select * into r from public.loja_solicitacoes where loja_id=s.id and chave=p_chave;
 if r.id is not null then if r.dados<>data then raise exception 'Esta solicitação já foi enviada com outros dados.';end if;return jsonb_build_object('id',r.id,'estado',r.estado);end if;
 if exists(select 1 from jsonb_array_elements(data->'turnos') x(value) where (x.value->>'data')::date<(now() at time zone 'America/Fortaleza')::date or (x.value->>'data')::date>(now() at time zone 'America/Fortaleza')::date+366) then raise exception 'Envie datas de hoje até um ano à frente.';end if;
 if (select count(*) from public.loja_solicitacoes where loja_id=s.id and criado_em>now()-interval '1 day')>=60 then raise exception 'Limite de solicitações atingido. Fale com a Direct.';end if;
 insert into public.loja_solicitacoes(loja_id,chave,dados) values(s.id,p_chave,data) returning * into r;
 return jsonb_build_object('id',r.id,'estado',r.estado);
end;$$;
create function public.direct_network_orders(p_token text,p_loja_id bigint) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare s public.lojas; orders jsonb; requests jsonb;
begin s:=direct_private.network_store(p_token,p_loja_id);
 select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'setor',p.setor,'quantidade_diaristas',p.quantidade_diaristas,'turnos',p.turnos,'situacao',p.situacao,'escalas',(select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'data',e.data,'nome',d.nome,'status',e.status,'confirmacao',e.confirmacao,'conferencia',(select jsonb_build_object('presenca',v.presenca,'estado',v.estado) from public.loja_validacoes v where v.escala_id=e.id)) order by e.data,e.id),'[]'::jsonb) from public.pedido_escalas e join public.diaristas d on d.id=e.diarista_id where e.pedido_id=p.id)) order by p.id desc),'[]'::jsonb) into orders from (select * from public.pedidos where lower(supermercado)=lower(s.rede) and lower(unidade)=lower(s.nome) order by id desc limit 200) p;
 select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'dados',r.dados,'estado',r.estado,'pedido_id',r.pedido_id,'motivo',r.motivo,'criado_em',r.criado_em) order by r.id desc),'[]'::jsonb) into requests from (select * from public.loja_solicitacoes where loja_id=s.id order by id desc limit 200) r;
 return jsonb_build_object('pedidos',orders,'solicitacoes',requests);
end;$$;
create function public.direct_network_check(p_token text,p_loja_id bigint,p_escala_id bigint,p_presenca text,p_observacao text default '') returns jsonb language plpgsql security definer set search_path='' as $$
declare s public.lojas; e public.pedido_escalas; v public.loja_validacoes;
begin
 perform direct_private.network_token(p_token);perform 1 from direct_private.rede_links where token=p_token for update;
 -- Recheck after acquiring the row lock: renewal/revocation may have won the race.
 s:=direct_private.network_store(p_token,p_loja_id);
 select esc.* into e from public.pedido_escalas esc join public.pedidos p on p.id=esc.pedido_id where esc.id=p_escala_id and lower(p.supermercado)=lower(s.rede) and lower(p.unidade)=lower(s.nome) and p.situacao<>'cancelado' for update of esc;
 if e.id is null or e.status='desistiu' then raise exception 'Atendimento não disponível nesta loja.';end if;
 if e.data>(now() at time zone 'America/Fortaleza')::date then raise exception 'Confira o atendimento após o dia da diária.';end if;
 if p_presenca not in ('presente','falta') or p_presenca is null or length(coalesce(p_observacao,''))>500 then raise exception 'Conferência inválida.';end if;
 select * into v from public.loja_validacoes where escala_id=e.id for update;
 if v.estado='aplicada' then raise exception 'Conferência já aplicada. Fale com a Direct para corrigir.';end if;
 insert into public.loja_validacoes(loja_id,escala_id,presenca,observacao) values(s.id,e.id,p_presenca,coalesce(p_observacao,'')) on conflict(escala_id) do update set presenca=excluded.presenca,observacao=excluded.observacao,estado='pendente',motivo='',atualizado_em=now() returning * into v;
 return jsonb_build_object('id',v.id,'estado',v.estado);
end;$$;

revoke all on function direct_private.network_token(text),direct_private.network_store(text,bigint) from public,anon,authenticated;
revoke all on function public.direct_network_links(),public.direct_network_link(text,text),public.direct_network_context(text),public.direct_network_submit(text,bigint,jsonb,uuid),public.direct_network_orders(text,bigint),public.direct_network_check(text,bigint,bigint,text,text) from public,anon,authenticated;
grant execute on function public.direct_network_links(),public.direct_network_link(text,text) to authenticated;
grant execute on function public.direct_network_context(text),public.direct_network_submit(text,bigint,jsonb,uuid),public.direct_network_orders(text,bigint),public.direct_network_check(text,bigint,bigint,text,text) to anon,authenticated;

create function direct_private.backup_snapshot_v9() returns jsonb language sql stable security invoker set search_path='' as $$
with data as(select direct_private.backup_snapshot_v8()->'tables'||jsonb_build_object('rede_links',(select coalesce(jsonb_agg(to_jsonb(t) order by id),'[]'::jsonb) from direct_private.rede_links t)) tables)
select jsonb_build_object('format','direct-data-v9','exportedAt',now(),'tables',tables,'snapshot',jsonb_build_object('consistent',true,'counts',(select jsonb_object_agg(key,jsonb_array_length(value)) from jsonb_each(data.tables)))) from data;$$;
revoke all on function direct_private.backup_snapshot_v9() from public,anon,authenticated;
create function public.direct_backup_snapshot_v9() returns jsonb language plpgsql stable security definer set search_path='' as $$begin if auth.uid() is null or coalesce(direct_private.member_role(),'')<>'admin' then raise exception 'Somente administrador.' using errcode='42501';end if;return direct_private.backup_snapshot_v9();end;$$;
revoke all on function public.direct_backup_snapshot_v9() from public,anon,authenticated;grant execute on function public.direct_backup_snapshot_v9() to authenticated;
do $$declare ddl text;begin select pg_get_functiondef('public.direct_backup_bundle(text,uuid)'::regprocedure) into ddl;execute replace(ddl,'direct_private.backup_snapshot_v8()','direct_private.backup_snapshot_v9()');end;$$;
create or replace function public.direct_store_submit(p_token text,p_dados jsonb,p_chave uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare s public.lojas; data jsonb; r public.loja_solicitacoes;
begin
 s:=direct_private.store_token(p_token);perform 1 from direct_private.loja_links where loja_id=s.id for update;
 -- Recheck after acquiring the row lock: renewal/revocation may have won the race.
 s:=direct_private.store_token(p_token);
 perform 1 from public.lojas where id=s.id for update;
 data:=direct_private.store_draft(p_dados,s);
 if p_chave is null then raise exception 'Chave da solicitação ausente.';end if;
 select * into r from public.loja_solicitacoes where loja_id=s.id and chave=p_chave;
 if r.id is not null then if r.dados<>data then raise exception 'Esta solicitação já foi enviada com outros dados.';end if;return jsonb_build_object('id',r.id,'estado',r.estado);end if;
 if exists(select 1 from jsonb_array_elements(data->'turnos') x(value) where (x.value->>'data')::date<(now() at time zone 'America/Fortaleza')::date or (x.value->>'data')::date>(now() at time zone 'America/Fortaleza')::date+366) then raise exception 'Envie datas de hoje até um ano à frente.';end if;
 if (select count(*) from public.loja_solicitacoes where loja_id=s.id and criado_em>now()-interval '1 day')>=60 then raise exception 'Limite de solicitações atingido. Fale com a Direct.';end if;
 insert into public.loja_solicitacoes(loja_id,chave,dados) values(s.id,p_chave,data) returning * into r;
 return jsonb_build_object('id',r.id,'estado',r.estado);
end;$$;

