create table if not exists public.direct_admins (
  email text primary key check (email = lower(email))
);
alter table public.direct_admins enable row level security;
revoke all on public.direct_admins from anon, authenticated;
grant select on public.direct_admins to authenticated;
create policy "admin can read own membership" on public.direct_admins
  for select to authenticated
  using (email = (select auth.jwt() ->> 'email'));

create table if not exists public.diaristas (
  id bigint generated by default as identity primary key,
  nome text not null,
  cpf text not null unique check (cpf ~ '^[0-9]{11}$'),
  setores jsonb not null default '[]'::jsonb,
  cep text not null,
  logradouro text not null,
  numero text not null,
  complemento text not null default '',
  bairro text not null,
  cidade text not null default 'Fortaleza',
  uf text not null default 'CE',
  trabalhando boolean not null default false,
  local_trabalho text not null default '',
  disponibilidade jsonb not null default '[]'::jsonb,
  pode_se_deslocar boolean not null default true,
  transporte text not null default '',
  observacoes_locomocao text not null default '',
  bloqueada boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
create index if not exists idx_diaristas_nome on public.diaristas (nome);
create table if not exists public.diarias (
  id bigint generated by default as identity primary key,
  diarista_id bigint not null references public.diaristas(id) on delete cascade,
  data date not null,
  local text not null,
  setor text not null,
  observacoes text not null default '',
  data_pagamento date,
  valor_centavos bigint check (valor_centavos > 0),
  vencimento_pagamento date,
  forma_pagamento text not null default '',
  criado_em timestamptz not null default now()
);
create index if not exists idx_diarias_diarista_data on public.diarias (diarista_id, data desc);
create table if not exists public.financeiro_lancamentos (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('receita', 'despesa')),
  descricao text not null,
  categoria text not null,
  contraparte text not null,
  valor_centavos bigint not null check (valor_centavos > 0),
  vencimento date not null,
  data_pagamento date,
  forma_pagamento text not null default '',
  observacoes text not null default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
create index if not exists idx_financeiro_vencimento on public.financeiro_lancamentos (vencimento);
create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  supermercado text not null,
  unidade text not null default '',
  contato text not null default '',
  setor text not null,
  quantidade_diaristas integer not null check (quantidade_diaristas between 1 and 100),
  turnos jsonb not null default '[]'::jsonb,
  situacao text not null default 'novo' check (situacao in ('novo', 'em_selecao', 'confirmado', 'concluido', 'cancelado')),
  observacoes text not null default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
create index if not exists idx_pedidos_situacao on public.pedidos (situacao);
create table if not exists public.lojas (
  id bigint generated by default as identity primary key,
  rede text not null,
  nome text not null,
  endereco text not null,
  bairro text not null default '',
  cidade text not null,
  uf text not null default 'CE',
  fonte_url text not null default '',
  situacao text not null check (situacao in ('confirmado', 'revisar')),
  observacao text not null default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (rede, nome)
);
create index if not exists idx_lojas_rede_cidade on public.lojas (rede, cidade);
alter table public.diaristas enable row level security;
alter table public.diarias enable row level security;
alter table public.financeiro_lancamentos enable row level security;
alter table public.pedidos enable row level security;
alter table public.lojas enable row level security;
revoke all on public.diaristas, public.diarias, public.financeiro_lancamentos, public.pedidos, public.lojas from anon;
grant select, insert, update, delete on public.diaristas, public.diarias, public.financeiro_lancamentos, public.pedidos, public.lojas to authenticated;
grant usage, select on all sequences in schema public to authenticated;
create policy "admin manages diaristas" on public.diaristas for all to authenticated
  using ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))))
  with check ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))));
create policy "admin manages diarias" on public.diarias for all to authenticated
  using ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))))
  with check ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))));
create policy "admin manages finance" on public.financeiro_lancamentos for all to authenticated
  using ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))))
  with check ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))));
create policy "admin manages pedidos" on public.pedidos for all to authenticated
  using ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))))
  with check ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))));
create policy "admin manages lojas" on public.lojas for all to authenticated
  using ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))))
  with check ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))));
