create table direct_private.loja_links (
 id bigint generated by default as identity primary key,
 loja_id bigint not null unique references public.lojas(id) on delete cascade,
 token text not null unique default encode(extensions.gen_random_bytes(32),'hex'),
 ativo boolean not null default true, expira_em timestamptz not null default now()+interval '90 days',
 criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
alter table direct_private.loja_links enable row level security;
revoke all on direct_private.loja_links from public,anon,authenticated;
create table public.loja_solicitacoes (
 id bigint generated by default as identity primary key,
 loja_id bigint not null references public.lojas(id) on delete restrict,
 chave uuid not null, dados jsonb not null, estado text not null default 'pendente' check(estado in ('pendente','aprovada','recusada')),
 pedido_id bigint references public.pedidos(id) on delete set null,
 motivo text not null default '' check(length(motivo)<=500),
 criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now(),
 unique(loja_id,chave)
);
create index loja_solicitacoes_loja_estado on public.loja_solicitacoes(loja_id,estado);
create index loja_solicitacoes_pedido on public.loja_solicitacoes(pedido_id);
create table public.loja_validacoes (
 id bigint generated by default as identity primary key,
 loja_id bigint not null references public.lojas(id) on delete restrict,
 escala_id bigint not null unique references public.pedido_escalas(id) on delete cascade,
 presenca text not null check(presenca in ('presente','falta')),
 observacao text not null default '' check(length(observacao)<=500),
 estado text not null default 'pendente' check(estado in ('pendente','aplicada','recusada')),
 motivo text not null default '' check(length(motivo)<=500),
 criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create index loja_validacoes_loja_estado on public.loja_validacoes(loja_id,estado);
alter table public.loja_solicitacoes enable row level security;
alter table public.loja_validacoes enable row level security;
revoke all on public.loja_solicitacoes,public.loja_validacoes from public,anon,authenticated;
grant select on public.loja_solicitacoes,public.loja_validacoes to authenticated;
create policy store_requests_read on public.loja_solicitacoes for select to authenticated using((select direct_private.member_role()) in ('admin','operacao'));
create policy store_checks_read on public.loja_validacoes for select to authenticated using((select direct_private.member_role()) in ('admin','operacao'));
create trigger audit_store_requests after insert or update or delete on public.loja_solicitacoes for each row execute function direct_private.log_change();
create trigger audit_store_checks after insert or update or delete on public.loja_validacoes for each row execute function direct_private.log_change();
create function direct_private.store_token(p_token text) returns public.lojas language plpgsql security invoker set search_path='' as $$
declare store public.lojas;
begin
 if coalesce(p_token,'') !~ '^[a-f0-9]{64}$' then raise exception 'Link inválido ou expirado. Peça um novo link à Direct.' using errcode='42501';end if;
 select l.* into store from public.lojas l join direct_private.loja_links x on x.loja_id=l.id where x.token=p_token and x.ativo and x.expira_em>now();
 if store.id is null then raise exception 'Link inválido ou expirado. Peça um novo link à Direct.' using errcode='42501';end if;
 return store;
end;$$;
create function direct_private.store_draft(p jsonb, store public.lojas) returns jsonb language plpgsql security invoker set search_path='' as $$
declare n integer; t jsonb;
begin
 if jsonb_typeof(p) is distinct from 'object' or jsonb_typeof(p->'turnos') is distinct from 'array' then raise exception 'Pedido inválido.';end if;
 n:=(p->>'quantidade_diaristas')::integer;if n is null or n not between 1 and 100 then raise exception 'Informe de 1 a 100 diaristas.';end if;
 if length(trim(coalesce(p->>'setor',''))) not between 1 and 80 or not exists(select 1 from public.tarifas_setores where lower(setor)=lower(trim(p->>'setor'))) then raise exception 'Escolha um setor cadastrado.';end if;
 if jsonb_array_length(p->'turnos') not between 1 and 90 then raise exception 'Informe de 1 a 90 dias.';end if;
 for t in select value from jsonb_array_elements(p->'turnos') loop
  if coalesce(t->>'data','') !~ '^\d{4}-\d{2}-\d{2}$' or (t->>'data')::date::text<>t->>'data' or coalesce(t->>'inicio','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or coalesce(t->>'fim','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or t->>'inicio'>=t->>'fim' then raise exception 'Confira datas e horários.';end if;
 end loop;
 if (select count(distinct x.value->>'data') from jsonb_array_elements(p->'turnos') x(value))<>jsonb_array_length(p->'turnos') then raise exception 'Datas repetidas.';end if;
 if length(coalesce(p->>'contato',''))>180 or length(coalesce(p->>'observacoes',''))>500 then raise exception 'Texto muito longo.';end if;
 return jsonb_build_object('supermercado',store.rede,'unidade',store.nome,'setor',trim(p->>'setor'),'quantidade_diaristas',n,'situacao','novo','contato',coalesce(p->>'contato',''),'observacoes',coalesce(p->>'observacoes',''),'turnos',(select jsonb_agg(jsonb_build_object('data',x.value->>'data','inicio',x.value->>'inicio','fim',x.value->>'fim') order by x.value->>'data') from jsonb_array_elements(p->'turnos') x(value)));
end;$$;
create function public.direct_store_link(p_loja_id bigint,p_acao text default 'consultar') returns jsonb language plpgsql security definer set search_path='' as $$
declare link direct_private.loja_links;
begin
 if auth.uid() is null or coalesce(direct_private.member_role(),'') not in ('admin','operacao') then raise exception 'Sem permissão para links de lojas.' using errcode='42501';end if;
 if p_acao not in ('consultar','renovar','revogar') then raise exception 'Ação inválida.';end if;
 if not exists(select 1 from public.lojas where id=p_loja_id) then raise exception 'Loja não encontrada.';end if;
 insert into direct_private.loja_links(loja_id) values(p_loja_id) on conflict(loja_id) do nothing;
 select * into link from direct_private.loja_links where loja_id=p_loja_id for update;
 if p_acao='renovar' then update direct_private.loja_links set token=encode(extensions.gen_random_bytes(32),'hex'),ativo=true,expira_em=now()+interval '90 days',atualizado_em=now() where id=link.id returning * into link;
 elsif p_acao='revogar' then update direct_private.loja_links set ativo=false,atualizado_em=now() where id=link.id returning * into link;end if;
 return jsonb_build_object('token',case when link.ativo and link.expira_em>now() then link.token else null end,'ativo',link.ativo,'expira_em',link.expira_em);
end;$$;
create function public.direct_store_context(p_token text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare s public.lojas;
begin s:=direct_private.store_token(p_token);
 return jsonb_build_object('loja',jsonb_build_object('id',s.id,'rede',s.rede,'nome',s.nome,'endereco',s.endereco,'cidade',s.cidade,'uf',s.uf),'setores',(select coalesce(jsonb_agg(setor order by setor),'[]'::jsonb) from (select distinct setor from public.tarifas_setores) x));
end;$$;
create function public.direct_store_orders(p_token text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare s public.lojas; orders jsonb; requests jsonb;
begin s:=direct_private.store_token(p_token);
 select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'setor',p.setor,'quantidade_diaristas',p.quantidade_diaristas,'turnos',p.turnos,'situacao',p.situacao,'escalas',(select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'data',e.data,'nome',d.nome,'status',e.status,'confirmacao',e.confirmacao,'conferencia',(select jsonb_build_object('presenca',v.presenca,'estado',v.estado) from public.loja_validacoes v where v.escala_id=e.id)) order by e.data,e.id),'[]'::jsonb) from public.pedido_escalas e join public.diaristas d on d.id=e.diarista_id where e.pedido_id=p.id)) order by p.id desc),'[]'::jsonb) into orders from (select * from public.pedidos where lower(supermercado)=lower(s.rede) and lower(unidade)=lower(s.nome) order by id desc limit 200) p;
 select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'dados',r.dados,'estado',r.estado,'pedido_id',r.pedido_id,'motivo',r.motivo,'criado_em',r.criado_em) order by r.id desc),'[]'::jsonb) into requests from (select * from public.loja_solicitacoes where loja_id=s.id order by id desc limit 200) r;
 return jsonb_build_object('pedidos',orders,'solicitacoes',requests);
end;$$;
create function public.direct_store_submit(p_token text,p_dados jsonb,p_chave uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare s public.lojas; data jsonb; r public.loja_solicitacoes;
begin
 s:=direct_private.store_token(p_token);perform 1 from direct_private.loja_links where loja_id=s.id for update;
 data:=direct_private.store_draft(p_dados,s);
 if p_chave is null then raise exception 'Chave da solicitação ausente.';end if;
 select * into r from public.loja_solicitacoes where loja_id=s.id and chave=p_chave;
 if r.id is not null then if r.dados<>data then raise exception 'Esta solicitação já foi enviada com outros dados.';end if;return jsonb_build_object('id',r.id,'estado',r.estado);end if;
 if exists(select 1 from jsonb_array_elements(data->'turnos') x(value) where (x.value->>'data')::date<(now() at time zone 'America/Fortaleza')::date or (x.value->>'data')::date>(now() at time zone 'America/Fortaleza')::date+366) then raise exception 'Envie datas de hoje até um ano à frente.';end if;
 if (select count(*) from public.loja_solicitacoes where loja_id=s.id and criado_em>now()-interval '1 day')>=60 then raise exception 'Limite de solicitações atingido. Fale com a Direct.';end if;
 insert into public.loja_solicitacoes(loja_id,chave,dados) values(s.id,p_chave,data) returning * into r;
 return jsonb_build_object('id',r.id,'estado',r.estado);
end;$$;
create function public.direct_store_check(p_token text,p_escala_id bigint,p_presenca text,p_observacao text default '') returns jsonb language plpgsql security definer set search_path='' as $$
declare s public.lojas; e public.pedido_escalas; v public.loja_validacoes;
begin
 s:=direct_private.store_token(p_token);perform 1 from direct_private.loja_links where loja_id=s.id for update;
 select esc.* into e from public.pedido_escalas esc join public.pedidos p on p.id=esc.pedido_id where esc.id=p_escala_id and lower(p.supermercado)=lower(s.rede) and lower(p.unidade)=lower(s.nome) and p.situacao<>'cancelado' for update of esc;
 if e.id is null or e.status='desistiu' then raise exception 'Atendimento não disponível nesta loja.';end if;
 if e.data>(now() at time zone 'America/Fortaleza')::date then raise exception 'Confira o atendimento após o dia da diária.';end if;
 if p_presenca not in ('presente','falta') or p_presenca is null or length(coalesce(p_observacao,''))>500 then raise exception 'Conferência inválida.';end if;
 select * into v from public.loja_validacoes where escala_id=e.id for update;
 if v.estado='aplicada' then raise exception 'Conferência já aplicada. Fale com a Direct para corrigir.';end if;
 insert into public.loja_validacoes(loja_id,escala_id,presenca,observacao) values(s.id,e.id,p_presenca,coalesce(p_observacao,'')) on conflict(escala_id) do update set presenca=excluded.presenca,observacao=excluded.observacao,estado='pendente',motivo='',atualizado_em=now() returning * into v;
 return jsonb_build_object('id',v.id,'estado',v.estado);
end;$$;
create function public.direct_store_review_request(p_id bigint,p_dados jsonb,p_aceitar boolean,p_motivo text default '') returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.loja_solicitacoes; s public.lojas; data jsonb; created public.pedidos;
begin
 if auth.uid() is null or coalesce(direct_private.member_role(),'') not in ('admin','operacao') then raise exception 'Sem permissão para revisar.' using errcode='42501';end if;
 select * into r from public.loja_solicitacoes where id=p_id for update;if r.id is null or r.estado<>'pendente' then raise exception 'Solicitação já revisada ou inexistente. Atualize a lista.';end if;
 if p_aceitar is null then raise exception 'Escolha aprovar ou recusar.';end if;
 if not p_aceitar then
  if length(trim(coalesce(p_motivo,''))) not between 8 and 500 then raise exception 'Explique a recusa (8 a 500 caracteres).';end if;
  update public.loja_solicitacoes set estado='recusada',motivo=trim(p_motivo),atualizado_em=now() where id=r.id;return jsonb_build_object('ok',true);
 end if;
 select * into s from public.lojas where id=r.loja_id;data:=direct_private.store_draft(p_dados,s);
 if lower(coalesce(p_dados->>'supermercado',''))<>lower(s.rede) or lower(coalesce(p_dados->>'unidade',''))<>lower(s.nome) then raise exception 'A loja precisa corresponder à solicitação recebida.';end if;
 insert into public.pedidos(supermercado,unidade,contato,setor,quantidade_diaristas,turnos,situacao,observacoes) values(s.rede,s.nome,data->>'contato',data->>'setor',(data->>'quantidade_diaristas')::integer,data->'turnos','novo',data->>'observacoes') returning * into created;
 update public.loja_solicitacoes set estado='aprovada',pedido_id=created.id,dados=data,atualizado_em=now() where id=r.id;
 return to_jsonb(created);
end;$$;
create function public.direct_store_review_check(p_id bigint,p_aceitar boolean,p_motivo text default '') returns jsonb language plpgsql security definer set search_path='' as $$
declare v public.loja_validacoes; e public.pedido_escalas;
begin
 if auth.uid() is null or coalesce(direct_private.member_role(),'') not in ('admin','operacao') then raise exception 'Sem permissão para revisar.' using errcode='42501';end if;
 select * into v from public.loja_validacoes where id=p_id for update;if v.id is null or v.estado<>'pendente' then raise exception 'Conferência já revisada ou inexistente.';end if;
 if p_aceitar is null then raise exception 'Escolha aplicar ou recusar.';end if;
 if not p_aceitar then
  if length(trim(coalesce(p_motivo,''))) not between 8 and 500 then raise exception 'Explique a recusa (8 a 500 caracteres).';end if;
  update public.loja_validacoes set estado='recusada',motivo=trim(p_motivo),atualizado_em=now() where id=v.id;return jsonb_build_object('ok',true);
 end if;
 select * into e from public.pedido_escalas where id=v.escala_id for update;
 if e.status='desistiu' or not exists(select 1 from public.pedidos p join public.lojas s on lower(s.rede)=lower(p.supermercado) and lower(s.nome)=lower(p.unidade) where p.id=e.pedido_id and s.id=v.loja_id and p.situacao<>'cancelado') then raise exception 'Pedido/escala mudou. Revise a conferência.';end if;
 update public.pedido_escalas set status=v.presenca,
 falta_motivo=case when v.presenca='falta' and e.status<>'falta' then left(case when length(trim(v.observacao))>=5 then v.observacao else 'Falta informada pela loja no link privado' end,300) else e.falta_motivo end,
 atualizado_em=now() where id=e.id;
 if v.presenca='presente' then update public.pedido_escalas set loja_validacao='validado',loja_responsavel='Conferência por link da loja',loja_observacao=v.observacao where id=e.id;end if;
 update public.loja_validacoes set estado='aplicada',atualizado_em=now() where id=v.id;
 return jsonb_build_object('ok',true,'pedido_id',e.pedido_id);
end;$$;
revoke all on function direct_private.store_token(text),direct_private.store_draft(jsonb,public.lojas) from public,anon,authenticated;
revoke all on function public.direct_store_link(bigint,text),public.direct_store_context(text),public.direct_store_orders(text),public.direct_store_submit(text,jsonb,uuid),public.direct_store_check(text,bigint,text,text),public.direct_store_review_request(bigint,jsonb,boolean,text),public.direct_store_review_check(bigint,boolean,text) from public,anon,authenticated;
grant execute on function public.direct_store_context(text),public.direct_store_orders(text),public.direct_store_submit(text,jsonb,uuid),public.direct_store_check(text,bigint,text,text) to anon,authenticated;
grant execute on function public.direct_store_link(bigint,text),public.direct_store_review_request(bigint,jsonb,boolean,text),public.direct_store_review_check(bigint,boolean,text) to authenticated;

create function direct_private.backup_snapshot_v7() returns jsonb language sql stable security invoker set search_path='' as $$
 with previous as(select direct_private.backup_snapshot() payload), data as(select (payload->'tables')||jsonb_build_object(
 'loja_solicitacoes',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.loja_solicitacoes t),
 'loja_validacoes',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.loja_validacoes t),
 'loja_links',(select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from direct_private.loja_links t)) tables from previous)
 select jsonb_build_object('format','direct-data-v7','exportedAt',now(),'tables',tables,'snapshot',jsonb_build_object('consistent',true,'counts',(select jsonb_object_agg(key,jsonb_array_length(value)) from jsonb_each(data.tables)))) from data;
$$;
revoke all on function direct_private.backup_snapshot_v7() from public,anon,authenticated;
create function public.direct_backup_snapshot_v7() returns jsonb language plpgsql stable security definer set search_path='' as $$
begin
 if auth.uid() is null or coalesce(direct_private.member_role(),'')<>'admin' then raise exception 'Somente o administrador pode baixar a cópia.' using errcode='42501';end if;
 return direct_private.backup_snapshot_v7();
end;$$;
revoke all on function public.direct_backup_snapshot_v7() from public,anon,authenticated;
grant execute on function public.direct_backup_snapshot_v7() to authenticated;
