create table public.leituras_pendentes (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('diarista', 'pedido', 'indefinido')),
  chave text not null unique check (char_length(chave) between 1 and 300),
  dados jsonb not null default '{}'::jsonb check (jsonb_typeof(dados) = 'object'),
  texto text not null check (char_length(texto) between 1 and 30000),
  faltando jsonb not null default '[]'::jsonb check (jsonb_typeof(faltando) = 'array'),
  avisos jsonb not null default '[]'::jsonb check (jsonb_typeof(avisos) = 'array'),
  status text not null default 'pendente' check (status in ('pendente', 'resolvido')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
create index leituras_pendentes_status_idx on public.leituras_pendentes (status, criado_em desc);
alter table public.leituras_pendentes enable row level security;
revoke all on public.leituras_pendentes from anon;
grant select, insert, update, delete on public.leituras_pendentes to authenticated;
grant usage, select on sequence public.leituras_pendentes_id_seq to authenticated;
create policy "admin manages pending readings" on public.leituras_pendentes
  for all to authenticated
  using ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))))
  with check ((select exists(select 1 from public.direct_admins where email = (select auth.jwt() ->> 'email'))));
